START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'inventario') THEN
        CREATE SCHEMA inventario;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'catalogo') THEN
        CREATE SCHEMA catalogo;
    END IF;
END $EF$;

ALTER TABLE compras.compras ADD observaciones character varying(500);

CREATE TABLE inventario.almacenes (
    id_almacen bigint GENERATED BY DEFAULT AS IDENTITY,
    nombre_almacen text NOT NULL,
    CONSTRAINT pk_almacenes PRIMARY KEY (id_almacen)
);

CREATE TABLE catalogo.productos (
    id_producto bigint GENERATED BY DEFAULT AS IDENTITY,
    nombre_producto text NOT NULL,
    CONSTRAINT pk_productos PRIMARY KEY (id_producto)
);

CREATE TABLE configuracion.tipo_comprobante (
    id_tipo_comprobante bigint GENERATED BY DEFAULT AS IDENTITY,
    codigo text NOT NULL,
    nombre text NOT NULL,
    es_compra boolean NOT NULL,
    es_orden_compra boolean NOT NULL,
    activado boolean NOT NULL,
    CONSTRAINT pk_tipo_comprobante PRIMARY KEY (id_tipo_comprobante)
);

CREATE TABLE configuracion.tipo_documento (
    id_regla bigint GENERATED BY DEFAULT AS IDENTITY,
    codigo text NOT NULL,
    nombre text NOT NULL,
    CONSTRAINT pk_tipo_documento PRIMARY KEY (id_regla)
);

CREATE TABLE configuracion.series_comprobantes (
    id_serie bigint GENERATED BY DEFAULT AS IDENTITY,
    id_tipo_comprobante bigint NOT NULL,
    serie text NOT NULL,
    correlativo_actual integer NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    CONSTRAINT pk_series_comprobantes PRIMARY KEY (id_serie),
    CONSTRAINT fk_series_comprobantes_tipo_comprobante_id_tipo_comprobante FOREIGN KEY (id_tipo_comprobante) REFERENCES configuracion.tipo_comprobante (id_tipo_comprobante) ON DELETE CASCADE
);

CREATE INDEX ix_series_comprobantes_id_tipo_comprobante ON configuracion.series_comprobantes (id_tipo_comprobante);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260219175220_AddObservacionesToCompra', '8.0.8');

COMMIT;

