// <auto-generated />
using System;
using Identidad.API.Infrastructure.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identidad.API.Infrastructure.Migrations
{
    [DbContext(typeof(IdentidadDbContext))]
    [Migration("20260128013527_InicialIdentidad")]
    partial class InicialIdentidad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identidad")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Identidad.API.Domain.Entidades.Area", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_area");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreArea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_area");

                    b.Property<string>("UsuarioActualizacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("areas", "identidad");
                });

            modelBuilder.Entity("Identidad.API.Domain.Entidades.Cargo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_cargo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("IdArea")
                        .HasColumnType("bigint")
                        .HasColumnName("id_area");

                    b.Property<string>("NombreCargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_cargo");

                    b.Property<string>("UsuarioActualizacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.ToTable("cargos", "identidad");
                });

            modelBuilder.Entity("Identidad.API.Domain.Entidades.Empresa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean");

                    b.Property<string>("CorreoContacto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correo_contacto");

                    b.Property<string>("DireccionFiscal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("direccion_fiscal");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("MonedaPrincipal")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("moneda_principal");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre_comercial");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ruc");

                    b.Property<string>("SitioWeb")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sitio_web");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.Property<string>("UsuarioActualizacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("empresa", "configuracion");
                });

            modelBuilder.Entity("Identidad.API.Domain.Entidades.Permiso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_permiso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoPermiso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo_permiso");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Modulo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modulo");

                    b.Property<string>("UsuarioActualizacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("permisos", "identidad");
                });

            modelBuilder.Entity("Identidad.API.Domain.Entidades.Rol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_rol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_rol");

                    b.Property<string>("UsuarioActualizacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("roles", "identidad");
                });

            modelBuilder.Entity("Identidad.API.Domain.Entidades.RolPermiso", b =>
                {
                    b.Property<long>("IdRol")
                        .HasColumnType("bigint")
                        .HasColumnName("id_rol");

                    b.Property<long>("IdPermiso")
                        .HasColumnType("bigint")
                        .HasColumnName("id_permiso");

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsuarioActualizacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRol", "IdPermiso");

                    b.HasIndex("IdPermiso");

                    b.ToTable("roles_permisos", "identidad");
                });

            modelBuilder.Entity("Identidad.API.Domain.Entidades.SerieComprobante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_serie");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean");

                    b.Property<long>("CorrelativoActual")
                        .HasColumnType("bigint")
                        .HasColumnName("correlativo_actual");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("IdAlmacen")
                        .HasColumnType("bigint")
                        .HasColumnName("id_almacen");

                    b.Property<long>("IdTipoComprobante")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_comprobante");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("serie");

                    b.Property<string>("UsuarioActualizacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("series_comprobantes", "configuracion");
                });

            modelBuilder.Entity("Identidad.API.Domain.Entidades.TablaGeneral", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_tabla");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsSistema")
                        .HasColumnType("boolean")
                        .HasColumnName("es_sistema");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("UsuarioActualizacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("tablas_generales", "configuracion");
                });

            modelBuilder.Entity("Identidad.API.Domain.Entidades.TablaGeneralDetalle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IdTablaGeneral")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tabla");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("UsuarioActualizacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValorAdicional")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("valor_adicional");

                    b.HasKey("Id");

                    b.HasIndex("IdTablaGeneral");

                    b.ToTable("tablas_generales_detalle", "configuracion");
                });

            modelBuilder.Entity("Identidad.API.Domain.Entidades.Trabajador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_trabajador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("EmailCorporativo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email_corporativo");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<long?>("IdCargo")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cargo");

                    b.Property<long>("IdTipoDocumento")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_documento");

                    b.Property<long?>("IdUsuario")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_documento");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("UsuarioActualizacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("trabajadores", "identidad");
                });

            modelBuilder.Entity("Identidad.API.Domain.Entidades.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IdRol")
                        .HasColumnType("bigint")
                        .HasColumnName("id_rol");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.Property<string>("UsuarioActualizacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdRol");

                    b.ToTable("usuarios", "identidad");
                });

            modelBuilder.Entity("Identidad.API.Domain.Entidades.Cargo", b =>
                {
                    b.HasOne("Identidad.API.Domain.Entidades.Area", "Area")
                        .WithMany("Cargos")
                        .HasForeignKey("IdArea");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Identidad.API.Domain.Entidades.RolPermiso", b =>
                {
                    b.HasOne("Identidad.API.Domain.Entidades.Permiso", "Permiso")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identidad.API.Domain.Entidades.Rol", "Rol")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Identidad.API.Domain.Entidades.TablaGeneralDetalle", b =>
                {
                    b.HasOne("Identidad.API.Domain.Entidades.TablaGeneral", "TablaGeneral")
                        .WithMany("Detalles")
                        .HasForeignKey("IdTablaGeneral")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TablaGeneral");
                });

            modelBuilder.Entity("Identidad.API.Domain.Entidades.Trabajador", b =>
                {
                    b.HasOne("Identidad.API.Domain.Entidades.Cargo", "Cargo")
                        .WithMany("Trabajadores")
                        .HasForeignKey("IdCargo");

                    b.HasOne("Identidad.API.Domain.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario");

                    b.Navigation("Cargo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Identidad.API.Domain.Entidades.Usuario", b =>
                {
                    b.HasOne("Identidad.API.Domain.Entidades.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Identidad.API.Domain.Entidades.Area", b =>
                {
                    b.Navigation("Cargos");
                });

            modelBuilder.Entity("Identidad.API.Domain.Entidades.Cargo", b =>
                {
                    b.Navigation("Trabajadores");
                });

            modelBuilder.Entity("Identidad.API.Domain.Entidades.Permiso", b =>
                {
                    b.Navigation("RolesPermisos");
                });

            modelBuilder.Entity("Identidad.API.Domain.Entidades.Rol", b =>
                {
                    b.Navigation("RolesPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Identidad.API.Domain.Entidades.TablaGeneral", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
