// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ventas.API.Infrastructure.Datos;

#nullable disable

namespace Ventas.API.Infrastructure.Migrations
{
    [DbContext(typeof(VentasDbContext))]
    partial class VentasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ventas")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ventas.API.Domain.Entidades.Caja", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_caja");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean")
                        .HasColumnName("activado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime?>("FechaApertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_apertura");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<long>("IdAlmacen")
                        .HasColumnType("bigint")
                        .HasColumnName("id_almacen");

                    b.Property<long>("IdEstado")
                        .HasColumnType("bigint")
                        .HasColumnName("id_estado");

                    b.Property<long?>("IdUsuarioCajero")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario_cajero");

                    b.Property<decimal?>("MontoActual")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("monto_actual");

                    b.Property<decimal?>("MontoApertura")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("monto_apertura");

                    b.Property<string>("NombreCaja")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_caja");

                    b.Property<string>("UsuarioActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_modificacion");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_creacion");

                    b.HasKey("Id")
                        .HasName("pk_cajas");

                    b.ToTable("cajas", "ventas");
                });

            modelBuilder.Entity("Ventas.API.Domain.Entidades.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean")
                        .HasColumnName("activado");

                    b.Property<int?>("DiasCredito")
                        .HasColumnType("integer")
                        .HasColumnName("dias_credito");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<long?>("IdListaPrecioAsignada")
                        .HasColumnType("bigint")
                        .HasColumnName("id_lista_precio_asignada");

                    b.Property<long?>("IdTipoCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_cliente");

                    b.Property<long>("IdTipoDocumento")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_documento");

                    b.Property<decimal?>("LimiteCredito")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("limite_credito");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre_comercial");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_documento");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.Property<string>("UsuarioActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_modificacion");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_creacion");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.ToTable("clientes", "clientes");
                });

            modelBuilder.Entity("Ventas.API.Domain.Entidades.ContactoCliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_contacto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean")
                        .HasColumnName("activado");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cargo");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("es_principal");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.Property<string>("UsuarioActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_modificacion");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_creacion");

                    b.HasKey("Id")
                        .HasName("pk_contactos_cliente");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("ix_contactos_cliente_id_cliente");

                    b.ToTable("contactos_cliente", "clientes");
                });

            modelBuilder.Entity("Ventas.API.Domain.Entidades.Cotizacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_cotizacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean")
                        .HasColumnName("activado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente");

                    b.Property<long>("IdEstado")
                        .HasColumnType("bigint")
                        .HasColumnName("id_estado");

                    b.Property<long>("IdUsuarioVendedor")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario_vendedor");

                    b.Property<decimal>("Impuesto")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("impuesto");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("moneda");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint")
                        .HasColumnName("numero");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("serie");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TipoCambio")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("tipo_cambio");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total");

                    b.Property<string>("UsuarioActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_modificacion");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_creacion");

                    b.HasKey("Id")
                        .HasName("pk_cotizaciones");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("ix_cotizaciones_id_cliente");

                    b.ToTable("cotizaciones", "ventas");
                });

            modelBuilder.Entity("Ventas.API.Domain.Entidades.DetalleCotizacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_detalle_cot");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean")
                        .HasColumnName("activado");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("cantidad");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<long>("IdCotizacion")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cotizacion");

                    b.Property<long>("IdProducto")
                        .HasColumnType("bigint")
                        .HasColumnName("id_producto");

                    b.Property<long?>("IdVariante")
                        .HasColumnType("bigint")
                        .HasColumnName("id_variante");

                    b.Property<decimal?>("MontoDescuento")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("monto_descuento");

                    b.Property<decimal?>("PorcentajeDescuento")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("porcentaje_descuento");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<string>("UsuarioActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_modificacion");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_creacion");

                    b.HasKey("Id")
                        .HasName("pk_detalle_cotizacion");

                    b.HasIndex("IdCotizacion")
                        .HasDatabaseName("ix_detalle_cotizacion_id_cotizacion");

                    b.ToTable("detalle_cotizacion", "ventas");
                });

            modelBuilder.Entity("Ventas.API.Domain.Entidades.DetalleVenta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_detalle_venta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean")
                        .HasColumnName("activado");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("cantidad");

                    b.Property<string>("DescripcionProducto")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion_producto");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<long>("IdProducto")
                        .HasColumnType("bigint")
                        .HasColumnName("id_producto");

                    b.Property<long?>("IdVariante")
                        .HasColumnType("bigint")
                        .HasColumnName("id_variante");

                    b.Property<long>("IdVenta")
                        .HasColumnType("bigint")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("ImpuestoItem")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("impuesto_item");

                    b.Property<decimal>("PorcentajeImpuesto")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("porcentaje_impuesto");

                    b.Property<decimal?>("PrecioListaOriginal")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_lista_original");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("TotalItem")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_item");

                    b.Property<string>("UsuarioActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_modificacion");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_creacion");

                    b.HasKey("Id")
                        .HasName("pk_detalle_venta");

                    b.HasIndex("IdVenta")
                        .HasDatabaseName("ix_detalle_venta_id_venta");

                    b.ToTable("detalle_venta", "ventas");
                });

            modelBuilder.Entity("Ventas.API.Domain.Entidades.MetodoPago", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_metodo_pago");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean")
                        .HasColumnName("activado");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<bool>("RequiereReferencia")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_referencia");

                    b.Property<string>("UsuarioActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_modificacion");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_creacion");

                    b.HasKey("Id")
                        .HasName("pk_metodos_pago");

                    b.ToTable("metodos_pago", "ventas");
                });

            modelBuilder.Entity("Ventas.API.Domain.Entidades.MovimientoCaja", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_movimiento_caja");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean")
                        .HasColumnName("activado");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("concepto");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_movimiento");

                    b.Property<long>("IdCaja")
                        .HasColumnType("bigint")
                        .HasColumnName("id_caja");

                    b.Property<long?>("IdPagoRelacionado")
                        .HasColumnType("bigint")
                        .HasColumnName("id_pago_relacionado");

                    b.Property<long>("IdTipoMovimiento")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_movimiento");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("monto");

                    b.Property<string>("UsuarioActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_modificacion");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_creacion");

                    b.Property<string>("UsuarioResponsable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario_responsable");

                    b.HasKey("Id")
                        .HasName("pk_movimientos_caja");

                    b.HasIndex("IdCaja")
                        .HasDatabaseName("ix_movimientos_caja_id_caja");

                    b.HasIndex("IdPagoRelacionado")
                        .HasDatabaseName("ix_movimientos_caja_id_pago_relacionado");

                    b.ToTable("movimientos_caja", "ventas");
                });

            modelBuilder.Entity("Ventas.API.Domain.Entidades.Pago", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_pago");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean")
                        .HasColumnName("activado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<long>("IdMetodoPago")
                        .HasColumnType("bigint")
                        .HasColumnName("id_metodo_pago");

                    b.Property<long>("IdVenta")
                        .HasColumnType("bigint")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("MontoPago")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("monto_pago");

                    b.Property<string>("ReferenciaPago")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("referencia_pago");

                    b.Property<string>("UsuarioActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_modificacion");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_creacion");

                    b.HasKey("Id")
                        .HasName("pk_pagos");

                    b.HasIndex("IdMetodoPago")
                        .HasDatabaseName("ix_pagos_id_metodo_pago");

                    b.HasIndex("IdVenta")
                        .HasDatabaseName("ix_pagos_id_venta");

                    b.ToTable("pagos", "ventas");
                });

            modelBuilder.Entity("Ventas.API.Domain.Entidades.Referencias.CatalogoReferencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_tablas_generales_detalle");

                    b.ToTable("tablas_generales_detalle", "configuracion");
                });

            modelBuilder.Entity("Ventas.API.Domain.Entidades.Venta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_venta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean")
                        .HasColumnName("activado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<DateTime?>("FechaVencimientoPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vencimiento_pago");

                    b.Property<long>("IdAlmacen")
                        .HasColumnType("bigint")
                        .HasColumnName("id_almacen");

                    b.Property<long?>("IdCaja")
                        .HasColumnType("bigint")
                        .HasColumnName("id_caja");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente");

                    b.Property<long?>("IdCotizacionOrigen")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cotizacion_origen");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    b.Property<long>("IdEstado")
                        .HasColumnType("bigint")
                        .HasColumnName("id_estado");

                    b.Property<long>("IdEstadoPago")
                        .HasColumnType("bigint")
                        .HasColumnName("id_estado_pago");

                    b.Property<long>("IdTipoComprobante")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_comprobante");

                    b.Property<long>("IdUsuarioVendedor")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario_vendedor");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("moneda");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint")
                        .HasColumnName("numero");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("saldo_pendiente");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("serie");

                    b.Property<decimal>("SubtotalExonerado")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("subtotal_exonerado");

                    b.Property<decimal>("SubtotalGravado")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("subtotal_gravado");

                    b.Property<decimal>("SubtotalInafecto")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("subtotal_inafecto");

                    b.Property<decimal>("TipoCambio")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("tipo_cambio");

                    b.Property<decimal>("TotalDescuentoGlobal")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_descuento_global");

                    b.Property<decimal>("TotalImpuesto")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_impuesto");

                    b.Property<decimal>("TotalVenta")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_venta");

                    b.Property<string>("UsuarioActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_modificacion");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_creacion");

                    b.HasKey("Id")
                        .HasName("pk_ventas");

                    b.HasIndex("IdCaja")
                        .HasDatabaseName("ix_ventas_id_caja");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("ix_ventas_id_cliente");

                    b.ToTable("ventas", "ventas");
                });

            modelBuilder.Entity("Ventas.API.Domain.Entidades.ContactoCliente", b =>
                {
                    b.HasOne("Ventas.API.Domain.Entidades.Cliente", "Cliente")
                        .WithMany("Contactos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contactos_cliente_clientes_id_cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Ventas.API.Domain.Entidades.Cotizacion", b =>
                {
                    b.HasOne("Ventas.API.Domain.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cotizaciones_clientes_id_cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Ventas.API.Domain.Entidades.DetalleCotizacion", b =>
                {
                    b.HasOne("Ventas.API.Domain.Entidades.Cotizacion", "Cotizacion")
                        .WithMany("Detalles")
                        .HasForeignKey("IdCotizacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_cotizacion_cotizaciones_id_cotizacion");

                    b.Navigation("Cotizacion");
                });

            modelBuilder.Entity("Ventas.API.Domain.Entidades.DetalleVenta", b =>
                {
                    b.HasOne("Ventas.API.Domain.Entidades.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_venta_ventas_id_venta");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Ventas.API.Domain.Entidades.MovimientoCaja", b =>
                {
                    b.HasOne("Ventas.API.Domain.Entidades.Caja", "Caja")
                        .WithMany()
                        .HasForeignKey("IdCaja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_caja_cajas_id_caja");

                    b.HasOne("Ventas.API.Domain.Entidades.Pago", "PagoRelacionado")
                        .WithMany()
                        .HasForeignKey("IdPagoRelacionado")
                        .HasConstraintName("fk_movimientos_caja_pagos_id_pago_relacionado");

                    b.Navigation("Caja");

                    b.Navigation("PagoRelacionado");
                });

            modelBuilder.Entity("Ventas.API.Domain.Entidades.Pago", b =>
                {
                    b.HasOne("Ventas.API.Domain.Entidades.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("IdMetodoPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pagos_metodos_pago_id_metodo_pago");

                    b.HasOne("Ventas.API.Domain.Entidades.Venta", "Venta")
                        .WithMany("Pagos")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pagos_ventas_id_venta");

                    b.Navigation("MetodoPago");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Ventas.API.Domain.Entidades.Venta", b =>
                {
                    b.HasOne("Ventas.API.Domain.Entidades.Caja", "Caja")
                        .WithMany()
                        .HasForeignKey("IdCaja")
                        .HasConstraintName("fk_ventas_cajas_id_caja");

                    b.HasOne("Ventas.API.Domain.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ventas_clientes_id_cliente");

                    b.Navigation("Caja");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Ventas.API.Domain.Entidades.Cliente", b =>
                {
                    b.Navigation("Contactos");
                });

            modelBuilder.Entity("Ventas.API.Domain.Entidades.Cotizacion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Ventas.API.Domain.Entidades.Venta", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
