-- Bootstrap COMPLETO para tablas de configuración SUNAT y Notas Comerciales
CREATE SCHEMA IF NOT EXISTS configuracion;
CREATE SCHEMA IF NOT EXISTS ventas;
CREATE SCHEMA IF NOT EXISTS compras;

CREATE TABLE IF NOT EXISTS configuracion.tipo_documento (
    id_regla BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo CHARACTER VARYING(10) NOT NULL UNIQUE,
    nombre CHARACTER VARYING(100) NOT NULL,
    longitud INTEGER NOT NULL DEFAULT 0,
    longitud_maxima INTEGER,
    es_numerico BOOLEAN NOT NULL DEFAULT true,
    estado BOOLEAN NOT NULL DEFAULT true,
    activado BOOLEAN NOT NULL DEFAULT true,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    usuario_creacion CHARACTER VARYING(50) DEFAULT 'SYSTEM'
);

CREATE TABLE IF NOT EXISTS configuracion.tipo_comprobante (
    id_tipo_comprobante BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo CHARACTER VARYING(10) NOT NULL UNIQUE,
    nombre CHARACTER VARYING(100) NOT NULL,
    mueve_stock BOOLEAN NOT NULL DEFAULT false,
    tipo_movimiento_stock VARCHAR(20) NOT NULL DEFAULT 'NEUTRO',
    es_venta BOOLEAN NOT NULL DEFAULT false,
    es_compra BOOLEAN NOT NULL DEFAULT false,
    es_orden_compra BOOLEAN NOT NULL DEFAULT false,
    activado BOOLEAN NOT NULL DEFAULT true,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    usuario_creacion CHARACTER VARYING(50) DEFAULT 'SYSTEM'
);

CREATE TABLE IF NOT EXISTS configuracion.series_comprobantes (
    id_serie BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serie CHARACTER VARYING(10) NOT NULL,
    correlativo_actual BIGINT NOT NULL DEFAULT 0,
    id_tipo_comprobante BIGINT,
    id_almacen BIGINT,
    activado BOOLEAN NOT NULL DEFAULT true,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    usuario_creacion CHARACTER VARYING(50) DEFAULT 'SYSTEM'
);

CREATE TABLE IF NOT EXISTS configuracion.tipo_operacion_sunat (
    id_tipo_operacion SERIAL PRIMARY KEY,
    codigo CHARACTER VARYING(4) UNIQUE NOT NULL,
    nombre VARCHAR(200) NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    activado BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_creacion VARCHAR(100) DEFAULT 'SYSTEM'
);

CREATE TABLE IF NOT EXISTS configuracion.matriz_regla_sunat (
    id_regla SERIAL PRIMARY KEY,
    id_tipo_operacion INTEGER,
    id_tipo_comprobante INTEGER,
    nivel_obligatoriedad INTEGER DEFAULT 0,
    activo BOOLEAN DEFAULT TRUE,
    activado BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_creacion VARCHAR(100) DEFAULT 'SYSTEM'
);

CREATE TABLE IF NOT EXISTS configuracion.regla_documento_comprobante (
    id_relacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_documento character varying(10) NOT NULL,
    id_tipo_comprobante bigint NOT NULL,
    activado boolean NOT NULL DEFAULT true,
    fecha_creacion timestamp with time zone NOT NULL DEFAULT now(),
    usuario_creacion character varying(50) NOT NULL DEFAULT 'SYSTEM'
);

CREATE TABLE IF NOT EXISTS ventas.notas (
    id_nota BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta_referencia BIGINT,
    id_tipo_nota BIGINT,
    id_tipo_comprobante BIGINT,
    serie CHARACTER VARYING(4),
    numero BIGINT,
    fecha_emision TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    motivo_sustento TEXT,
    total_nota DECIMAL(12,2),
    activado BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS compras.notas (
    id_nota BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_compra_referencia BIGINT,
    id_tipo_comprobante BIGINT,
    serie_comprobante CHARACTER VARYING(10),
    numero_comprobante CHARACTER VARYING(20),
    fecha_emision TIMESTAMP WITH TIME ZONE,
    motivo_sustento TEXT,
    total DECIMAL(12,2),
    activado BOOLEAN DEFAULT TRUE
);

-- ------------------------------------------------------------------------------
-- RESTRICCIONES DE INTEGRIDAD (FKs)
-- ------------------------------------------------------------------------------

DO $$ 
BEGIN 
    -- series_comprobantes -> tipo_comprobante
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_series_tipo_comp') THEN
        ALTER TABLE configuracion.series_comprobantes 
        ADD CONSTRAINT fk_series_tipo_comp FOREIGN KEY (id_tipo_comprobante) 
        REFERENCES configuracion.tipo_comprobante(id_tipo_comprobante);
    END IF;

    -- matriz_regla_sunat -> tipo_comprobante
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_matriz_tipo_comp') THEN
        ALTER TABLE configuracion.matriz_regla_sunat 
        ADD CONSTRAINT fk_matriz_tipo_comp FOREIGN KEY (id_tipo_comprobante) 
        REFERENCES configuracion.tipo_comprobante(id_tipo_comprobante);
    END IF;

    -- matriz_regla_sunat -> tipo_operacion_sunat
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_matriz_tipo_oper') THEN
        ALTER TABLE configuracion.matriz_regla_sunat 
        ADD CONSTRAINT fk_matriz_tipo_oper FOREIGN KEY (id_tipo_operacion) 
        REFERENCES configuracion.tipo_operacion_sunat(id_tipo_operacion);
    END IF;

    -- regla_documento_comprobante -> tipo_comprobante
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_regla_doc_tipo_comp') THEN
        ALTER TABLE configuracion.regla_documento_comprobante 
        ADD CONSTRAINT fk_regla_doc_tipo_comp FOREIGN KEY (id_tipo_comprobante) 
        REFERENCES configuracion.tipo_comprobante(id_tipo_comprobante);
    END IF;
END $$;
