/*
==============================================================================
SCRIPT: MEJORAS SUNAT Y VISTAS SQL (15_mejoras_sunat_vistas.sql)
==============================================================================
Este script realiza:
1. Creación de Catálogos SUNAT (Afectación IGV, Motivos NC/ND).
2. Adaptación de tipo_documento para Catálogo 52 (Documento Relacionado).
3. Corrección de esquemas en ventas y compras (campos faltantes para FE).
4. Creación de vistas optimizadas para el frontend en el esquema 'vistas'.
==============================================================================
*/

-- ------------------------------------------------------------------------------
-- 1. CATÁLOGO 17: TIPO DE AFECTACIÓN AL IGV
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS configuracion.tipo_afectacion_igv (
    id_afectacion     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo            VARCHAR(2) NOT NULL UNIQUE,
    nombre            VARCHAR(100) NOT NULL,
    afecta_igv        BOOLEAN NOT NULL,
    es_exportacion    BOOLEAN NOT NULL DEFAULT false,
    activo            BOOLEAN NOT NULL DEFAULT true,
    activado          BOOLEAN NOT NULL DEFAULT true,
    fecha_creacion    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    usuario_creacion  VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    fecha_modificacion    TIMESTAMPTZ,
    usuario_modificacion  VARCHAR(50)
);

INSERT INTO configuracion.tipo_afectacion_igv (codigo, nombre, afecta_igv, es_exportacion)
VALUES 
('10', 'GRAVADO - OPERACION ONEROSA', true, false),
('11', 'GRAVADO - RETIRO POR PREMIO', true, false),
('12', 'GRAVADO - RETIRO POR DONACION', true, false),
('13', 'GRAVADO - RETIRO', true, false),
('14', 'GRAVADO - RETIRO POR PUBLICIDAD', true, false),
('15', 'GRAVADO - BONIFICACIONES', true, false),
('16', 'GRAVADO - RETIRO POR ENTREGA A TRABAJADORES', true, false),
('17', 'GRAVADO - IVAP', true, false),
('20', 'EXONERADO - OPERACION ONEROSA', false, false),
('21', 'EXONERADO - TRANSFERENCIA GRATUITA', false, false),
('30', 'INAFECTO - OPERACION ONEROSA', false, false),
('31', 'INAFECTO - RETIRO POR BONIFICACION', false, false),
('32', 'INAFECTO - RETIRO', false, false),
('33', 'INAFECTO - RETIRO POR MUESTRAS MEDICAS', false, false),
('34', 'INAFECTO - TRANSFERENCIA GRATUITA', false, false),
('35', 'INAFECTO - RETIRO POR PUBLICIDAD', false, false),
('36', 'INAFECTO - BONIFICACIONES', false, false),
('37', 'INAFECTO - RETIRO POR ENTREGA A TRABAJADORES', false, false),
('40', 'EXPORTACION DE BIENES O SERVICIOS', false, true)
ON CONFLICT (codigo) DO NOTHING;

-- ------------------------------------------------------------------------------
-- 2. ADAPTACIÓN TIPO_DOCUMENTO (CATÁLOGOS 06 Y 52)
-- ------------------------------------------------------------------------------
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='configuracion' AND table_name='tipo_documento' AND column_name='es_documento_relacionado') THEN
        ALTER TABLE configuracion.tipo_documento ADD COLUMN es_documento_relacionado BOOLEAN NOT NULL DEFAULT false;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='configuracion' AND table_name='tipo_documento' AND column_name='es_documento_identidad') THEN
        ALTER TABLE configuracion.tipo_documento ADD COLUMN es_documento_identidad BOOLEAN NOT NULL DEFAULT true;
    END IF;
END $$;

-- Asegurar que los existentes son de identidad
UPDATE configuracion.tipo_documento SET es_documento_identidad = true, es_documento_relacionado = false 
WHERE codigo IN ('1', '6', '4', '7', '0');

-- ------------------------------------------------------------------------------
-- 3. CATÁLOGOS 09 Y 10: MOTIVOS DE NC Y ND
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS configuracion.motivo_nota_credito (
    id_motivo         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo            VARCHAR(2) NOT NULL UNIQUE,
    nombre            VARCHAR(200) NOT NULL,
    devuelve_stock    BOOLEAN NOT NULL DEFAULT false,
    activo            BOOLEAN NOT NULL DEFAULT true,
    activado          BOOLEAN NOT NULL DEFAULT true,
    fecha_creacion    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    usuario_creacion  VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    fecha_modificacion    TIMESTAMPTZ,
    usuario_modificacion  VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS configuracion.motivo_nota_debito (
    id_motivo         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo            VARCHAR(2) NOT NULL UNIQUE,
    nombre            VARCHAR(200) NOT NULL,
    activo            BOOLEAN NOT NULL DEFAULT true,
    activado          BOOLEAN NOT NULL DEFAULT true,
    fecha_creacion    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    usuario_creacion  VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    fecha_modificacion    TIMESTAMPTZ,
    usuario_modificacion  VARCHAR(50)
);

INSERT INTO configuracion.motivo_nota_credito (codigo, nombre, devuelve_stock)
VALUES 
('01', 'ANULACION DE LA OPERACION', true),
('02', 'ANULACION POR ERROR EN EL RUC', false),
('03', 'CORRECCION POR ERROR EN LA DESCRIPCION', false),
('04', 'DESCUENTO GLOBAL', false),
('05', 'DESCUENTO POR ITEM', false),
('06', 'DEVOLUCION TOTAL', true),
('07', 'DEVOLUCION POR ITEM', true),
('08', 'BONIFICACION', false),
('09', 'DISMINUCION EN EL VALOR', false),
('10', 'OTROS CONCEPTOS', false),
('11', 'AJUSTES DE OPERACIONES DE EXPORTACION', false),
('12', 'AJUSTE AFECTO AL IVAP', false),
('13', 'CORRECCION DE LA DESCRIPCION', false)
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO configuracion.motivo_nota_debito (codigo, nombre)
VALUES 
('01', 'INTERES POR MORA'),
('02', 'AUMENTO EN EL VALOR'),
('03', 'PENALIDADES / OTROS CONCEPTOS'),
('10', 'OTROS CONCEPTOS'),
('11', 'AJUSTES DE OPERACIONES DE EXPORTACION'),
('12', 'AJUSTE AFECTO AL IVAP')
ON CONFLICT (codigo) DO NOTHING;

-- ------------------------------------------------------------------------------
-- 4. CORRECCIÓN VENTAS.DETALLE_VENTA
-- ------------------------------------------------------------------------------
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='ventas' AND table_name='detalle_venta' AND column_name='codigo_afectacion_igv') THEN
        ALTER TABLE ventas.detalle_venta ADD COLUMN codigo_afectacion_igv VARCHAR(2);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='ventas' AND table_name='detalle_venta' AND column_name='codigo_tributo') THEN
        ALTER TABLE ventas.detalle_venta ADD COLUMN codigo_tributo VARCHAR(4);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='ventas' AND table_name='detalle_venta' AND column_name='precio_unitario_base') THEN
        ALTER TABLE ventas.detalle_venta ADD COLUMN precio_unitario_base NUMERIC(12,4);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='ventas' AND table_name='detalle_venta' AND column_name='descuento_item') THEN
        ALTER TABLE ventas.detalle_venta ADD COLUMN descuento_item NUMERIC(12,4) DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='ventas' AND table_name='detalle_venta' AND column_name='valor_item') THEN
        ALTER TABLE ventas.detalle_venta ADD COLUMN valor_item NUMERIC(12,4);
    END IF;
END $$;

-- Agregar FK si no existe
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_detalle_venta_afectacion_igv') THEN
        ALTER TABLE ventas.detalle_venta 
        ADD CONSTRAINT fk_detalle_venta_afectacion_igv 
        FOREIGN KEY (codigo_afectacion_igv) 
        REFERENCES configuracion.tipo_afectacion_igv(codigo);
    END IF;
END $$;

-- ------------------------------------------------------------------------------
-- 5. CORRECCIÓN COMPRAS.DETALLE_COMPRA
-- ------------------------------------------------------------------------------
ALTER TABLE compras.detalle_compra ALTER COLUMN afectacion_igv TYPE VARCHAR(2);

DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='compras' AND table_name='detalle_compra' AND column_name='codigo_tributo') THEN
        ALTER TABLE compras.detalle_compra ADD COLUMN codigo_tributo VARCHAR(4);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='compras' AND table_name='detalle_compra' AND column_name='precio_unitario_base') THEN
        ALTER TABLE compras.detalle_compra ADD COLUMN precio_unitario_base NUMERIC(12,4);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='compras' AND table_name='detalle_compra' AND column_name='descuento_item') THEN
        ALTER TABLE compras.detalle_compra ADD COLUMN descuento_item NUMERIC(12,4) DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='compras' AND table_name='detalle_compra' AND column_name='valor_item') THEN
        ALTER TABLE compras.detalle_compra ADD COLUMN valor_item NUMERIC(12,4);
    END IF;
END $$;

-- Agregar FK si no existe
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_detalle_compra_afectacion_igv') THEN
        ALTER TABLE compras.detalle_compra
        ADD CONSTRAINT fk_detalle_compra_afectacion_igv
        FOREIGN KEY (afectacion_igv)
        REFERENCES configuracion.tipo_afectacion_igv(codigo);
    END IF;
END $$;

-- ------------------------------------------------------------------------------
-- 6. REF. NOTAS VENTAS Y COMPRAS
-- ------------------------------------------------------------------------------
DO $$ 
BEGIN 
    -- Ventas
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='ventas' AND table_name='notas' AND column_name='codigo_motivo_nc') THEN
        ALTER TABLE ventas.notas ADD COLUMN codigo_motivo_nc VARCHAR(2);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='ventas' AND table_name='notas' AND column_name='codigo_motivo_nd') THEN
        ALTER TABLE ventas.notas ADD COLUMN codigo_motivo_nd VARCHAR(2);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='ventas' AND table_name='notas' AND column_name='id_tipo_doc_ref') THEN
        ALTER TABLE ventas.notas ADD COLUMN id_tipo_doc_ref VARCHAR(4);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='ventas' AND table_name='notas' AND column_name='serie_ref') THEN
        ALTER TABLE ventas.notas ADD COLUMN serie_ref VARCHAR(10);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='ventas' AND table_name='notas' AND column_name='numero_ref') THEN
        ALTER TABLE ventas.notas ADD COLUMN numero_ref VARCHAR(20);
    END IF;

    -- Compras
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='compras' AND table_name='notas' AND column_name='codigo_motivo_nc') THEN
        ALTER TABLE compras.notas ADD COLUMN codigo_motivo_nc VARCHAR(2);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='compras' AND table_name='notas' AND column_name='codigo_motivo_nd') THEN
        ALTER TABLE compras.notas ADD COLUMN codigo_motivo_nd VARCHAR(2);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='compras' AND table_name='notas' AND column_name='id_tipo_doc_ref') THEN
        ALTER TABLE compras.notas ADD COLUMN id_tipo_doc_ref VARCHAR(4);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='compras' AND table_name='notas' AND column_name='serie_ref') THEN
        ALTER TABLE compras.notas ADD COLUMN serie_ref VARCHAR(10);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='compras' AND table_name='notas' AND column_name='numero_ref') THEN
        ALTER TABLE compras.notas ADD COLUMN numero_ref VARCHAR(20);
    END IF;
END $$;

-- ------------------------------------------------------------------------------
-- 7. ESQUEMA VISTAS Y PROYECCIONES
-- ------------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS vistas;

-- VIEW 1: vw_lista_ventas
CREATE OR REPLACE VIEW vistas.vw_lista_ventas AS
SELECT 
    v.id_venta, 
    v.serie, 
    v.numero, 
    v.fecha_emision,
    tc.codigo AS codigo_tipo_comprobante, 
    tc.nombre AS nombre_tipo_comprobante,
    c.numero_documento AS numero_documento_cliente, 
    c.razon_social AS razon_social_cliente,
    v.subtotal_gravado + v.subtotal_exonerado + v.subtotal_inafecto AS subtotal,
    v.total_impuesto AS igv, 
    v.total_venta AS total, 
    v.moneda,
    eg.nombre AS estado_venta,
    v.usuario_creacion AS nombre_usuario_creacion,
    EXISTS(SELECT 1 FROM ventas.notas n JOIN configuracion.tipo_comprobante tcn ON n.id_tipo_comprobante = tcn.id_tipo_comprobante WHERE n.id_venta_referencia = v.id_venta AND tcn.codigo = '07') AS tiene_nota_credito,
    EXISTS(SELECT 1 FROM ventas.notas n JOIN configuracion.tipo_comprobante tcn ON n.id_tipo_comprobante = tcn.id_tipo_comprobante WHERE n.id_venta_referencia = v.id_venta AND tcn.codigo = '08') AS tiene_nota_debito
FROM ventas.ventas v
JOIN clientes.clientes c ON v.id_cliente = c.id_cliente
JOIN configuracion.tipo_comprobante tc ON v.id_tipo_comprobante = tc.id_tipo_comprobante
LEFT JOIN configuracion.tablas_generales_detalle eg ON v.id_estado = eg.id_detalle;

-- VIEW 2: vw_detalle_venta
CREATE OR REPLACE VIEW vistas.vw_detalle_venta AS
SELECT 
    d.id_detalle_venta, 
    d.id_venta,
    p.id_producto, 
    p.codigo_producto, 
    d.descripcion_producto,
    um.codigo_sunat AS codigo_unidad_medida, 
    um.simbolo AS simbolo_unidad,
    d.cantidad, 
    d.precio_unitario_base, 
    d.precio_unitario AS precio_unitario_con_igv,
    d.descuento_item, 
    d.valor_item,
    ta.codigo AS codigo_afectacion_igv, 
    ta.nombre AS nombre_afectacion_igv,
    d.codigo_tributo, 
    d.porcentaje_impuesto AS porcentaje_igv, 
    d.impuesto_item,
    d.total_item
FROM ventas.detalle_venta d
JOIN catalogo.productos p ON d.id_producto = p.id_producto
JOIN catalogo.unidades_medida um ON p.id_unidad = um.id_unidad
LEFT JOIN configuracion.tipo_afectacion_igv ta ON d.codigo_afectacion_igv = ta.codigo;

-- VIEW 3: vw_lista_compras
CREATE OR REPLACE VIEW vistas.vw_lista_compras AS
SELECT 
    c.id_compra, 
    c.serie_comprobante, 
    c.numero_comprobante, 
    c.fecha_emision,
    tc.nombre AS nombre_tipo_comprobante,
    p.numero_documento AS numero_documento_proveedor, 
    p.razon_social AS razon_social_proveedor,
    c.subtotal, 
    c.impuesto AS igv, 
    c.total, 
    c.moneda,
    a.nombre_almacen AS nombre_almacen_destino,
    (c.id_orden_compra_ref IS NOT NULL) AS tiene_orden_compra_vinculada
FROM compras.compras c
JOIN compras.proveedores p ON c.id_proveedor = p.id_proveedor
JOIN configuracion.tipo_comprobante tc ON c.id_tipo_comprobante = tc.id_tipo_comprobante
JOIN inventario.almacenes a ON c.id_almacen = a.id_almacen;

-- VIEW 4: vw_kardex_movimientos
CREATE OR REPLACE VIEW vistas.vw_kardex_movimientos AS
SELECT 
    m.id_movimiento, 
    m.fecha_creacion AS fecha_movimiento,
    p.codigo_producto, 
    p.nombre_producto AS descripcion_producto,
    a.nombre_almacen,
    tm.nombre AS tipo_operacion,
    m.referencia_modulo AS tipo_documento_origen, 
    m.id_referencia::text AS numero_documento,
    m.cantidad, 
    m.costo_unitario_movimiento AS costo_unitario, 
    m.cantidad * m.costo_unitario_movimiento AS costo_total,
    m.cantidad_nueva AS saldo_cantidad,
    m.observaciones
FROM inventario.movimientos_inventario m
JOIN inventario.stock s ON m.id_stock = s.id_stock
JOIN catalogo.productos p ON s.id_producto = p.id_producto
JOIN inventario.almacenes a ON s.id_almacen = a.id_almacen
LEFT JOIN configuracion.tablas_generales_detalle tm ON m.id_tipo_movimiento = tm.id_detalle;

-- VIEW 5: vw_stock_actual
CREATE OR REPLACE VIEW vistas.vw_stock_actual AS
SELECT 
    p.id_producto, 
    p.codigo_producto, 
    p.nombre_producto AS descripcion_producto,
    cat.nombre_categoria, 
    mar.nombre_marca,
    um.codigo_sunat AS codigo_unidad_medida, 
    um.simbolo AS simbolo_unidad,
    a.nombre_almacen, 
    st.cantidad_actual AS stock_actual, 
    st.ubicacion_fisica,
    (st.cantidad_actual < p.stock_minimo) AS alerta_stock_minimo
FROM inventario.stock st
JOIN catalogo.productos p ON st.id_producto = p.id_producto
JOIN catalogo.categorias cat ON p.id_categoria = cat.id_categoria
JOIN catalogo.marcas mar ON p.id_marca = mar.id_marca
JOIN catalogo.unidades_medida um ON p.id_unidad = um.id_unidad
JOIN inventario.almacenes a ON st.id_almacen = a.id_almacen;
-- VIEW 6: vw_caja_movimientos
CREATE OR REPLACE VIEW vistas.vw_caja_movimientos AS
SELECT 
    m.id_movimiento_caja, 
    m.fecha_movimiento,
    c.nombre_caja, 
    tm.nombre AS tipo_movimiento,
    m.concepto, 
    m.monto, 
    'PEN' AS moneda, -- Por defecto según script
    NULL AS referencia_comprobante,
    m.usuario_responsable AS nombre_usuario
FROM ventas.movimientos_caja m
JOIN ventas.cajas c ON m.id_caja = c.id_caja
LEFT JOIN configuracion.tablas_generales_detalle tm ON m.id_tipo_movimiento = tm.id_detalle;

-- VIEW 7: vw_notas_credito_debito
CREATE OR REPLACE VIEW vistas.vw_notas_credito_debito AS
SELECT 
    n.id_nota, 
    CASE WHEN tc.codigo = '07' THEN 'CREDITO' ELSE 'DEBITO' END AS tipo_nota, 
    'VENTA' AS origen,
    n.serie, 
    n.numero, 
    n.fecha_emision,
    tc.nombre AS nombre_tipo_comprobante,
    n.serie_ref || '-' || n.numero_ref AS comprobante_referencia,
    c.razon_social AS razon_social_cliente_o_proveedor,
    COALESCE(mnc.codigo, mnd.codigo) AS codigo_motivo, 
    COALESCE(mnc.nombre, mnd.nombre) AS descripcion_motivo,
    COALESCE(mnc.devuelve_stock, false) AS devuelve_stock,
    n.total_nota AS monto_total,
    'ACTIVO' AS estado
FROM ventas.notas n
JOIN configuracion.tipo_comprobante tc ON n.id_tipo_comprobante = tc.id_tipo_comprobante
JOIN ventas.ventas v ON n.id_venta_referencia = v.id_venta
JOIN clientes.clientes c ON v.id_cliente = c.id_cliente
LEFT JOIN configuracion.motivo_nota_credito mnc ON n.codigo_motivo_nc = mnc.codigo
LEFT JOIN configuracion.motivo_nota_debito mnd ON n.codigo_motivo_nd = mnd.codigo

UNION ALL

SELECT 
    n.id_nota, 
    CASE WHEN tc.codigo = '07' THEN 'CREDITO' ELSE 'DEBITO' END AS tipo_nota, 
    'COMPRA' AS origen,
    n.serie_comprobante AS serie, 
    CAST(n.numero_comprobante AS BIGINT) AS numero, 
    n.fecha_emision,
    tc.nombre AS nombre_tipo_comprobante,
    n.serie_ref || '-' || n.numero_ref AS comprobante_referencia,
    p.razon_social AS razon_social_cliente_o_proveedor,
    COALESCE(mnc.codigo, mnd.codigo) AS codigo_motivo, 
    COALESCE(mnc.nombre, mnd.nombre) AS descripcion_motivo,
    COALESCE(mnc.devuelve_stock, false) AS devuelve_stock,
    n.total AS monto_total,
    'ACTIVO' AS estado
FROM compras.notas n
JOIN configuracion.tipo_comprobante tc ON n.id_tipo_comprobante = tc.id_tipo_comprobante
JOIN compras.compras c ON n.id_compra_referencia = c.id_compra
JOIN compras.proveedores p ON c.id_proveedor = p.id_proveedor
LEFT JOIN configuracion.motivo_nota_credito mnc ON n.codigo_motivo_nc = mnc.codigo
LEFT JOIN configuracion.motivo_nota_debito mnd ON n.codigo_motivo_nd = mnd.codigo;
