CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE categorias (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(100) NOT NULL,
    "Descripcion" text,
    "ImagenUrl" text,
    "IdCategoriaPadre" integer,
    "Activado" boolean NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "UsuarioCreacion" text NOT NULL,
    "FechaActualizacion" timestamp with time zone,
    "UsuarioActualizacion" text,
    CONSTRAINT "PK_categorias" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_categorias_categorias_IdCategoriaPadre" FOREIGN KEY ("IdCategoriaPadre") REFERENCES categorias ("Id")
);

CREATE TABLE marcas (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(100) NOT NULL,
    "PaisOrigen" text,
    "Activado" boolean NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "UsuarioCreacion" text NOT NULL,
    "FechaActualizacion" timestamp with time zone,
    "UsuarioActualizacion" text,
    CONSTRAINT "PK_marcas" PRIMARY KEY ("Id")
);

CREATE TABLE unidades_medida (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CodigoSunat" text NOT NULL,
    "Nombre" character varying(50) NOT NULL,
    "Simbolo" character varying(10) NOT NULL,
    "Activado" boolean NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "UsuarioCreacion" text NOT NULL,
    "FechaActualizacion" timestamp with time zone,
    "UsuarioActualizacion" text,
    CONSTRAINT "PK_unidades_medida" PRIMARY KEY ("Id")
);

CREATE TABLE productos (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CodigoProducto" character varying(50) NOT NULL,
    "CodigoBarras" text,
    "Sku" character varying(100),
    "NombreProducto" character varying(255) NOT NULL,
    "Descripcion" text,
    "ImagenUrl" text,
    "IdCategoria" integer NOT NULL,
    "IdMarca" integer NOT NULL,
    "IdUnidadMedida" integer NOT NULL,
    "PrecioCompra" numeric(12,2) NOT NULL,
    "PrecioVentaPublico" numeric(12,2) NOT NULL,
    "PrecioVentaMayorista" numeric(12,2) NOT NULL,
    "PrecioVentaDistribuidor" numeric(12,2) NOT NULL,
    "TieneVariantes" boolean NOT NULL,
    "PermiteInventarioNegativo" boolean NOT NULL,
    "GravadoImpuesto" boolean NOT NULL,
    "PorcentajeImpuesto" numeric(5,2) NOT NULL,
    "TipoProducto" text NOT NULL,
    "StockMinimo" numeric(10,3) NOT NULL,
    "StockMaximo" numeric(10,3) NOT NULL,
    "Activado" boolean NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "UsuarioCreacion" text NOT NULL,
    "FechaActualizacion" timestamp with time zone,
    "UsuarioActualizacion" text,
    CONSTRAINT "PK_productos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_productos_categorias_IdCategoria" FOREIGN KEY ("IdCategoria") REFERENCES categorias ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_productos_marcas_IdMarca" FOREIGN KEY ("IdMarca") REFERENCES marcas ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_productos_unidades_medida_IdUnidadMedida" FOREIGN KEY ("IdUnidadMedida") REFERENCES unidades_medida ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_categorias_IdCategoriaPadre" ON categorias ("IdCategoriaPadre");

CREATE UNIQUE INDEX "IX_productos_CodigoProducto" ON productos ("CodigoProducto");

CREATE INDEX "IX_productos_IdCategoria" ON productos ("IdCategoria");

CREATE INDEX "IX_productos_IdMarca" ON productos ("IdMarca");

CREATE INDEX "IX_productos_IdUnidadMedida" ON productos ("IdUnidadMedida");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260127221140_Inicial', '8.0.8');

COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'catalogo') THEN
        CREATE SCHEMA catalogo;
    END IF;
END $EF$;

ALTER TABLE unidades_medida SET SCHEMA catalogo;

ALTER TABLE productos SET SCHEMA catalogo;

ALTER TABLE marcas SET SCHEMA catalogo;

ALTER TABLE categorias SET SCHEMA catalogo;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260127221706_AjusteEsquema', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE catalogo.categorias DROP CONSTRAINT "FK_categorias_categorias_IdCategoriaPadre";

ALTER TABLE catalogo.productos DROP CONSTRAINT "FK_productos_categorias_IdCategoria";

ALTER TABLE catalogo.productos DROP CONSTRAINT "FK_productos_marcas_IdMarca";

ALTER TABLE catalogo.productos DROP CONSTRAINT "FK_productos_unidades_medida_IdUnidadMedida";

ALTER TABLE catalogo.productos DROP COLUMN "ImagenUrl";

ALTER TABLE catalogo.productos DROP COLUMN "TipoProducto";

ALTER TABLE catalogo.unidades_medida RENAME COLUMN "Simbolo" TO simbolo;

ALTER TABLE catalogo.unidades_medida RENAME COLUMN "Activado" TO activado;

ALTER TABLE catalogo.unidades_medida RENAME COLUMN "UsuarioCreacion" TO usuario_creacion;

ALTER TABLE catalogo.unidades_medida RENAME COLUMN "UsuarioActualizacion" TO usuario_modificacion;

ALTER TABLE catalogo.unidades_medida RENAME COLUMN "FechaCreacion" TO fecha_creacion;

ALTER TABLE catalogo.unidades_medida RENAME COLUMN "FechaActualizacion" TO fecha_modificacion;

ALTER TABLE catalogo.unidades_medida RENAME COLUMN "CodigoSunat" TO codigo_sunat;

ALTER TABLE catalogo.unidades_medida RENAME COLUMN "Id" TO id_unidad;

ALTER TABLE catalogo.unidades_medida RENAME COLUMN "Nombre" TO nombre_unidad;

ALTER TABLE catalogo.productos RENAME COLUMN "Sku" TO sku;

ALTER TABLE catalogo.productos RENAME COLUMN "Descripcion" TO descripcion;

ALTER TABLE catalogo.productos RENAME COLUMN "Activado" TO activado;

ALTER TABLE catalogo.productos RENAME COLUMN "UsuarioCreacion" TO usuario_creacion;

ALTER TABLE catalogo.productos RENAME COLUMN "UsuarioActualizacion" TO usuario_modificacion;

ALTER TABLE catalogo.productos RENAME COLUMN "TieneVariantes" TO tiene_variantes;

ALTER TABLE catalogo.productos RENAME COLUMN "StockMinimo" TO stock_minimo;

ALTER TABLE catalogo.productos RENAME COLUMN "StockMaximo" TO stock_maximo;

ALTER TABLE catalogo.productos RENAME COLUMN "PrecioVentaPublico" TO precio_venta_publico;

ALTER TABLE catalogo.productos RENAME COLUMN "PrecioVentaMayorista" TO precio_venta_mayorista;

ALTER TABLE catalogo.productos RENAME COLUMN "PrecioVentaDistribuidor" TO precio_venta_distribuidor;

ALTER TABLE catalogo.productos RENAME COLUMN "PrecioCompra" TO precio_compra;

ALTER TABLE catalogo.productos RENAME COLUMN "PorcentajeImpuesto" TO porcentaje_impuesto;

ALTER TABLE catalogo.productos RENAME COLUMN "PermiteInventarioNegativo" TO permite_inventario_negativo;

ALTER TABLE catalogo.productos RENAME COLUMN "NombreProducto" TO nombre_producto;

ALTER TABLE catalogo.productos RENAME COLUMN "IdUnidadMedida" TO id_unidad;

ALTER TABLE catalogo.productos RENAME COLUMN "IdMarca" TO id_marca;

ALTER TABLE catalogo.productos RENAME COLUMN "IdCategoria" TO id_categoria;

ALTER TABLE catalogo.productos RENAME COLUMN "GravadoImpuesto" TO gravado_impuesto;

ALTER TABLE catalogo.productos RENAME COLUMN "FechaCreacion" TO fecha_creacion;

ALTER TABLE catalogo.productos RENAME COLUMN "FechaActualizacion" TO fecha_modificacion;

ALTER TABLE catalogo.productos RENAME COLUMN "CodigoProducto" TO codigo_producto;

ALTER TABLE catalogo.productos RENAME COLUMN "CodigoBarras" TO codigo_barras;

ALTER TABLE catalogo.productos RENAME COLUMN "Id" TO id_producto;

ALTER INDEX catalogo."IX_productos_IdUnidadMedida" RENAME TO "IX_productos_id_unidad";

ALTER INDEX catalogo."IX_productos_IdMarca" RENAME TO "IX_productos_id_marca";

ALTER INDEX catalogo."IX_productos_IdCategoria" RENAME TO "IX_productos_id_categoria";

ALTER INDEX catalogo."IX_productos_CodigoProducto" RENAME TO "IX_productos_codigo_producto";

ALTER TABLE catalogo.marcas RENAME COLUMN "Activado" TO activado;

ALTER TABLE catalogo.marcas RENAME COLUMN "UsuarioCreacion" TO usuario_creacion;

ALTER TABLE catalogo.marcas RENAME COLUMN "UsuarioActualizacion" TO usuario_modificacion;

ALTER TABLE catalogo.marcas RENAME COLUMN "PaisOrigen" TO pais_origen;

ALTER TABLE catalogo.marcas RENAME COLUMN "FechaCreacion" TO fecha_creacion;

ALTER TABLE catalogo.marcas RENAME COLUMN "FechaActualizacion" TO fecha_modificacion;

ALTER TABLE catalogo.marcas RENAME COLUMN "Id" TO id_marca;

ALTER TABLE catalogo.marcas RENAME COLUMN "Nombre" TO nombre_marca;

ALTER TABLE catalogo.categorias RENAME COLUMN "Descripcion" TO descripcion;

ALTER TABLE catalogo.categorias RENAME COLUMN "Activado" TO activado;

ALTER TABLE catalogo.categorias RENAME COLUMN "UsuarioCreacion" TO usuario_creacion;

ALTER TABLE catalogo.categorias RENAME COLUMN "UsuarioActualizacion" TO usuario_modificacion;

ALTER TABLE catalogo.categorias RENAME COLUMN "ImagenUrl" TO imagen_url;

ALTER TABLE catalogo.categorias RENAME COLUMN "IdCategoriaPadre" TO id_categoria_padre;

ALTER TABLE catalogo.categorias RENAME COLUMN "FechaCreacion" TO fecha_creacion;

ALTER TABLE catalogo.categorias RENAME COLUMN "FechaActualizacion" TO fecha_modificacion;

ALTER TABLE catalogo.categorias RENAME COLUMN "Id" TO id_categoria;

ALTER TABLE catalogo.categorias RENAME COLUMN "Nombre" TO nombre_categoria;

ALTER INDEX catalogo."IX_categorias_IdCategoriaPadre" RENAME TO "IX_categorias_id_categoria_padre";

ALTER TABLE catalogo.unidades_medida ALTER COLUMN fecha_creacion TYPE timestamp without time zone;

ALTER TABLE catalogo.unidades_medida ALTER COLUMN fecha_modificacion TYPE timestamp without time zone;

ALTER TABLE catalogo.unidades_medida ALTER COLUMN codigo_sunat TYPE character varying(10);
ALTER TABLE catalogo.unidades_medida ALTER COLUMN codigo_sunat DROP NOT NULL;

ALTER TABLE catalogo.unidades_medida ALTER COLUMN id_unidad TYPE bigint;

ALTER TABLE catalogo.productos ALTER COLUMN stock_maximo DROP NOT NULL;

ALTER TABLE catalogo.productos ALTER COLUMN id_unidad TYPE bigint;

ALTER TABLE catalogo.productos ALTER COLUMN id_marca TYPE bigint;

ALTER TABLE catalogo.productos ALTER COLUMN id_categoria TYPE bigint;

ALTER TABLE catalogo.productos ALTER COLUMN fecha_creacion TYPE timestamp without time zone;

ALTER TABLE catalogo.productos ALTER COLUMN fecha_modificacion TYPE timestamp without time zone;

ALTER TABLE catalogo.productos ALTER COLUMN codigo_barras TYPE character varying(100);

ALTER TABLE catalogo.productos ALTER COLUMN id_producto TYPE bigint;

ALTER TABLE catalogo.productos ADD id_tipo_producto bigint NOT NULL DEFAULT 0;

ALTER TABLE catalogo.productos ADD imagen_principal_url character varying(500);

ALTER TABLE catalogo.marcas ALTER COLUMN pais_origen TYPE character varying(100);

ALTER TABLE catalogo.marcas ALTER COLUMN fecha_creacion TYPE timestamp without time zone;

ALTER TABLE catalogo.marcas ALTER COLUMN fecha_modificacion TYPE timestamp without time zone;

ALTER TABLE catalogo.marcas ALTER COLUMN id_marca TYPE bigint;

ALTER TABLE catalogo.categorias ALTER COLUMN descripcion TYPE character varying(255);

ALTER TABLE catalogo.categorias ALTER COLUMN imagen_url TYPE character varying(500);

ALTER TABLE catalogo.categorias ALTER COLUMN id_categoria_padre TYPE bigint;

ALTER TABLE catalogo.categorias ALTER COLUMN fecha_creacion TYPE timestamp without time zone;

ALTER TABLE catalogo.categorias ALTER COLUMN fecha_modificacion TYPE timestamp without time zone;

ALTER TABLE catalogo.categorias ALTER COLUMN id_categoria TYPE bigint;

CREATE TABLE catalogo.imagenes_producto (
    id_imagen bigint GENERATED BY DEFAULT AS IDENTITY,
    id_producto bigint NOT NULL,
    url_imagen character varying(500) NOT NULL,
    es_principal boolean NOT NULL,
    orden integer NOT NULL,
    "Activado" boolean NOT NULL,
    "FechaCreacion" timestamp without time zone NOT NULL,
    "UsuarioCreacion" text NOT NULL,
    "FechaActualizacion" timestamp without time zone,
    "UsuarioActualizacion" text,
    CONSTRAINT "PK_imagenes_producto" PRIMARY KEY (id_imagen),
    CONSTRAINT "FK_imagenes_producto_productos_id_producto" FOREIGN KEY (id_producto) REFERENCES catalogo.productos (id_producto) ON DELETE CASCADE
);

CREATE TABLE catalogo.variantes_producto (
    id_variante bigint GENERATED BY DEFAULT AS IDENTITY,
    id_producto bigint NOT NULL,
    sku_variante character varying(100) NOT NULL,
    codigo_barras_variante character varying(100),
    nombre_completo_variante character varying(255) NOT NULL,
    atributos_json jsonb,
    precio_adicional numeric(12,2) NOT NULL,
    "Activado" boolean NOT NULL,
    "FechaCreacion" timestamp without time zone NOT NULL,
    "UsuarioCreacion" text NOT NULL,
    "FechaActualizacion" timestamp without time zone,
    "UsuarioActualizacion" text,
    CONSTRAINT "PK_variantes_producto" PRIMARY KEY (id_variante),
    CONSTRAINT "FK_variantes_producto_productos_id_producto" FOREIGN KEY (id_producto) REFERENCES catalogo.productos (id_producto) ON DELETE CASCADE
);

CREATE INDEX "IX_imagenes_producto_id_producto" ON catalogo.imagenes_producto (id_producto);

CREATE INDEX "IX_variantes_producto_id_producto" ON catalogo.variantes_producto (id_producto);

ALTER TABLE catalogo.categorias ADD CONSTRAINT "FK_categorias_categorias_id_categoria_padre" FOREIGN KEY (id_categoria_padre) REFERENCES catalogo.categorias (id_categoria);

ALTER TABLE catalogo.productos ADD CONSTRAINT "FK_productos_categorias_id_categoria" FOREIGN KEY (id_categoria) REFERENCES catalogo.categorias (id_categoria) ON DELETE RESTRICT;

ALTER TABLE catalogo.productos ADD CONSTRAINT "FK_productos_marcas_id_marca" FOREIGN KEY (id_marca) REFERENCES catalogo.marcas (id_marca) ON DELETE RESTRICT;

ALTER TABLE catalogo.productos ADD CONSTRAINT "FK_productos_unidades_medida_id_unidad" FOREIGN KEY (id_unidad) REFERENCES catalogo.unidades_medida (id_unidad) ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260128013043_RefactorTipoProducto', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE catalogo.variantes_producto RENAME COLUMN "Activado" TO activado;

ALTER TABLE catalogo.variantes_producto RENAME COLUMN "UsuarioCreacion" TO usuario_creacion;

ALTER TABLE catalogo.variantes_producto RENAME COLUMN "UsuarioActualizacion" TO usuario_modificacion;

ALTER TABLE catalogo.variantes_producto RENAME COLUMN "FechaCreacion" TO fecha_creacion;

ALTER TABLE catalogo.variantes_producto RENAME COLUMN "FechaActualizacion" TO fecha_modificacion;

ALTER TABLE catalogo.imagenes_producto RENAME COLUMN "Activado" TO activado;

ALTER TABLE catalogo.imagenes_producto RENAME COLUMN "UsuarioCreacion" TO usuario_creacion;

ALTER TABLE catalogo.imagenes_producto RENAME COLUMN "UsuarioActualizacion" TO usuario_modificacion;

ALTER TABLE catalogo.imagenes_producto RENAME COLUMN "FechaCreacion" TO fecha_creacion;

ALTER TABLE catalogo.imagenes_producto RENAME COLUMN "FechaActualizacion" TO fecha_modificacion;

ALTER TABLE catalogo.variantes_producto ALTER COLUMN usuario_creacion TYPE character varying(50);

ALTER TABLE catalogo.variantes_producto ALTER COLUMN usuario_modificacion TYPE character varying(50);

ALTER TABLE catalogo.unidades_medida ALTER COLUMN usuario_modificacion TYPE character varying(50);

ALTER TABLE catalogo.unidades_medida ALTER COLUMN usuario_creacion TYPE character varying(50);

ALTER TABLE catalogo.productos ALTER COLUMN usuario_modificacion TYPE character varying(50);

ALTER TABLE catalogo.productos ALTER COLUMN usuario_creacion TYPE character varying(50);

ALTER TABLE catalogo.productos ALTER COLUMN id_tipo_producto DROP NOT NULL;

ALTER TABLE catalogo.productos ADD metodo_valuacion character varying(2) NOT NULL DEFAULT '';

ALTER TABLE catalogo.marcas ALTER COLUMN usuario_modificacion TYPE character varying(50);

ALTER TABLE catalogo.marcas ALTER COLUMN usuario_creacion TYPE character varying(50);

ALTER TABLE catalogo.imagenes_producto ALTER COLUMN usuario_creacion TYPE character varying(50);

ALTER TABLE catalogo.imagenes_producto ALTER COLUMN usuario_modificacion TYPE character varying(50);

ALTER TABLE catalogo.categorias ALTER COLUMN usuario_modificacion TYPE character varying(50);

ALTER TABLE catalogo.categorias ALTER COLUMN usuario_creacion TYPE character varying(50);

CREATE TABLE catalogo.listas_precios (
    id_lista_precio bigint GENERATED BY DEFAULT AS IDENTITY,
    nombre_lista character varying(50) NOT NULL,
    es_base boolean NOT NULL,
    porcentaje_ganancia_sugerido numeric(5,2),
    activado boolean NOT NULL,
    fecha_creacion timestamp without time zone NOT NULL,
    usuario_creacion character varying(50) NOT NULL,
    fecha_modificacion timestamp without time zone,
    usuario_modificacion character varying(50),
    CONSTRAINT "PK_listas_precios" PRIMARY KEY (id_lista_precio)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260222180939_AddMetodoValuacionToProducto', '8.0.8');

COMMIT;

