export const RUTAS_TITULOS: Record<string, string> = {
  '/dashboard':                    'Dashboard',
  '/catalogo/productos':           'Productos',
  '/catalogo/categorias':          'Categorías',
  '/catalogo/marcas':              'Marcas',
  '/catalogo/precios':             'Precios',
  '/catalogo/unidades-medida':     'Unidades de Medida',
  '/catalogo/listas-precios':      'Listas de Precios',
  '/ventas':                       'Ventas',
  '/ventas/lista':                 'Ventas',
  '/ventas/nueva':                 'Nueva Venta',
  '/ventas/pos':                   'POS',
  '/ventas/notas':                 'Notas SUNAT',
  '/ventas/cotizaciones':          'Cotizaciones',
  '/ventas/devoluciones':          'Devoluciones',
  '/comprobantes/facturas':        'Facturas',
  '/comprobantes/boletas':         'Boletas',
  '/comprobantes/notas-credito':   'Notas de Crédito',
  '/comprobantes/guias':           'Guías de Remisión',
  '/inventario/stock':             'Stock',
  '/inventario/movimientos':       'Movimientos',
  '/inventario/almacenes':         'Almacenes',
  '/inventario/kardex':            'Kardex',
  '/inventario/kardex/reporte':    'Kardex Reporte',
  '/inventario/kardex/periodos':   'Control Kardex',
  '/inventario/traslados':         'Traslados',
  '/clientes':                     'Clientes',
  '/clientes/grupos':              'Grupos',
  '/clientes/historial':           'Historial',
  '/proveedores':                  'Proveedores',
  '/proveedores/ordenes':          'Órdenes de Compra',
  '/proveedores/historial':        'Historial',
  '/configuracion/general':        'General',
  '/configuracion/empresa':        'Empresa',
  '/configuracion/usuarios':       'Usuarios',
  '/configuracion/roles':          'Roles',
  '/configuracion/sucursales':     'Sucursales',
  '/configuracion/impuestos':      'Impuestos',
  '/configuracion/metodos-pago':   'Métodos de Pago',
  '/configuracion/comprobantes':   'Comprobantes',
  '/configuracion/reglas-sunat':   'Reglas SUNAT',
  '/configuracion/operaciones-sunat': 'Operaciones SUNAT',
  '/configuracion/matriz-sunat':   'Matriz SUNAT',
  '/configuracion/tablas-generales': 'Tablas Generales',
  '/configuracion/ubigeos': 'Ubigeos',
  '/configuracion/sunat':          'SUNAT',
  '/seguridad/usuarios':           'Gestión de Usuarios',
  '/seguridad/roles':              'Roles y Permisos',
  '/seguridad/trabajadores':       'Directorio de Personal',
  '/configuracion/permisos':       'Permisos',
  '/compras/lista':                'Compras',
  '/compras/notas':                'Notas de Compra',
  '/perfil':                       'Mi Perfil',
  '/configuracion-usuario':        'Configuración de Usuario',
  '/ventas/turnos':                 'Historial de Turnos',
  '/ventas/cajas':                  'Gestión de Cajas',
}
