CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260129230510_Inicial', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE inventario.stock ADD costo_promedio numeric(12,4) NOT NULL DEFAULT 0.0;

ALTER TABLE inventario.stock ADD valor_total numeric(12,2) NOT NULL DEFAULT 0.0;

ALTER TABLE inventario.movimientos_inventario ADD costo_promedio_actual numeric(12,4) NOT NULL DEFAULT 0.0;

ALTER TABLE inventario.movimientos_inventario ADD saldo_cantidad numeric(10,3) NOT NULL DEFAULT 0.0;

ALTER TABLE inventario.movimientos_inventario ADD saldo_valorizado numeric(12,2) NOT NULL DEFAULT 0.0;

ALTER TABLE inventario.almacenes ADD id_sucursal bigint NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260216193227_AddIdSucursalToAlmacen', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE inventario.stock ALTER COLUMN fecha_modificacion TYPE timestamp without time zone;

ALTER TABLE inventario.stock ALTER COLUMN fecha_creacion TYPE timestamp without time zone;

ALTER TABLE inventario.movimientos_inventario ALTER COLUMN fecha_modificacion TYPE timestamp without time zone;

ALTER TABLE inventario.movimientos_inventario ALTER COLUMN fecha_creacion TYPE timestamp without time zone;

ALTER TABLE inventario.almacenes ALTER COLUMN fecha_modificacion TYPE timestamp without time zone;

ALTER TABLE inventario.almacenes ALTER COLUMN fecha_creacion TYPE timestamp without time zone;

CREATE TABLE inventario.inv_kardex_lote (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    producto_id bigint NOT NULL,
    almacen_id bigint NOT NULL,
    fecha_entrada date NOT NULL,
    hora_entrada time NOT NULL,
    movimiento_origen_id bigint NOT NULL,
    costo_unitario numeric(18,6) NOT NULL,
    cantidad_original numeric(18,6) NOT NULL,
    cantidad_disponible numeric(18,6) NOT NULL,
    estado character varying(1) NOT NULL,
    activado boolean NOT NULL,
    fecha_creacion timestamp without time zone NOT NULL,
    usuario_creacion character varying(50) NOT NULL,
    fecha_modificacion timestamp without time zone,
    usuario_modificacion character varying(50),
    CONSTRAINT pk_inv_kardex_lote PRIMARY KEY (id)
);

CREATE TABLE inventario.inv_kardex_movimiento (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    uuid character varying(36) NOT NULL,
    periodo character varying(7) NOT NULL,
    correlativo_kardex bigint NOT NULL,
    fecha_movimiento date NOT NULL,
    hora_movimiento time NOT NULL,
    fecha_hora_compuesta timestamp without time zone NOT NULL,
    modulo_origen character varying(30) NOT NULL,
    tipo_documento character varying(2) NOT NULL,
    serie_documento character varying(10) NOT NULL,
    numero_documento character varying(20) NOT NULL,
    anulado boolean NOT NULL,
    fecha_anulacion date,
    motivo_anulacion text,
    tipo_operacion character varying(1) NOT NULL,
    motivo_traslado_sunat character varying(2) NOT NULL,
    descripcion_movimiento character varying(255) NOT NULL,
    almacen_id bigint NOT NULL,
    almacen_origen_id bigint,
    almacen_destino_id bigint,
    producto_id bigint NOT NULL,
    unidad_medida_codigo character varying(10) NOT NULL,
    factor_conversion numeric(18,6) NOT NULL,
    entrada_cantidad numeric(18,6),
    entrada_costo_unitario numeric(18,6),
    entrada_costo_total numeric(18,6),
    salida_cantidad numeric(18,6),
    salida_costo_unitario numeric(18,6),
    salida_costo_total numeric(18,6),
    saldo_cantidad numeric(18,6) NOT NULL,
    saldo_costo_unitario numeric(18,6) NOT NULL,
    saldo_costo_total numeric(18,6) NOT NULL,
    referencia_id bigint,
    referencia_tipo character varying(50),
    lote_id bigint,
    proveedor_cliente_id bigint,
    observaciones text,
    usuario_registro_id bigint NOT NULL,
    usuario_anulacion_id bigint,
    recalculado_at timestamp without time zone,
    activado boolean NOT NULL,
    fecha_creacion timestamp without time zone NOT NULL,
    usuario_creacion character varying(50) NOT NULL,
    fecha_modificacion timestamp without time zone,
    usuario_modificacion character varying(50),
    CONSTRAINT pk_inv_kardex_movimiento PRIMARY KEY (id)
);

CREATE TABLE inventario.inv_kardex_periodo_control (
    periodo character varying(7) NOT NULL,
    estado character varying(1) NOT NULL,
    fecha_cierre date,
    usuario_cierre_id bigint,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone,
    CONSTRAINT pk_inv_kardex_periodo_control PRIMARY KEY (periodo)
);

CREATE TABLE inventario.inv_kardex_recalculo_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    almacen_id integer NOT NULL,
    producto_id integer NOT NULL,
    desde_fecha date NOT NULL,
    motivo character varying(30) NOT NULL,
    registros_afect integer NOT NULL,
    usuario_id integer NOT NULL,
    duracion_ms integer,
    created_at timestamp without time zone NOT NULL,
    CONSTRAINT pk_inv_kardex_recalculo_log PRIMARY KEY (id)
);

CREATE INDEX ix_inv_kardex_movimiento_fecha_movimiento_hora_movimiento ON inventario.inv_kardex_movimiento (fecha_movimiento, hora_movimiento);

CREATE INDEX ix_inv_kardex_movimiento_periodo_almacen_id_producto_id ON inventario.inv_kardex_movimiento (periodo, almacen_id, producto_id);

CREATE INDEX ix_inv_kardex_movimiento_referencia_id_referencia_tipo ON inventario.inv_kardex_movimiento (referencia_id, referencia_tipo);

CREATE INDEX ix_inv_kardex_movimiento_tipo_documento_serie_documento_numero ON inventario.inv_kardex_movimiento (tipo_documento, serie_documento, numero_documento);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260222181633_AddKardexEntities', '8.0.0');

COMMIT;

