import {
  ShoppingCart,
  LayoutDashboard,
  Package,
  ShoppingBag,
  Calculator,
  Settings,
  BarChart3,
  Receipt,
  FileText,
  Users,
  Box,
  FolderTree,
  ArrowLeftRight,
  Warehouse,
  FileInput,
  Building,
  ListTree,
  BookOpen,
  BookText,
  BookMarked,
  Scale,
  TrendingUp,
  DollarSign,
  Building2,
  UserCog,
  Shield,
  Wrench,
  CreditCard,
} from "lucide-react";

export const MENU_ITEMS = [
  {
    id: "dashboard",
    titulo: "Dashboard",
    icono: LayoutDashboard,
    ruta: "/dashboard",
    badge: null,
  },
  {
    id: "ventas",
    titulo: "Ventas",
    icono: ShoppingCart,
    badge: { texto: "3", variant: "default" },
    submenu: [
      {
        id: "pos",
        titulo: "Punto de Venta",
        icono: CreditCard,
        ruta: "/pos",
        atajoTeclado: "V",
      },
      {
        id: "ventas-lista",
        titulo: "Ventas",
        icono: Receipt,
        ruta: "/ventas",
      },
      {
        id: "cotizaciones",
        titulo: "Cotizaciones",
        icono: FileText,
        ruta: "/cotizaciones",
        badge: { texto: "3", variant: "secondary" },
      },
      {
        id: "clientes",
        titulo: "Clientes",
        icono: Users,
        ruta: "/clientes",
      },
    ],
  },
  {
    id: "inventario",
    titulo: "Inventario",
    icono: Package,
    submenu: [
      {
        id: "productos",
        titulo: "Productos",
        icono: Box,
        ruta: "/productos",
      },
      {
        id: "categorias",
        titulo: "Categorías",
        icono: FolderTree,
        ruta: "/categorias",
      },
      {
        id: "stock",
        titulo: "Stock",
        icono: BarChart3,
        ruta: "/stock",
        badge: { texto: "!", variant: "destructive" },
      },
      {
        id: "movimientos",
        titulo: "Movimientos",
        icono: ArrowLeftRight,
        ruta: "/movimientos",
      },
      {
        id: "almacenes",
        titulo: "Almacenes",
        icono: Warehouse,
        ruta: "/almacenes",
      },
    ],
  },
  {
    id: "compras",
    titulo: "Compras",
    icono: ShoppingBag,
    submenu: [
      {
        id: "ordenes-compra",
        titulo: "Órdenes de Compra",
        icono: FileInput,
        ruta: "/ordenes-compra",
      },
      {
        id: "compras-lista",
        titulo: "Compras",
        icono: Receipt,
        ruta: "/compras",
      },
      {
        id: "proveedores",
        titulo: "Proveedores",
        icono: Building,
        ruta: "/proveedores",
      },
      {
        id: "cuentas-pagar",
        titulo: "Cuentas por Pagar",
        icono: CreditCard,
        ruta: "/cuentas-pagar",
        badge: { texto: "5", variant: "destructive" },
      },
    ],
  },
  {
    id: "contabilidad",
    titulo: "Contabilidad",
    icono: Calculator,
    submenu: [
      {
        id: "plan-cuentas",
        titulo: "Plan de Cuentas",
        icono: ListTree,
        ruta: "/plan-cuentas",
      },
      {
        id: "asientos",
        titulo: "Asientos Contables",
        icono: BookOpen,
        ruta: "/asientos",
      },
      {
        id: "libro-diario",
        titulo: "Libro Diario",
        icono: BookText,
        ruta: "/libro-diario",
      },
      {
        id: "libro-mayor",
        titulo: "Libro Mayor",
        icono: BookMarked,
        ruta: "/libro-mayor",
      },
      {
        id: "balance-general",
        titulo: "Balance General",
        icono: Scale,
        ruta: "/balance-general",
      },
    ],
  },
  {
    id: "reportes",
    titulo: "Reportes",
    icono: BarChart3,
    submenu: [
      {
        id: "reportes-ventas",
        titulo: "Ventas",
        icono: TrendingUp,
        ruta: "/reportes/ventas",
      },
      {
        id: "reportes-inventario",
        titulo: "Inventario",
        icono: Package,
        ruta: "/reportes/inventario",
      },
      {
        id: "reportes-financieros",
        titulo: "Financieros",
        icono: DollarSign,
        ruta: "/reportes/financieros",
      },
      {
        id: "reportes-clientes",
        titulo: "Clientes",
        icono: Users,
        ruta: "/reportes/clientes",
      },
    ],
  },
  { separador: true, id: "separador-1" },
  {
    id: "configuracion",
    titulo: "Configuración",
    icono: Settings,
    submenu: [
      {
        id: "empresa",
        titulo: "Empresa",
        icono: Building2,
        ruta: "/configuracion/empresa",
      },
      {
        id: "usuarios",
        titulo: "Usuarios",
        icono: UserCog,
        ruta: "/configuracion/usuarios",
      },
      {
        id: "roles",
        titulo: "Roles y Permisos",
        icono: Shield,
        ruta: "/configuracion/roles",
      },
      {
        id: "general",
        titulo: "General",
        icono: Wrench,
        ruta: "/configuracion/general",
      },
    ],
  },
];
