// <auto-generated />
using System;
using Catalogo.Infrastructure.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalogo.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogoDbContext))]
    [Migration("20260128013043_RefactorTipoProducto")]
    partial class RefactorTipoProducto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalogo")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalogo.Domain.Entidades.Categoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean")
                        .HasColumnName("activado");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<long?>("IdCategoriaPadre")
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria_padre");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_categoria");

                    b.Property<string>("UsuarioActualizacion")
                        .HasColumnType("text")
                        .HasColumnName("usuario_modificacion");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_creacion");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoriaPadre");

                    b.ToTable("categorias", "catalogo");
                });

            modelBuilder.Entity("Catalogo.Domain.Entidades.ImagenProducto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_imagen");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("es_principal");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("IdProducto")
                        .HasColumnType("bigint")
                        .HasColumnName("id_producto");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_imagen");

                    b.Property<string>("UsuarioActualizacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdProducto");

                    b.ToTable("imagenes_producto", "catalogo");
                });

            modelBuilder.Entity("Catalogo.Domain.Entidades.Marca", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_marca");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean")
                        .HasColumnName("activado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("NombreMarca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_marca");

                    b.Property<string>("PaisOrigen")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pais_origen");

                    b.Property<string>("UsuarioActualizacion")
                        .HasColumnType("text")
                        .HasColumnName("usuario_modificacion");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_creacion");

                    b.HasKey("Id");

                    b.ToTable("marcas", "catalogo");
                });

            modelBuilder.Entity("Catalogo.Domain.Entidades.Producto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_producto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean")
                        .HasColumnName("activado");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo_barras");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_producto");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<bool>("GravadoImpuesto")
                        .HasColumnType("boolean")
                        .HasColumnName("gravado_impuesto");

                    b.Property<long>("IdCategoria")
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria");

                    b.Property<long>("IdMarca")
                        .HasColumnType("bigint")
                        .HasColumnName("id_marca");

                    b.Property<long>("IdTipoProducto")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_producto");

                    b.Property<long>("IdUnidadMedida")
                        .HasColumnType("bigint")
                        .HasColumnName("id_unidad");

                    b.Property<string>("ImagenPrincipalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagen_principal_url");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre_producto");

                    b.Property<bool>("PermiteInventarioNegativo")
                        .HasColumnType("boolean")
                        .HasColumnName("permite_inventario_negativo");

                    b.Property<decimal>("PorcentajeImpuesto")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("porcentaje_impuesto");

                    b.Property<decimal>("PrecioCompra")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_compra");

                    b.Property<decimal>("PrecioVentaDistribuidor")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_venta_distribuidor");

                    b.Property<decimal>("PrecioVentaMayorista")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_venta_mayorista");

                    b.Property<decimal>("PrecioVentaPublico")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_venta_publico");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku");

                    b.Property<decimal?>("StockMaximo")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("stock_maximo");

                    b.Property<decimal>("StockMinimo")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("stock_minimo");

                    b.Property<bool>("TieneVariantes")
                        .HasColumnType("boolean")
                        .HasColumnName("tiene_variantes");

                    b.Property<string>("UsuarioActualizacion")
                        .HasColumnType("text")
                        .HasColumnName("usuario_modificacion");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_creacion");

                    b.HasKey("Id");

                    b.HasIndex("CodigoProducto")
                        .IsUnique();

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdMarca");

                    b.HasIndex("IdUnidadMedida");

                    b.ToTable("productos", "catalogo");
                });

            modelBuilder.Entity("Catalogo.Domain.Entidades.UnidadMedida", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_unidad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean")
                        .HasColumnName("activado");

                    b.Property<string>("CodigoSunat")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_sunat");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("NombreUnidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_unidad");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("simbolo");

                    b.Property<string>("UsuarioActualizacion")
                        .HasColumnType("text")
                        .HasColumnName("usuario_modificacion");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_creacion");

                    b.HasKey("Id");

                    b.ToTable("unidades_medida", "catalogo");
                });

            modelBuilder.Entity("Catalogo.Domain.Entidades.VarianteProducto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_variante");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activado")
                        .HasColumnType("boolean");

                    b.Property<string>("AtributosJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("atributos_json");

                    b.Property<string>("CodigoBarrasVariante")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo_barras_variante");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("IdProducto")
                        .HasColumnType("bigint")
                        .HasColumnName("id_producto");

                    b.Property<string>("NombreCompletoVariante")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre_completo_variante");

                    b.Property<decimal>("PrecioAdicional")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_adicional");

                    b.Property<string>("SkuVariante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku_variante");

                    b.Property<string>("UsuarioActualizacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdProducto");

                    b.ToTable("variantes_producto", "catalogo");
                });

            modelBuilder.Entity("Catalogo.Domain.Entidades.Categoria", b =>
                {
                    b.HasOne("Catalogo.Domain.Entidades.Categoria", "CategoriaPadre")
                        .WithMany("SubCategorias")
                        .HasForeignKey("IdCategoriaPadre");

                    b.Navigation("CategoriaPadre");
                });

            modelBuilder.Entity("Catalogo.Domain.Entidades.ImagenProducto", b =>
                {
                    b.HasOne("Catalogo.Domain.Entidades.Producto", "Producto")
                        .WithMany("Imagenes")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Catalogo.Domain.Entidades.Producto", b =>
                {
                    b.HasOne("Catalogo.Domain.Entidades.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Catalogo.Domain.Entidades.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Catalogo.Domain.Entidades.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("IdUnidadMedida")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Marca");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("Catalogo.Domain.Entidades.VarianteProducto", b =>
                {
                    b.HasOne("Catalogo.Domain.Entidades.Producto", "Producto")
                        .WithMany("Variantes")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Catalogo.Domain.Entidades.Categoria", b =>
                {
                    b.Navigation("SubCategorias");
                });

            modelBuilder.Entity("Catalogo.Domain.Entidades.Producto", b =>
                {
                    b.Navigation("Imagenes");

                    b.Navigation("Variantes");
                });
#pragma warning restore 612, 618
        }
    }
}
