/*
==============================================================================
MIGRACIÓN FASE 1: NÚCLEO Y KARDEX VALORIZADO
==============================================================================
Este script realiza los cambios necesarios en la base de datos para soportar:
1. Kardex Valorizado (Costo Promedio Ponderado).
2. Gestión de Series y Correlativos (ya existentes en configuracion.series_comprobantes).
3. Tablas para Notas de Crédito y Débito.
*/

-- 1. EXTENSIÓN DE INVENTARIO PARA KARDEX VALORIZADO
------------------------------------------------------------------------------
ALTER TABLE inventario.movimientos_inventario 
ADD COLUMN IF NOT EXISTS saldo_cantidad DECIMAL(10,3) DEFAULT 0,
ADD COLUMN IF NOT EXISTS saldo_valorizado DECIMAL(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS costo_promedio_actual DECIMAL(12,4) DEFAULT 0;

ALTER TABLE inventario.stock
ADD COLUMN IF NOT EXISTS costo_promedio DECIMAL(12,4) DEFAULT 0,
ADD COLUMN IF NOT EXISTS valor_total DECIMAL(12,2) DEFAULT 0;

COMMENT ON COLUMN inventario.movimientos_inventario.saldo_cantidad IS 'Cantidad acumulada en stock luego del movimiento';
COMMENT ON COLUMN inventario.movimientos_inventario.saldo_valorizado IS 'Valor monetario acumulado del stock luego del movimiento';
COMMENT ON COLUMN inventario.movimientos_inventario.costo_promedio_actual IS 'Costo promedio ponderado calculado al momento del movimiento';

-- 2. TABLAS DE NOTAS DE CRÉDITO Y DÉBITO (VENTAS)
------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ventas.notas (
    id_nota BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta_referencia BIGINT NOT NULL,
    id_tipo_nota BIGINT NOT NULL, -- Referencia a tabla general (Catalogo SUNAT 09 o 10)
    id_tipo_comprobante BIGINT NOT NULL, -- 07 Nota Crédito, 08 Nota Débito
    serie CHARACTER VARYING(4) NOT NULL,
    numero BIGINT NOT NULL,
    fecha_emision TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    motivo_sustento TEXT NOT NULL,
    moneda CHARACTER VARYING(3) NOT NULL,
    tipo_cambio DECIMAL(10,4) NOT NULL,
    subtotal_gravado DECIMAL(12,2) NOT NULL,
    total_impuesto DECIMAL(12,2) NOT NULL,
    total_nota DECIMAL(12,2) NOT NULL,
    id_estado BIGINT NOT NULL, -- Pendiente, Aceptado, Anulado
    activado BOOLEAN DEFAULT TRUE NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    usuario_creacion CHARACTER VARYING(50) NOT NULL,
    fecha_modificacion TIMESTAMP WITH TIME ZONE,
    usuario_modificacion CHARACTER VARYING(50),
    CONSTRAINT fk_notas_ventas_referencia FOREIGN KEY (id_venta_referencia) REFERENCES ventas.ventas(id_venta)
);

CREATE TABLE IF NOT EXISTS ventas.detalle_notas (
    id_detalle_nota BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_nota BIGINT NOT NULL,
    id_producto BIGINT NOT NULL,
    id_variante BIGINT,
    cantidad DECIMAL(10,3) NOT NULL,
    precio_unitario DECIMAL(12,2) NOT NULL,
    impuesto_item DECIMAL(12,2) NOT NULL,
    total_item DECIMAL(12,2) NOT NULL,
    activado BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT fk_detalle_notas_cabecera FOREIGN KEY (id_nota) REFERENCES ventas.notas(id_nota) ON DELETE CASCADE
);

-- 3. TABLAS DE NOTAS DE CRÉDITO Y DÉBITO (COMPRAS)
------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS compras.notas (
    id_nota BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_compra_referencia BIGINT NOT NULL,
    id_tipo_comprobante BIGINT NOT NULL, -- 07 Nota Crédito, 08 Nota Débito
    serie_comprobante CHARACTER VARYING(10) NOT NULL,
    numero_comprobante CHARACTER VARYING(20) NOT NULL,
    fecha_emision TIMESTAMP WITH TIME ZONE NOT NULL,
    motivo_sustento TEXT NOT NULL,
    subtotal DECIMAL(12,2) NOT NULL,
    impuesto DECIMAL(12,2) NOT NULL,
    total DECIMAL(12,2) NOT NULL,
    activado BOOLEAN DEFAULT TRUE NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    usuario_creacion CHARACTER VARYING(50) NOT NULL,
    CONSTRAINT fk_notas_compras_referencia FOREIGN KEY (id_compra_referencia) REFERENCES compras.compras(id_compra)
);

CREATE TABLE IF NOT EXISTS compras.detalle_notas (
    id_detalle_nota BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_nota BIGINT NOT NULL,
    id_producto BIGINT NOT NULL,
    cantidad DECIMAL(10,3) NOT NULL,
    precio_unitario DECIMAL(12,2) NOT NULL,
    subtotal DECIMAL(12,2) NOT NULL,
    activado BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT fk_detalle_notas_compras_cabecera FOREIGN KEY (id_nota) REFERENCES compras.notas(id_nota) ON DELETE CASCADE
);

-- 4. AJUSTES EN SERIES (ASEGURAR CAMPOS PARA SUNAT)
------------------------------------------------------------------------------
-- Si la tabla ya existe, aseguramos que tenga id_tipo_comprobante para filtrar por Factura/Boleta/Nota
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='configuracion' AND table_name='series_comprobantes' AND column_name='id_tipo_comprobante') THEN
        ALTER TABLE configuracion.series_comprobantes ADD COLUMN id_tipo_comprobante BIGINT;
    END IF;
END $$;

-- 5. NORMALIZACIÓN DE TABLAS SUNAT Y VÍNCULO ALMACÉN-SUCURSAL (2026-02-16)
------------------------------------------------------------------------------

-- 5.1 Renombrar tablas a singular (Normalización)
DO $$ 
BEGIN
    -- Renombrar tablas principales
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='configuracion' AND table_name='tipos_comprobantes') THEN
        ALTER TABLE configuracion.tipos_comprobantes RENAME TO tipo_comprobante;
    END IF;
    
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='configuracion' AND table_name='impuestos') THEN
        ALTER TABLE configuracion.impuestos RENAME TO impuesto;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='configuracion' AND table_name='sucursales') THEN
        ALTER TABLE configuracion.sucursales RENAME TO sucursal;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='configuracion' AND table_name='metodos_pago') THEN
        ALTER TABLE configuracion.metodos_pago RENAME TO metodo_pago;
    END IF;

    -- Renombrar tablas SUNAT (posibles nombres previos en mayúsculas)
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='configuracion' AND table_name='DOCUMENTOIDENTIDAD') THEN
        ALTER TABLE configuracion."DOCUMENTOIDENTIDAD" RENAME TO tipo_documento;
    ELSIF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='configuracion' AND table_name='documentoidentidad') THEN
        ALTER TABLE configuracion.documentoidentidad RENAME TO tipo_documento;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='configuracion' AND table_name='DOCUMENTOIDENTIDAD_DOCUMENTOCOMPROBANTE') THEN
        ALTER TABLE configuracion."DOCUMENTOIDENTIDAD_DOCUMENTOCOMPROBANTE" RENAME TO regla_documento_comprobante;
    ELSIF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='configuracion' AND table_name='documentoidentidad_documentocomprobante') THEN
        ALTER TABLE configuracion.documentoidentidad_documentocomprobante RENAME TO regla_documento_comprobante;
    END IF;
END $$;

-- 5.2 Vincular Almacenes con Sucursales
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='inventario' AND table_name='almacenes' AND column_name='id_sucursal') THEN
        ALTER TABLE inventario.almacenes ADD COLUMN id_sucursal BIGINT NOT NULL DEFAULT 0;
        COMMENT ON COLUMN inventario.almacenes.id_sucursal IS 'ID de la sucursal a la que pertenece el almacén';
    END IF;
END $$;
