using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventario.API.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AgregarTrasladosFinal : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // DropColumns safely
            migrationBuilder.Sql(@"
            DO $$ 
            BEGIN 
                IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='inventario' AND table_name='movimientos_inventario' AND column_name='activado') THEN
                    ALTER TABLE inventario.movimientos_inventario DROP COLUMN activado;
                END IF;
                IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='inventario' AND table_name='movimientos_inventario' AND column_name='fecha_modificacion') THEN
                    ALTER TABLE inventario.movimientos_inventario DROP COLUMN fecha_modificacion;
                END IF;
                IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='inventario' AND table_name='movimientos_inventario' AND column_name='usuario_modificacion') THEN
                    ALTER TABLE inventario.movimientos_inventario DROP COLUMN usuario_modificacion;
                END IF;
            END $$;");

            // Create traslados
            migrationBuilder.Sql(@"
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='inventario' AND table_name='traslados') THEN
                    CREATE TABLE inventario.traslados (
                        id_traslado bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        numero_traslado varchar(20) NOT NULL,
                        almacen_origen_id bigint NOT NULL,
                        almacen_destino_id bigint NOT NULL,
                        fecha_pedido timestamp without time zone NOT NULL,
                        fecha_despacho timestamp without time zone,
                        fecha_recepcion timestamp without time zone,
                        gr_serie varchar(10),
                        gr_numero varchar(20),
                        estado varchar(20) NOT NULL,
                        id_usuario_despacho bigint,
                        id_usuario_recepcion bigint,
                        observaciones text,
                        activado boolean NOT NULL,
                        fecha_creacion timestamp without time zone NOT NULL,
                        usuario_creacion varchar(50) NOT NULL,
                        fecha_modificacion timestamp without time zone,
                        usuario_modificacion varchar(50)
                    );
                END IF;
            END $$;");

            // Create traslados_detalle
            migrationBuilder.Sql(@"
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='inventario' AND table_name='traslados_detalle') THEN
                    CREATE TABLE inventario.traslados_detalle (
                        id_detalle_traslado bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        id_traslado bigint NOT NULL,
                        id_producto bigint NOT NULL,
                        cantidad_solicitada numeric(18,6) NOT NULL,
                        cantidad_despachada numeric(18,6) NOT NULL,
                        cantidad_recibida numeric(18,6) NOT NULL,
                        costo_unitario_despacho numeric(18,6),
                        observaciones text,
                        CONSTRAINT fk_traslados_detalle_traslados_id_traslado FOREIGN KEY (id_traslado) REFERENCES inventario.traslados(id_traslado) ON DELETE CASCADE
                    );
                END IF;
            END $$;");

            // Indexes
            migrationBuilder.Sql(@"CREATE UNIQUE INDEX IF NOT EXISTS ix_traslados_numero_traslado ON inventario.traslados (numero_traslado);");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ix_traslados_detalle_id_traslado ON inventario.traslados_detalle (id_traslado);");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "traslados_detalle",
                schema: "inventario");

            migrationBuilder.DropTable(
                name: "traslados",
                schema: "inventario");

            migrationBuilder.AddColumn<bool>(
                name: "activado",
                schema: "inventario",
                table: "movimientos_inventario",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "fecha_modificacion",
                schema: "inventario",
                table: "movimientos_inventario",
                type: "timestamp without time zone",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "usuario_modificacion",
                schema: "inventario",
                table: "movimientos_inventario",
                type: "character varying(50)",
                maxLength: 50,
                nullable: true);
        }
    }
}
