using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventario.API.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddKardexEntities : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // AlterStock
            migrationBuilder.Sql(@"
            DO $$ 
            BEGIN 
                ALTER TABLE inventario.stock ALTER COLUMN fecha_modificacion TYPE timestamp without time zone;
                ALTER TABLE inventario.stock ALTER COLUMN fecha_modificacion DROP NOT NULL;
                ALTER TABLE inventario.stock ALTER COLUMN fecha_creacion TYPE timestamp without time zone;
            EXCEPTION WHEN OTHERS THEN RAISE NOTICE 'AlterStock already applied or failed';
            END $$;");

            // AlterMovimientos
            migrationBuilder.Sql(@"
            DO $$ 
            BEGIN 
                ALTER TABLE inventario.movimientos_inventario ALTER COLUMN fecha_modificacion TYPE timestamp without time zone;
                ALTER TABLE inventario.movimientos_inventario ALTER COLUMN fecha_modificacion DROP NOT NULL;
                ALTER TABLE inventario.movimientos_inventario ALTER COLUMN fecha_creacion TYPE timestamp without time zone;
            EXCEPTION WHEN OTHERS THEN RAISE NOTICE 'AlterMovimientos already applied or failed';
            END $$;");

            // AlterAlmacenes
            migrationBuilder.Sql(@"
            DO $$ 
            BEGIN 
                ALTER TABLE inventario.almacenes ALTER COLUMN fecha_modificacion TYPE timestamp without time zone;
                ALTER TABLE inventario.almacenes ALTER COLUMN fecha_modificacion DROP NOT NULL;
                ALTER TABLE inventario.almacenes ALTER COLUMN fecha_creacion TYPE timestamp without time zone;
            EXCEPTION WHEN OTHERS THEN RAISE NOTICE 'AlterAlmacenes already applied or failed';
            END $$;");

            // Create inv_kardex_lote
            migrationBuilder.Sql(@"
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='inventario' AND table_name='inv_kardex_lote') THEN
                    CREATE TABLE inventario.inv_kardex_lote (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        producto_id bigint NOT NULL,
                        almacen_id bigint NOT NULL,
                        fecha_entrada date NOT NULL,
                        hora_entrada time NOT NULL,
                        movimiento_origen_id bigint NOT NULL,
                        costo_unitario numeric(18,6) NOT NULL,
                        cantidad_original numeric(18,6) NOT NULL,
                        cantidad_disponible numeric(18,6) NOT NULL,
                        estado varchar(1) NOT NULL,
                        activado boolean NOT NULL,
                        fecha_creacion timestamp without time zone NOT NULL,
                        usuario_creacion varchar(50) NOT NULL,
                        fecha_modificacion timestamp without time zone,
                        usuario_modificacion varchar(50)
                    );
                END IF;
            END $$;");

            // Create inv_kardex_movimiento
            migrationBuilder.Sql(@"
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='inventario' AND table_name='inv_kardex_movimiento') THEN
                    CREATE TABLE inventario.inv_kardex_movimiento (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        uuid varchar(36) NOT NULL,
                        periodo varchar(7) NOT NULL,
                        correlativo_kardex bigint NOT NULL,
                        fecha_movimiento date NOT NULL,
                        hora_movimiento time NOT NULL,
                        fecha_hora_compuesta timestamp without time zone NOT NULL,
                        modulo_origen varchar(30) NOT NULL,
                        tipo_documento varchar(2) NOT NULL,
                        serie_documento varchar(10) NOT NULL,
                        numero_documento varchar(20) NOT NULL,
                        anulado boolean NOT NULL,
                        fecha_anulacion date,
                        motivo_anulacion text,
                        tipo_operacion varchar(1) NOT NULL,
                        motivo_traslado_sunat varchar(2) NOT NULL,
                        descripcion_movimiento varchar(255) NOT NULL,
                        almacen_id bigint NOT NULL,
                        almacen_origen_id bigint,
                        almacen_destino_id bigint,
                        producto_id bigint NOT NULL,
                        unidad_medida_codigo varchar(10) NOT NULL,
                        factor_conversion numeric(18,6) NOT NULL,
                        entrada_cantidad numeric(18,6),
                        entrada_costo_unitario numeric(18,6),
                        entrada_costo_total numeric(18,6),
                        salida_cantidad numeric(18,6),
                        salida_costo_unitario numeric(18,6),
                        salida_costo_total numeric(18,6),
                        saldo_cantidad numeric(18,6) NOT NULL,
                        saldo_costo_unitario numeric(18,6) NOT NULL,
                        saldo_costo_total numeric(18,6) NOT NULL,
                        referencia_id bigint,
                        referencia_tipo varchar(50),
                        lote_id bigint,
                        proveedor_cliente_id bigint,
                        observaciones text,
                        usuario_registro_id bigint NOT NULL,
                        usuario_anulacion_id bigint,
                        recalculado_at timestamp without time zone,
                        activado boolean NOT NULL,
                        fecha_creacion timestamp without time zone NOT NULL,
                        usuario_creacion varchar(50) NOT NULL,
                        fecha_modificacion timestamp without time zone,
                        usuario_modificacion varchar(50)
                    );
                END IF;
            END $$;");

            // Create inv_kardex_periodo_control
            migrationBuilder.Sql(@"
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='inventario' AND table_name='inv_kardex_periodo_control') THEN
                    CREATE TABLE inventario.inv_kardex_periodo_control (
                        periodo varchar(7) PRIMARY KEY,
                        estado varchar(1) NOT NULL,
                        fecha_cierre date,
                        usuario_cierre_id bigint,
                        created_at timestamp without time zone NOT NULL,
                        updated_at timestamp without time zone
                    );
                END IF;
            END $$;");

            // Create inv_kardex_recalculo_log
            migrationBuilder.Sql(@"
            DO $$ 
            BEGIN 
                IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='inventario' AND table_name='inv_kardex_recalculo_log') THEN
                    CREATE TABLE inventario.inv_kardex_recalculo_log (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        almacen_id int NOT NULL,
                        producto_id int NOT NULL,
                        desde_fecha date NOT NULL,
                        motivo varchar(30) NOT NULL,
                        registros_afect int NOT NULL,
                        usuario_id int NOT NULL,
                        duracion_ms int,
                        created_at timestamp without time zone NOT NULL
                    );
                END IF;
            END $$;");

            // Indexes
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ix_inv_kardex_movimiento_fecha_movimiento_hora_movimiento ON inventario.inv_kardex_movimiento (fecha_movimiento, hora_movimiento);");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ix_inv_kardex_movimiento_periodo_almacen_id_producto_id ON inventario.inv_kardex_movimiento (periodo, almacen_id, producto_id);");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ix_inv_kardex_movimiento_referencia_id_referencia_tipo ON inventario.inv_kardex_movimiento (referencia_id, referencia_tipo);");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ix_inv_kardex_movimiento_tipo_documento_serie_documento_numero ON inventario.inv_kardex_movimiento (tipo_documento, serie_documento, numero_documento);");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "inv_kardex_lote",
                schema: "inventario");

            migrationBuilder.DropTable(
                name: "inv_kardex_movimiento",
                schema: "inventario");

            migrationBuilder.DropTable(
                name: "inv_kardex_periodo_control",
                schema: "inventario");

            migrationBuilder.DropTable(
                name: "inv_kardex_recalculo_log",
                schema: "inventario");

            migrationBuilder.AlterColumn<DateTime>(
                name: "fecha_modificacion",
                schema: "inventario",
                table: "stock",
                type: "timestamp with time zone",
                nullable: true,
                oldClrType: typeof(DateTime),
                oldType: "timestamp without time zone",
                oldNullable: true);

            migrationBuilder.AlterColumn<DateTime>(
                name: "fecha_creacion",
                schema: "inventario",
                table: "stock",
                type: "timestamp with time zone",
                nullable: false,
                oldClrType: typeof(DateTime),
                oldType: "timestamp without time zone");

            migrationBuilder.AlterColumn<DateTime>(
                name: "fecha_modificacion",
                schema: "inventario",
                table: "movimientos_inventario",
                type: "timestamp with time zone",
                nullable: true,
                oldClrType: typeof(DateTime),
                oldType: "timestamp without time zone",
                oldNullable: true);

            migrationBuilder.AlterColumn<DateTime>(
                name: "fecha_creacion",
                schema: "inventario",
                table: "movimientos_inventario",
                type: "timestamp with time zone",
                nullable: false,
                oldClrType: typeof(DateTime),
                oldType: "timestamp without time zone");

            migrationBuilder.AlterColumn<DateTime>(
                name: "fecha_modificacion",
                schema: "inventario",
                table: "almacenes",
                type: "timestamp with time zone",
                nullable: true,
                oldClrType: typeof(DateTime),
                oldType: "timestamp without time zone",
                oldNullable: true);

            migrationBuilder.AlterColumn<DateTime>(
                name: "fecha_creacion",
                schema: "inventario",
                table: "almacenes",
                type: "timestamp with time zone",
                nullable: false,
                oldClrType: typeof(DateTime),
                oldType: "timestamp without time zone");
        }
    }
}
