/*
 * 12_SUNAT_NOTAS_VENTAS.sql
 * Implementación de Notas de Crédito y Débito para el esquema de Ventas.
 * Generado via EF Core Migration: AddSunatNotasVentas
 */

START TRANSACTION;

-- Eliminar vistas dependientes temporalmente para permitir cambios de tipos en columnas
DROP VIEW IF EXISTS vistas.vw_notas_credito_debito;
DROP VIEW IF EXISTS vistas.vw_caja_movimientos;
DROP VIEW IF EXISTS vistas.vw_stock_actual;
DROP VIEW IF EXISTS vistas.vw_kardex_movimientos;
DROP VIEW IF EXISTS vistas.vw_lista_compras;
DROP VIEW IF EXISTS vistas.vw_detalle_venta;
DROP VIEW IF EXISTS vistas.vw_lista_ventas;

-- Normalización de longitudes de usuario y campos SUNAT en ventas
ALTER TABLE ventas.ventas ALTER COLUMN usuario_modificacion TYPE character varying(100);
ALTER TABLE ventas.ventas ALTER COLUMN usuario_creacion TYPE character varying(100);
ALTER TABLE ventas.ventas ALTER COLUMN moneda TYPE character varying(255);
ALTER TABLE ventas.ventas ADD COLUMN IF NOT EXISTS estado_sunat text NOT NULL DEFAULT '';
ALTER TABLE ventas.ventas ADD COLUMN IF NOT EXISTS fecha_anulacion timestamp with time zone;
ALTER TABLE ventas.ventas ADD COLUMN IF NOT EXISTS motivo_anulacion text;
ALTER TABLE ventas.ventas ADD COLUMN IF NOT EXISTS numero_resumen_baja text;

-- Ampliación de auditoría en tablas relacionadas
ALTER TABLE ventas.pagos ALTER COLUMN usuario_modificacion TYPE character varying(100);
ALTER TABLE ventas.pagos ALTER COLUMN usuario_creacion TYPE character varying(100);
ALTER TABLE ventas.movimientos_caja ALTER COLUMN usuario_modificacion TYPE character varying(100);
ALTER TABLE ventas.movimientos_caja ALTER COLUMN usuario_responsable TYPE character varying(100);
ALTER TABLE ventas.metodos_pago ALTER COLUMN usuario_modificacion TYPE character varying(100);
ALTER TABLE ventas.metodos_pago ALTER COLUMN usuario_creacion TYPE character varying(100);
ALTER TABLE ventas.detalle_venta ALTER COLUMN usuario_modificacion TYPE character varying(100);
ALTER TABLE ventas.detalle_venta ALTER COLUMN usuario_creacion TYPE character varying(100);
ALTER TABLE ventas.detalle_cotizacion ALTER COLUMN usuario_modificacion TYPE character varying(100);
-- ALTER TABLE ventas.detalle_cotizacion ALTER COLUMN usuario_creacion TYPE character varying(100);
ALTER TABLE ventas.cotizaciones ALTER COLUMN usuario_modificacion TYPE character varying(100);
ALTER TABLE ventas.cotizaciones ALTER COLUMN usuario_creacion TYPE character varying(100);
ALTER TABLE ventas.cajas ALTER COLUMN usuario_modificacion TYPE character varying(100);
ALTER TABLE ventas.cajas ALTER COLUMN usuario_creacion TYPE character varying(100);

-- Tabla de Notas de Crédito
CREATE TABLE IF NOT EXISTS ventas.nota_credito (
    id_nota bigint GENERATED BY DEFAULT AS IDENTITY,
    serie character varying(4) NOT NULL,
    numero bigint NOT NULL,
    tipo_comprobante character varying(2) NOT NULL,
    id_venta_referencia bigint NOT NULL,
    serie_referencia character varying(4) NOT NULL,
    numero_referencia bigint NOT NULL,
    tipo_doc_referencia character varying(2) NOT NULL,
    id_tipo_nota bigint NOT NULL,
    motivo_sustento text NOT NULL,
    cliente_tipo_doc character varying(2) NOT NULL,
    cliente_nro_doc character varying(15) NOT NULL,
    cliente_razon_social character varying(250) NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    igv numeric(12,2) NOT NULL,
    total numeric(12,2) NOT NULL,
    porcentaje_igv numeric(5,2) NOT NULL,
    moneda character varying(3) NOT NULL,
    tipo_cambio numeric(10,4),
    afecta_stock boolean NOT NULL,
    fecha_emision date NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_envio_sunat timestamp with time zone,
    respuesta_sunat_codigo character varying(10),
    respuesta_sunat_desc text,
    hash_cdr text,
    xml_generado text,
    activado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    usuario_creacion character varying(100) NOT NULL,
    fecha_modificacion timestamp with time zone,
    usuario_modificacion character varying(100),
    CONSTRAINT pk_nota_credito PRIMARY KEY (id_nota),
    CONSTRAINT fk_nota_credito_ventas_id_venta_referencia FOREIGN KEY (id_venta_referencia) REFERENCES ventas.ventas (id_venta) ON DELETE CASCADE
);

-- Tabla de Notas de Débito
CREATE TABLE IF NOT EXISTS ventas.nota_debito (
    id_nota bigint GENERATED BY DEFAULT AS IDENTITY,
    serie character varying(4) NOT NULL,
    numero bigint NOT NULL,
    tipo_comprobante character varying(2) NOT NULL,
    id_venta_referencia bigint NOT NULL,
    serie_referencia character varying(4) NOT NULL,
    numero_referencia bigint NOT NULL,
    tipo_doc_referencia character varying(2) NOT NULL,
    id_tipo_nota bigint NOT NULL,
    motivo_sustento text NOT NULL,
    cliente_tipo_doc character varying(2) NOT NULL,
    cliente_nro_doc character varying(15) NOT NULL,
    cliente_razon_social character varying(250) NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    igv numeric(12,2) NOT NULL,
    total numeric(12,2) NOT NULL,
    porcentaje_igv numeric(5,2) NOT NULL,
    moneda character varying(3) NOT NULL,
    tipo_cambio numeric(10,4),
    afecta_stock boolean NOT NULL,
    fecha_emision date NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_envio_sunat timestamp with time zone,
    respuesta_sunat_codigo character varying(10),
    respuesta_sunat_desc text,
    hash_cdr text,
    xml_generado text,
    activado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    usuario_creacion character varying(100) NOT NULL,
    fecha_modificacion timestamp with time zone,
    usuario_modificacion character varying(100),
    CONSTRAINT pk_nota_debito PRIMARY KEY (id_nota),
    CONSTRAINT fk_nota_debito_ventas_id_venta_referencia FOREIGN KEY (id_venta_referencia) REFERENCES ventas.ventas (id_venta) ON DELETE CASCADE
);

-- Detalles de Notas
CREATE TABLE IF NOT EXISTS ventas.nota_credito_detalle (
    id_detalle bigint GENERATED BY DEFAULT AS IDENTITY,
    id_nota_credito bigint NOT NULL,
    id_venta_detalle bigint,
    id_producto bigint NOT NULL,
    descripcion character varying(500) NOT NULL,
    unidad_medida character varying(10) NOT NULL,
    cantidad numeric(12,4) NOT NULL,
    precio_unitario numeric(12,4) NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    igv numeric(12,2) NOT NULL,
    total numeric(12,2) NOT NULL,
    activado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    usuario_creacion character varying(100) NOT NULL,
    fecha_modificacion timestamp with time zone,
    usuario_modificacion character varying(100),
    CONSTRAINT pk_nota_credito_detalle PRIMARY KEY (id_detalle),
    CONSTRAINT fk_nota_credito_detalle_detalle_venta_id_venta_detalle FOREIGN KEY (id_venta_detalle) REFERENCES ventas.detalle_venta (id_detalle_venta),
    CONSTRAINT fk_nota_credito_detalle_nota_credito_id_nota_credito FOREIGN KEY (id_nota_credito) REFERENCES ventas.nota_credito (id_nota) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ventas.nota_debito_detalle (
    id_detalle bigint GENERATED BY DEFAULT AS IDENTITY,
    id_nota_debito bigint NOT NULL,
    id_venta_detalle bigint,
    id_producto bigint NOT NULL,
    descripcion character varying(500) NOT NULL,
    unidad_medida character varying(10) NOT NULL,
    cantidad numeric(12,4) NOT NULL,
    precio_unitario numeric(12,4) NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    igv numeric(12,2) NOT NULL,
    total numeric(12,2) NOT NULL,
    activado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    usuario_creacion character varying(100) NOT NULL,
    fecha_modificacion timestamp with time zone,
    usuario_modificacion character varying(100),
    CONSTRAINT pk_nota_debito_detalle PRIMARY KEY (id_detalle),
    CONSTRAINT fk_nota_debito_detalle_detalle_venta_id_venta_detalle FOREIGN KEY (id_venta_detalle) REFERENCES ventas.detalle_venta (id_detalle_venta),
    CONSTRAINT fk_nota_debito_detalle_nota_debito_id_nota_debito FOREIGN KEY (id_nota_debito) REFERENCES ventas.nota_debito (id_nota) ON DELETE CASCADE
);

-- Índices para optimización
CREATE INDEX IF NOT EXISTS ix_nota_credito_id_venta_referencia ON ventas.nota_credito (id_venta_referencia);
CREATE INDEX IF NOT EXISTS ix_nota_credito_detalle_id_nota_credito ON ventas.nota_credito_detalle (id_nota_credito);
CREATE INDEX IF NOT EXISTS ix_nota_debito_id_venta_referencia ON ventas.nota_debito (id_venta_referencia);
CREATE INDEX IF NOT EXISTS ix_nota_debito_detalle_id_nota_debito ON ventas.nota_debito_detalle (id_nota_debito);

-- Recrear vistas eliminadas por dependencias
CREATE OR REPLACE VIEW vistas.vw_lista_ventas AS
SELECT 
    v.id_venta, 
    v.serie, 
    v.numero, 
    v.fecha_emision,
    tc.codigo AS codigo_tipo_comprobante, 
    tc.nombre AS nombre_tipo_comprobante,
    c.numero_documento AS numero_documento_cliente, 
    c.razon_social AS razon_social_cliente,
    v.subtotal_gravado + v.subtotal_exonerado + v.subtotal_inafecto AS subtotal,
    v.total_impuesto AS igv, 
    v.total_venta AS total, 
    v.moneda,
    eg.nombre AS estado_venta,
    v.usuario_creacion AS nombre_usuario_creacion,
    EXISTS(SELECT 1 FROM ventas.nota_credito n JOIN configuracion.tipo_comprobante tcn ON n.tipo_comprobante = tcn.codigo WHERE n.id_venta_referencia = v.id_venta AND tcn.codigo = '07') AS tiene_nota_credito,
    EXISTS(SELECT 1 FROM ventas.nota_debito n JOIN configuracion.tipo_comprobante tcn ON n.tipo_comprobante = tcn.codigo WHERE n.id_venta_referencia = v.id_venta AND tcn.codigo = '08') AS tiene_nota_debito
FROM ventas.ventas v
JOIN clientes.clientes c ON v.id_cliente = c.id_cliente
JOIN configuracion.tipo_comprobante tc ON v.id_tipo_comprobante = tc.id_tipo_comprobante
LEFT JOIN configuracion.tablas_generales_detalle eg ON v.id_estado = eg.id_detalle;

CREATE OR REPLACE VIEW vistas.vw_detalle_venta AS
SELECT 
    d.id_detalle_venta, 
    d.id_venta,
    p.id_producto, 
    p.codigo_producto, 
    d.descripcion_producto,
    um.codigo_sunat AS codigo_unidad_medida, 
    um.simbolo AS simbolo_unidad,
    d.cantidad, 
    d.precio_unitario_base, 
    d.precio_unitario AS precio_unitario_con_igv,
    d.descuento_item, 
    d.valor_item,
    ta.codigo AS codigo_afectacion_igv, 
    ta.nombre AS nombre_afectacion_igv,
    d.codigo_tributo, 
    d.porcentaje_impuesto AS porcentaje_igv, 
    d.impuesto_item,
    d.total_item
FROM ventas.detalle_venta d
JOIN catalogo.productos p ON d.id_producto = p.id_producto
JOIN catalogo.unidades_medida um ON p.id_unidad = um.id_unidad
LEFT JOIN configuracion.tipo_afectacion_igv ta ON d.codigo_afectacion_igv = ta.codigo;

CREATE OR REPLACE VIEW vistas.vw_lista_compras AS
SELECT 
    c.id_compra, 
    c.serie_comprobante, 
    c.numero_comprobante, 
    c.fecha_emision,
    tc.nombre AS nombre_tipo_comprobante,
    p.numero_documento AS numero_documento_proveedor, 
    p.razon_social AS razon_social_proveedor,
    c.subtotal, 
    c.impuesto AS igv, 
    c.total, 
    c.moneda,
    a.nombre_almacen AS nombre_almacen_destino,
    (c.id_orden_compra_ref IS NOT NULL) AS tiene_orden_compra_vinculada
FROM compras.compras c
JOIN compras.proveedores p ON c.id_proveedor = p.id_proveedor
JOIN configuracion.tipo_comprobante tc ON c.id_tipo_comprobante = tc.id_tipo_comprobante
JOIN inventario.almacenes a ON c.id_almacen = a.id_almacen;

CREATE OR REPLACE VIEW vistas.vw_kardex_movimientos AS
SELECT 
    m.id_movimiento, 
    m.fecha_creacion AS fecha_movimiento,
    p.codigo_producto, 
    p.nombre_producto AS descripcion_producto,
    a.nombre_almacen,
    tm.nombre AS tipo_operacion,
    m.referencia_modulo AS tipo_documento_origen, 
    m.id_referencia::text AS numero_documento,
    m.cantidad, 
    m.costo_unitario_movimiento AS costo_unitario, 
    m.cantidad * m.costo_unitario_movimiento AS costo_total,
    m.cantidad_nueva AS saldo_cantidad,
    m.observaciones
FROM inventario.movimientos_inventario m
JOIN inventario.stock s ON m.id_stock = s.id_stock
JOIN catalogo.productos p ON s.id_producto = p.id_producto
JOIN inventario.almacenes a ON s.id_almacen = a.id_almacen
LEFT JOIN configuracion.tablas_generales_detalle tm ON m.id_tipo_movimiento = tm.id_detalle;

CREATE OR REPLACE VIEW vistas.vw_stock_actual AS
SELECT 
    p.id_producto, 
    p.codigo_producto, 
    p.nombre_producto AS descripcion_producto,
    cat.nombre_categoria, 
    mar.nombre_marca,
    um.codigo_sunat AS codigo_unidad_medida, 
    um.simbolo AS simbolo_unidad,
    a.nombre_almacen, 
    st.cantidad_actual AS stock_actual, 
    st.ubicacion_fisica,
    (st.cantidad_actual < p.stock_minimo) AS alerta_stock_minimo
FROM inventario.stock st
JOIN catalogo.productos p ON st.id_producto = p.id_producto
JOIN catalogo.categorias cat ON p.id_categoria = cat.id_categoria
JOIN catalogo.marcas mar ON p.id_marca = mar.id_marca
JOIN catalogo.unidades_medida um ON p.id_unidad = um.id_unidad
JOIN inventario.almacenes a ON st.id_almacen = a.id_almacen;

CREATE OR REPLACE VIEW vistas.vw_caja_movimientos AS
SELECT 
    m.id_movimiento_caja, 
    m.fecha_movimiento,
    c.nombre_caja, 
    tm.nombre AS tipo_movimiento,
    m.concepto, 
    m.monto, 
    'PEN' AS moneda, -- Por defecto según script
    NULL AS referencia_comprobante,
    m.usuario_responsable AS nombre_usuario
FROM ventas.movimientos_caja m
JOIN ventas.cajas c ON m.id_caja = c.id_caja
LEFT JOIN configuracion.tablas_generales_detalle tm ON m.id_tipo_movimiento = tm.id_detalle;

CREATE OR REPLACE VIEW vistas.vw_notas_credito_debito AS
SELECT 
    n.id_nota, 
    CASE WHEN tc.codigo = '07' THEN 'CREDITO' ELSE 'DEBITO' END AS tipo_nota, 
    'VENTA' AS origen,
    n.serie, 
    n.numero, 
    n.fecha_emision,
    tc.nombre AS nombre_tipo_comprobante,
    n.serie_referencia || '-' || n.numero_referencia AS comprobante_referencia,
    n.cliente_razon_social AS razon_social_cliente_o_proveedor,
    CAST(n.id_tipo_nota AS character varying) AS codigo_motivo, 
    n.motivo_sustento AS descripcion_motivo,
    n.afecta_stock AS devuelve_stock,
    n.total AS monto_total,
    n.estado AS estado
FROM ventas.nota_credito n
JOIN configuracion.tipo_comprobante tc ON n.tipo_comprobante = tc.codigo

UNION ALL

SELECT 
    n.id_nota, 
    CASE WHEN tc.codigo = '07' THEN 'CREDITO' ELSE 'DEBITO' END AS tipo_nota, 
    'VENTA' AS origen,
    n.serie, 
    n.numero, 
    n.fecha_emision,
    tc.nombre AS nombre_tipo_comprobante,
    n.serie_referencia || '-' || n.numero_referencia AS comprobante_referencia,
    n.cliente_razon_social AS razon_social_cliente_o_proveedor,
    CAST(n.id_tipo_nota AS character varying) AS codigo_motivo, 
    n.motivo_sustento AS descripcion_motivo,
    n.afecta_stock AS devuelve_stock,
    n.total AS monto_total,
    n.estado AS estado
FROM ventas.nota_debito n
JOIN configuracion.tipo_comprobante tc ON n.tipo_comprobante = tc.codigo

UNION ALL

SELECT 
    n.id_nota, 
    CASE WHEN tc.codigo = '07' THEN 'CREDITO' ELSE 'DEBITO' END AS tipo_nota, 
    'COMPRA' AS origen,
    n.serie_comprobante AS serie, 
    CAST(n.numero_comprobante AS BIGINT) AS numero, 
    n.fecha_emision,
    tc.nombre AS nombre_tipo_comprobante,
    n.serie_ref || '-' || n.numero_ref AS comprobante_referencia,
    p.razon_social AS razon_social_cliente_o_proveedor,
    COALESCE(mnc.codigo, mnd.codigo) AS codigo_motivo, 
    COALESCE(mnc.nombre, mnd.nombre) AS descripcion_motivo,
    COALESCE(mnc.devuelve_stock, false) AS devuelve_stock,
    n.total AS monto_total,
    'ACTIVO' AS estado
FROM compras.notas n
JOIN configuracion.tipo_comprobante tc ON n.id_tipo_comprobante = tc.id_tipo_comprobante
JOIN compras.compras c ON n.id_compra_referencia = c.id_compra
JOIN compras.proveedores p ON c.id_proveedor = p.id_proveedor
LEFT JOIN configuracion.motivo_nota_credito mnc ON n.codigo_motivo_nc = mnc.codigo
LEFT JOIN configuracion.motivo_nota_debito mnd ON n.codigo_motivo_nd = mnd.codigo;

-- Registro de migración
INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260329205242_AddSunatNotasVentas', '8.0.8')
ON CONFLICT DO NOTHING;

COMMIT;
