/*
 * 13_SUNAT_NOTAS_COMPRAS.sql
 * Implementación de Notas de Crédito y Débito para el esquema de Compras.
 * Generado via EF Core Migration: AddSunatNotasCompras
 */

START TRANSACTION;

-- Eliminar vistas dependientes temporalmente para permitir cambios de tipos en columnas
DROP VIEW IF EXISTS vistas.vw_notas_credito_debito;
DROP VIEW IF EXISTS vistas.vw_lista_compras;

-- Aplicación de longitudes extendidas para auditoría en compras
ALTER TABLE compras.proveedores ALTER COLUMN usuario_modificacion TYPE character varying(100);
ALTER TABLE compras.proveedores ALTER COLUMN usuario_creacion TYPE character varying(100);
ALTER TABLE compras.ordenes_compra ALTER COLUMN usuario_modificacion TYPE character varying(100);
ALTER TABLE compras.ordenes_compra ALTER COLUMN usuario_creacion TYPE character varying(100);
ALTER TABLE compras.notas ALTER COLUMN usuario_modificacion TYPE character varying(100);
ALTER TABLE compras.notas ALTER COLUMN usuario_creacion TYPE character varying(100);
ALTER TABLE compras.detalle_orden_compra ALTER COLUMN usuario_modificacion TYPE character varying(100);
ALTER TABLE compras.detalle_orden_compra ALTER COLUMN usuario_creacion TYPE character varying(100);
ALTER TABLE compras.detalle_notas ALTER COLUMN usuario_modificacion TYPE character varying(100);
ALTER TABLE compras.detalle_notas ALTER COLUMN usuario_creacion TYPE character varying(100);
ALTER TABLE compras.detalle_compra ALTER COLUMN usuario_modificacion TYPE character varying(100);
ALTER TABLE compras.detalle_compra ALTER COLUMN usuario_creacion TYPE character varying(100);
ALTER TABLE compras.compras ALTER COLUMN usuario_modificacion TYPE character varying(100);
ALTER TABLE compras.compras ALTER COLUMN usuario_creacion TYPE character varying(100);

-- Nuevos campos para cumplimiento SUNAT en compras
ALTER TABLE compras.compras ADD COLUMN IF NOT EXISTS estado_sunat text NOT NULL DEFAULT '';
ALTER TABLE compras.compras ADD COLUMN IF NOT EXISTS fecha_anulacion timestamp without time zone;
ALTER TABLE compras.compras ADD COLUMN IF NOT EXISTS motivo_anulacion text;

-- Tabla de Notas de Crédito (Proveedores)
CREATE TABLE IF NOT EXISTS compras.nota_credito (
    id_nota bigint GENERATED BY DEFAULT AS IDENTITY,
    serie character varying(10) NOT NULL,
    numero character varying(20) NOT NULL,
    tipo_comprobante character varying(2) NOT NULL,
    id_compra_referencia bigint NOT NULL,
    serie_referencia character varying(10) NOT NULL,
    numero_referencia character varying(20) NOT NULL,
    tipo_doc_referencia character varying(2) NOT NULL,
    id_tipo_nota bigint NOT NULL,
    motivo_sustento text NOT NULL,
    id_proveedor bigint NOT NULL,
    proveedor_tipo_doc character varying(2) NOT NULL,
    proveedor_nro_doc character varying(15) NOT NULL,
    proveedor_razon_social character varying(250) NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    igv numeric(12,2) NOT NULL,
    total numeric(12,2) NOT NULL,
    moneda character varying(3) NOT NULL,
    tipo_cambio numeric(10,4),
    afecta_stock boolean NOT NULL,
    fecha_emision date NOT NULL,
    estado character varying(20) NOT NULL,
    activado boolean NOT NULL,
    fecha_creacion timestamp without time zone NOT NULL,
    usuario_creacion character varying(100) NOT NULL,
    fecha_modificacion timestamp without time zone,
    usuario_modificacion character varying(100),
    CONSTRAINT pk_nota_credito PRIMARY KEY (id_nota),
    CONSTRAINT fk_nota_credito_compras_id_compra_referencia FOREIGN KEY (id_compra_referencia) REFERENCES compras.compras (id_compra) ON DELETE CASCADE,
    CONSTRAINT fk_nota_credito_proveedores_id_proveedor FOREIGN KEY (id_proveedor) REFERENCES compras.proveedores (id_proveedor) ON DELETE CASCADE
);

-- Tabla de Notas de Débito (Proveedores)
CREATE TABLE IF NOT EXISTS compras.nota_debito (
    id_nota bigint GENERATED BY DEFAULT AS IDENTITY,
    serie character varying(10) NOT NULL,
    numero character varying(20) NOT NULL,
    tipo_comprobante character varying(2) NOT NULL,
    id_compra_referencia bigint NOT NULL,
    serie_referencia character varying(10) NOT NULL,
    numero_referencia character varying(20) NOT NULL,
    tipo_doc_referencia character varying(2) NOT NULL,
    id_tipo_nota bigint NOT NULL,
    motivo_sustento text NOT NULL,
    id_proveedor bigint NOT NULL,
    proveedor_tipo_doc character varying(2) NOT NULL,
    proveedor_nro_doc character varying(15) NOT NULL,
    proveedor_razon_social character varying(250) NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    igv numeric(12,2) NOT NULL,
    total numeric(12,2) NOT NULL,
    moneda character varying(3) NOT NULL,
    tipo_cambio numeric(10,4),
    afecta_stock boolean NOT NULL,
    fecha_emision date NOT NULL,
    estado character varying(20) NOT NULL,
    activado boolean NOT NULL,
    fecha_creacion timestamp without time zone NOT NULL,
    usuario_creacion character varying(100) NOT NULL,
    fecha_modificacion timestamp without time zone,
    usuario_modificacion character varying(100),
    CONSTRAINT pk_nota_debito PRIMARY KEY (id_nota),
    CONSTRAINT fk_nota_debito_compras_id_compra_referencia FOREIGN KEY (id_compra_referencia) REFERENCES compras.compras (id_compra) ON DELETE CASCADE,
    CONSTRAINT fk_nota_debito_proveedores_id_proveedor FOREIGN KEY (id_proveedor) REFERENCES compras.proveedores (id_proveedor) ON DELETE CASCADE
);

-- Detalles de Notas de Compra
CREATE TABLE IF NOT EXISTS compras.nota_credito_detalle (
    id_detalle bigint GENERATED BY DEFAULT AS IDENTITY,
    id_nota_credito bigint NOT NULL,
    id_compra_detalle bigint,
    id_producto bigint NOT NULL,
    descripcion character varying(500) NOT NULL,
    unidad_medida character varying(10) NOT NULL,
    cantidad numeric(12,4) NOT NULL,
    precio_unitario numeric(12,4) NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    igv numeric(12,2) NOT NULL,
    total numeric(12,2) NOT NULL,
    activado boolean NOT NULL,
    fecha_creacion timestamp without time zone NOT NULL,
    usuario_creacion character varying(100) NOT NULL,
    fecha_modificacion timestamp without time zone,
    usuario_modificacion character varying(100),
    CONSTRAINT pk_nota_credito_detalle PRIMARY KEY (id_detalle),
    CONSTRAINT fk_nota_credito_detalle_detalle_compra_id_compra_detalle FOREIGN KEY (id_compra_detalle) REFERENCES compras.detalle_compra (id_detalle_compra),
    CONSTRAINT fk_nota_credito_detalle_nota_credito_id_nota_credito FOREIGN KEY (id_nota_credito) REFERENCES compras.nota_credito (id_nota) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS compras.nota_debito_detalle (
    id_detalle bigint GENERATED BY DEFAULT AS IDENTITY,
    id_nota_debito bigint NOT NULL,
    id_compra_detalle bigint,
    id_producto bigint NOT NULL,
    descripcion character varying(500) NOT NULL,
    unidad_medida character varying(10) NOT NULL,
    cantidad numeric(12,4) NOT NULL,
    precio_unitario numeric(12,4) NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    igv numeric(12,2) NOT NULL,
    total numeric(12,2) NOT NULL,
    activado boolean NOT NULL,
    fecha_creacion timestamp without time zone NOT NULL,
    usuario_creacion character varying(100) NOT NULL,
    fecha_modificacion timestamp without time zone,
    usuario_modificacion character varying(100),
    CONSTRAINT pk_nota_debito_detalle PRIMARY KEY (id_detalle),
    CONSTRAINT fk_nota_debito_detalle_detalle_compra_id_compra_detalle FOREIGN KEY (id_compra_detalle) REFERENCES compras.detalle_compra (id_detalle_compra),
    CONSTRAINT fk_nota_debito_detalle_nota_debito_id_nota_debito FOREIGN KEY (id_nota_debito) REFERENCES compras.nota_debito (id_nota) ON DELETE CASCADE
);

-- Índices específicos
CREATE INDEX IF NOT EXISTS ix_nota_credito_id_compra_referencia ON compras.nota_credito (id_compra_referencia);
CREATE INDEX IF NOT EXISTS ix_nota_debito_id_compra_referencia ON compras.nota_debito (id_compra_referencia);

-- Recrear vistas eliminadas por dependencias
CREATE OR REPLACE VIEW vistas.vw_lista_compras AS
SELECT 
    c.id_compra, 
    c.serie_comprobante, 
    c.numero_comprobante, 
    c.fecha_emision,
    tc.nombre AS nombre_tipo_comprobante,
    p.numero_documento AS numero_documento_proveedor, 
    p.razon_social AS razon_social_proveedor,
    c.subtotal, 
    c.impuesto AS igv, 
    c.total, 
    c.moneda,
    a.nombre_almacen AS nombre_almacen_destino,
    (c.id_orden_compra_ref IS NOT NULL) AS tiene_orden_compra_vinculada
FROM compras.compras c
JOIN compras.proveedores p ON c.id_proveedor = p.id_proveedor
JOIN configuracion.tipo_comprobante tc ON c.id_tipo_comprobante = tc.id_tipo_comprobante
JOIN inventario.almacenes a ON c.id_almacen = a.id_almacen;

CREATE OR REPLACE VIEW vistas.vw_notas_credito_debito AS
SELECT 
    n.id_nota, 
    CASE WHEN tc.codigo = '07' THEN 'CREDITO' ELSE 'DEBITO' END AS tipo_nota, 
    'VENTA' AS origen,
    n.serie, 
    n.numero, 
    n.fecha_emision,
    tc.nombre AS nombre_tipo_comprobante,
    n.serie_referencia || '-' || n.numero_referencia AS comprobante_referencia,
    n.cliente_razon_social AS razon_social_cliente_o_proveedor,
    CAST(n.id_tipo_nota AS character varying) AS codigo_motivo, 
    n.motivo_sustento AS descripcion_motivo,
    n.afecta_stock AS devuelve_stock,
    n.total AS monto_total,
    n.estado AS estado
FROM ventas.nota_credito n
JOIN configuracion.tipo_comprobante tc ON n.tipo_comprobante = tc.codigo

UNION ALL

SELECT 
    n.id_nota, 
    CASE WHEN tc.codigo = '07' THEN 'CREDITO' ELSE 'DEBITO' END AS tipo_nota, 
    'VENTA' AS origen,
    n.serie, 
    n.numero, 
    n.fecha_emision,
    tc.nombre AS nombre_tipo_comprobante,
    n.serie_referencia || '-' || n.numero_referencia AS comprobante_referencia,
    n.cliente_razon_social AS razon_social_cliente_o_proveedor,
    CAST(n.id_tipo_nota AS character varying) AS codigo_motivo, 
    n.motivo_sustento AS descripcion_motivo,
    n.afecta_stock AS devuelve_stock,
    n.total AS monto_total,
    n.estado AS estado
FROM ventas.nota_debito n
JOIN configuracion.tipo_comprobante tc ON n.tipo_comprobante = tc.codigo

UNION ALL

SELECT 
    n.id_nota, 
    CASE WHEN tc.codigo = '07' THEN 'CREDITO' ELSE 'DEBITO' END AS tipo_nota, 
    'COMPRA' AS origen,
    n.serie_comprobante AS serie, 
    CAST(n.numero_comprobante AS BIGINT) AS numero, 
    n.fecha_emision,
    tc.nombre AS nombre_tipo_comprobante,
    n.serie_ref || '-' || n.numero_ref AS comprobante_referencia,
    p.razon_social AS razon_social_cliente_o_proveedor,
    COALESCE(mnc.codigo, mnd.codigo) AS codigo_motivo, 
    COALESCE(mnc.nombre, mnd.nombre) AS descripcion_motivo,
    COALESCE(mnc.devuelve_stock, false) AS devuelve_stock,
    n.total AS monto_total,
    'ACTIVO' AS estado
FROM compras.notas n
JOIN configuracion.tipo_comprobante tc ON n.id_tipo_comprobante = tc.id_tipo_comprobante
JOIN compras.compras c ON n.id_compra_referencia = c.id_compra
JOIN compras.proveedores p ON c.id_proveedor = p.id_proveedor
LEFT JOIN configuracion.motivo_nota_credito mnc ON n.codigo_motivo_nc = mnc.codigo
LEFT JOIN configuracion.motivo_nota_debito mnd ON n.codigo_motivo_nd = mnd.codigo;

-- Registro de migración
INSERT INTO compras.__ef_migrations_history (migration_id, product_version)
VALUES ('20260329205312_AddSunatNotasCompras', '8.0.8')
ON CONFLICT DO NOTHING;

COMMIT;
