CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260129230722_Inicial', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE ventas.detalle_venta ADD codigo_afectacion_igv character varying(2);

ALTER TABLE ventas.detalle_venta ADD codigo_tributo character varying(4);

ALTER TABLE ventas.detalle_venta ADD descuento_item numeric(12,4) NOT NULL DEFAULT 0.0;

ALTER TABLE ventas.detalle_venta ADD precio_unitario_base numeric(12,4);

ALTER TABLE ventas.detalle_venta ADD valor_item numeric(12,4);

CREATE TABLE ventas.notas (
    id_nota bigint GENERATED BY DEFAULT AS IDENTITY,
    id_venta_referencia bigint NOT NULL,
    id_tipo_nota bigint NOT NULL,
    id_tipo_comprobante bigint NOT NULL,
    serie character varying(4) NOT NULL,
    numero bigint NOT NULL,
    fecha_emision timestamp with time zone NOT NULL,
    motivo_sustento text NOT NULL,
    moneda character varying(3) NOT NULL,
    tipo_cambio numeric(10,4) NOT NULL,
    subtotal_gravado numeric(12,2) NOT NULL,
    total_impuesto numeric(12,2) NOT NULL,
    total_nota numeric(12,2) NOT NULL,
    id_estado bigint NOT NULL,
    codigo_tipo_comprobante_ref character varying(10),
    serie_ref character varying(10),
    numero_ref character varying(20),
    codigo_motivo character varying(2),
    descripcion_motivo character varying(200),
    activado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    usuario_creacion character varying(50) NOT NULL,
    fecha_modificacion timestamp with time zone,
    usuario_modificacion character varying(50),
    CONSTRAINT pk_notas PRIMARY KEY (id_nota),
    CONSTRAINT fk_notas_ventas_id_venta_referencia FOREIGN KEY (id_venta_referencia) REFERENCES ventas.ventas (id_venta) ON DELETE CASCADE
);

CREATE TABLE configuracion.series_comprobantes (
    id_serie bigint GENERATED BY DEFAULT AS IDENTITY,
    serie character varying(10) NOT NULL,
    correlativo_actual bigint NOT NULL,
    id_almacen bigint,
    id_tipo_comprobante bigint,
    activado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    usuario_creacion character varying(50) NOT NULL,
    fecha_modificacion timestamp with time zone,
    usuario_modificacion character varying(50),
    CONSTRAINT pk_series_comprobantes PRIMARY KEY (id_serie)
);

CREATE TABLE ventas.detalle_notas (
    id_detalle_nota bigint GENERATED BY DEFAULT AS IDENTITY,
    id_nota bigint NOT NULL,
    id_producto bigint NOT NULL,
    id_variante bigint,
    cantidad numeric(10,3) NOT NULL,
    precio_unitario numeric(12,2) NOT NULL,
    impuesto_item numeric(12,2) NOT NULL,
    total_item numeric(12,2) NOT NULL,
    activado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    usuario_creacion character varying(50) NOT NULL,
    fecha_modificacion timestamp with time zone,
    usuario_modificacion character varying(50),
    CONSTRAINT pk_detalle_notas PRIMARY KEY (id_detalle_nota),
    CONSTRAINT fk_detalle_notas_notas_id_nota FOREIGN KEY (id_nota) REFERENCES ventas.notas (id_nota) ON DELETE CASCADE
);

CREATE INDEX ix_detalle_notas_id_nota ON ventas.detalle_notas (id_nota);

CREATE INDEX ix_notas_id_venta_referencia ON ventas.notas (id_venta_referencia);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260316050735_UpdateSunatFieldsVentas', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE ventas.ventas ALTER COLUMN usuario_modificacion TYPE character varying(100);

ALTER TABLE ventas.ventas ALTER COLUMN usuario_creacion TYPE character varying(100);

ALTER TABLE ventas.ventas ALTER COLUMN moneda TYPE character varying(255);

ALTER TABLE ventas.ventas ADD estado_sunat text NOT NULL DEFAULT '';

ALTER TABLE ventas.ventas ADD fecha_anulacion timestamp with time zone;

ALTER TABLE ventas.ventas ADD motivo_anulacion text;

ALTER TABLE ventas.ventas ADD numero_resumen_baja text;

ALTER TABLE configuracion.series_comprobantes ALTER COLUMN usuario_modificacion TYPE character varying(100);

ALTER TABLE configuracion.series_comprobantes ALTER COLUMN usuario_creacion TYPE character varying(100);

ALTER TABLE ventas.pagos ALTER COLUMN usuario_modificacion TYPE character varying(100);

ALTER TABLE ventas.pagos ALTER COLUMN usuario_creacion TYPE character varying(100);

ALTER TABLE ventas.notas ALTER COLUMN usuario_modificacion TYPE character varying(100);

ALTER TABLE ventas.notas ALTER COLUMN usuario_creacion TYPE character varying(100);

ALTER TABLE ventas.movimientos_caja ALTER COLUMN usuario_modificacion TYPE character varying(100);

ALTER TABLE ventas.movimientos_caja ALTER COLUMN usuario_responsable TYPE character varying(100);

ALTER TABLE ventas.metodos_pago ALTER COLUMN usuario_modificacion TYPE character varying(100);

ALTER TABLE ventas.metodos_pago ALTER COLUMN usuario_creacion TYPE character varying(100);

ALTER TABLE ventas.detalle_venta ALTER COLUMN usuario_modificacion TYPE character varying(100);

ALTER TABLE ventas.detalle_venta ALTER COLUMN usuario_creacion TYPE character varying(100);

ALTER TABLE ventas.detalle_notas ALTER COLUMN usuario_modificacion TYPE character varying(100);

ALTER TABLE ventas.detalle_cotizacion ALTER COLUMN usuario_modificacion TYPE character varying(100);

ALTER TABLE ventas.cotizaciones ALTER COLUMN usuario_modificacion TYPE character varying(100);

ALTER TABLE ventas.cotizaciones ALTER COLUMN usuario_creacion TYPE character varying(100);

ALTER TABLE clientes.contactos_cliente ALTER COLUMN usuario_modificacion TYPE character varying(100);

ALTER TABLE clientes.contactos_cliente ALTER COLUMN usuario_creacion TYPE character varying(100);

ALTER TABLE clientes.clientes ALTER COLUMN usuario_modificacion TYPE character varying(100);

ALTER TABLE clientes.clientes ALTER COLUMN usuario_creacion TYPE character varying(100);

ALTER TABLE ventas.cajas ALTER COLUMN usuario_modificacion TYPE character varying(100);

ALTER TABLE ventas.cajas ALTER COLUMN usuario_creacion TYPE character varying(100);

CREATE TABLE ventas.nota_credito (
    id_nota bigint GENERATED BY DEFAULT AS IDENTITY,
    serie character varying(4) NOT NULL,
    numero bigint NOT NULL,
    tipo_comprobante character varying(2) NOT NULL,
    id_venta_referencia bigint NOT NULL,
    serie_referencia character varying(4) NOT NULL,
    numero_referencia bigint NOT NULL,
    tipo_doc_referencia character varying(2) NOT NULL,
    id_tipo_nota bigint NOT NULL,
    motivo_sustento text NOT NULL,
    cliente_tipo_doc character varying(2) NOT NULL,
    cliente_nro_doc character varying(15) NOT NULL,
    cliente_razon_social character varying(250) NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    igv numeric(12,2) NOT NULL,
    total numeric(12,2) NOT NULL,
    porcentaje_igv numeric(5,2) NOT NULL,
    moneda character varying(3) NOT NULL,
    tipo_cambio numeric(10,4),
    afecta_stock boolean NOT NULL,
    fecha_emision date NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_envio_sunat timestamp with time zone,
    respuesta_sunat_codigo character varying(10),
    respuesta_sunat_desc text,
    hash_cdr text,
    xml_generado text,
    activado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    usuario_creacion character varying(100) NOT NULL,
    fecha_modificacion timestamp with time zone,
    usuario_modificacion character varying(100),
    CONSTRAINT pk_nota_credito PRIMARY KEY (id_nota),
    CONSTRAINT fk_nota_credito_ventas_id_venta_referencia FOREIGN KEY (id_venta_referencia) REFERENCES ventas.ventas (id_venta) ON DELETE CASCADE
);

CREATE TABLE ventas.nota_debito (
    id_nota bigint GENERATED BY DEFAULT AS IDENTITY,
    serie character varying(4) NOT NULL,
    numero bigint NOT NULL,
    tipo_comprobante character varying(2) NOT NULL,
    id_venta_referencia bigint NOT NULL,
    serie_referencia character varying(4) NOT NULL,
    numero_referencia bigint NOT NULL,
    tipo_doc_referencia character varying(2) NOT NULL,
    id_tipo_nota bigint NOT NULL,
    motivo_sustento text NOT NULL,
    cliente_tipo_doc character varying(2) NOT NULL,
    cliente_nro_doc character varying(15) NOT NULL,
    cliente_razon_social character varying(250) NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    igv numeric(12,2) NOT NULL,
    total numeric(12,2) NOT NULL,
    porcentaje_igv numeric(5,2) NOT NULL,
    moneda character varying(3) NOT NULL,
    tipo_cambio numeric(10,4),
    afecta_stock boolean NOT NULL,
    fecha_emision date NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_envio_sunat timestamp with time zone,
    respuesta_sunat_codigo character varying(10),
    respuesta_sunat_desc text,
    hash_cdr text,
    xml_generado text,
    activado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    usuario_creacion character varying(100) NOT NULL,
    fecha_modificacion timestamp with time zone,
    usuario_modificacion character varying(100),
    CONSTRAINT pk_nota_debito PRIMARY KEY (id_nota),
    CONSTRAINT fk_nota_debito_ventas_id_venta_referencia FOREIGN KEY (id_venta_referencia) REFERENCES ventas.ventas (id_venta) ON DELETE CASCADE
);

CREATE TABLE ventas.nota_credito_detalle (
    id_detalle bigint GENERATED BY DEFAULT AS IDENTITY,
    id_nota_credito bigint NOT NULL,
    id_venta_detalle bigint,
    id_producto bigint NOT NULL,
    descripcion character varying(500) NOT NULL,
    unidad_medida character varying(10) NOT NULL,
    cantidad numeric(12,4) NOT NULL,
    precio_unitario numeric(12,4) NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    igv numeric(12,2) NOT NULL,
    total numeric(12,2) NOT NULL,
    activado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    usuario_creacion character varying(100) NOT NULL,
    fecha_modificacion timestamp with time zone,
    usuario_modificacion character varying(100),
    CONSTRAINT pk_nota_credito_detalle PRIMARY KEY (id_detalle),
    CONSTRAINT fk_nota_credito_detalle_detalle_venta_id_venta_detalle FOREIGN KEY (id_venta_detalle) REFERENCES ventas.detalle_venta (id_detalle_venta),
    CONSTRAINT fk_nota_credito_detalle_nota_credito_id_nota_credito FOREIGN KEY (id_nota_credito) REFERENCES ventas.nota_credito (id_nota) ON DELETE CASCADE
);

CREATE TABLE ventas.nota_debito_detalle (
    id_detalle bigint GENERATED BY DEFAULT AS IDENTITY,
    id_nota_debito bigint NOT NULL,
    id_venta_detalle bigint,
    id_producto bigint NOT NULL,
    descripcion character varying(500) NOT NULL,
    unidad_medida character varying(10) NOT NULL,
    cantidad numeric(12,4) NOT NULL,
    precio_unitario numeric(12,4) NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    igv numeric(12,2) NOT NULL,
    total numeric(12,2) NOT NULL,
    activado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    usuario_creacion character varying(100) NOT NULL,
    fecha_modificacion timestamp with time zone,
    usuario_modificacion character varying(100),
    CONSTRAINT pk_nota_debito_detalle PRIMARY KEY (id_detalle),
    CONSTRAINT fk_nota_debito_detalle_detalle_venta_id_venta_detalle FOREIGN KEY (id_venta_detalle) REFERENCES ventas.detalle_venta (id_detalle_venta),
    CONSTRAINT fk_nota_debito_detalle_nota_debito_id_nota_debito FOREIGN KEY (id_nota_debito) REFERENCES ventas.nota_debito (id_nota) ON DELETE CASCADE
);

CREATE INDEX ix_nota_credito_id_venta_referencia ON ventas.nota_credito (id_venta_referencia);

CREATE INDEX ix_nota_credito_detalle_id_nota_credito ON ventas.nota_credito_detalle (id_nota_credito);

CREATE INDEX ix_nota_credito_detalle_id_venta_detalle ON ventas.nota_credito_detalle (id_venta_detalle);

CREATE INDEX ix_nota_debito_id_venta_referencia ON ventas.nota_debito (id_venta_referencia);

CREATE INDEX ix_nota_debito_detalle_id_nota_debito ON ventas.nota_debito_detalle (id_nota_debito);

CREATE INDEX ix_nota_debito_detalle_id_venta_detalle ON ventas.nota_debito_detalle (id_venta_detalle);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260329205242_AddSunatNotasVentas', '8.0.8');

COMMIT;

