/*
==============================================================================
MIGRACIÃ“N FASE 1: NÃšCLEO Y KARDEX VALORIZADO
==============================================================================
Este script realiza los cambios necesarios en la base de datos para soportar:
1. Kardex Valorizado (Costo Promedio Ponderado).
2. GestiÃ³n de Series y Correlativos (ya existentes en configuracion.series_comprobantes).
3. Tablas para Notas de CrÃ©dito y DÃ©bito.
*/

-- 1. EXTENSIÃ“N DE INVENTARIO PARA KARDEX VALORIZADO
------------------------------------------------------------------------------
ALTER TABLE inventario.movimientos_inventario 
ADD COLUMN IF NOT EXISTS saldo_cantidad DECIMAL(10,3) DEFAULT 0,
ADD COLUMN IF NOT EXISTS saldo_valorizado DECIMAL(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS costo_promedio_actual DECIMAL(12,4) DEFAULT 0;

ALTER TABLE inventario.stock
ADD COLUMN IF NOT EXISTS costo_promedio DECIMAL(12,4) DEFAULT 0,
ADD COLUMN IF NOT EXISTS valor_total DECIMAL(12,2) DEFAULT 0;

COMMENT ON COLUMN inventario.movimientos_inventario.saldo_cantidad IS 'Cantidad acumulada en stock luego del movimiento';
COMMENT ON COLUMN inventario.movimientos_inventario.saldo_valorizado IS 'Valor monetario acumulado del stock luego del movimiento';
COMMENT ON COLUMN inventario.movimientos_inventario.costo_promedio_actual IS 'Costo promedio ponderado calculado al momento del movimiento';

-- 2. TABLAS DE NOTAS DE CRÃ‰DITO Y DÃ‰BITO (VENTAS)
------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ventas.notas (
    id_nota BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta_referencia BIGINT NOT NULL,
    id_tipo_nota BIGINT NOT NULL, -- Referencia a tabla general (Catalogo SUNAT 09 o 10)
    id_tipo_comprobante BIGINT NOT NULL, -- 07 Nota CrÃ©dito, 08 Nota DÃ©bito
    serie CHARACTER VARYING(4) NOT NULL,
    numero BIGINT NOT NULL,
    fecha_emision TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    motivo_sustento TEXT NOT NULL,
    moneda CHARACTER VARYING(3) NOT NULL,
    tipo_cambio DECIMAL(10,4) NOT NULL,
    subtotal_gravado DECIMAL(12,2) NOT NULL,
    total_impuesto DECIMAL(12,2) NOT NULL,
    total_nota DECIMAL(12,2) NOT NULL,
    id_estado BIGINT NOT NULL, -- Pendiente, Aceptado, Anulado
    activado BOOLEAN DEFAULT TRUE NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    usuario_creacion CHARACTER VARYING(50) NOT NULL,
    fecha_modificacion TIMESTAMP WITH TIME ZONE,
    usuario_modificacion CHARACTER VARYING(50),
    CONSTRAINT fk_notas_ventas_referencia FOREIGN KEY (id_venta_referencia) REFERENCES ventas.ventas(id_venta)
);

CREATE TABLE IF NOT EXISTS ventas.detalle_notas (
    id_detalle_nota BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_nota BIGINT NOT NULL,
    id_producto BIGINT NOT NULL,
    id_variante BIGINT,
    cantidad DECIMAL(10,3) NOT NULL,
    precio_unitario DECIMAL(12,2) NOT NULL,
    impuesto_item DECIMAL(12,2) NOT NULL,
    total_item DECIMAL(12,2) NOT NULL,
    activado BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT fk_detalle_notas_cabecera FOREIGN KEY (id_nota) REFERENCES ventas.notas(id_nota) ON DELETE CASCADE
);

-- 3. TABLAS DE NOTAS DE CRÃ‰DITO Y DÃ‰BITO (COMPRAS)
------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS compras.notas (
    id_nota BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_compra_referencia BIGINT NOT NULL,
    id_tipo_comprobante BIGINT NOT NULL, -- 07 Nota CrÃ©dito, 08 Nota DÃ©bito
    serie_comprobante CHARACTER VARYING(10) NOT NULL,
    numero_comprobante CHARACTER VARYING(20) NOT NULL,
    fecha_emision TIMESTAMP WITH TIME ZONE NOT NULL,
    motivo_sustento TEXT NOT NULL,
    subtotal DECIMAL(12,2) NOT NULL,
    impuesto DECIMAL(12,2) NOT NULL,
    total DECIMAL(12,2) NOT NULL,
    activado BOOLEAN DEFAULT TRUE NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    usuario_creacion CHARACTER VARYING(50) NOT NULL,
    CONSTRAINT fk_notas_compras_referencia FOREIGN KEY (id_compra_referencia) REFERENCES compras.compras(id_compra)
);

CREATE TABLE IF NOT EXISTS compras.detalle_notas (
    id_detalle_nota BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_nota BIGINT NOT NULL,
    id_producto BIGINT NOT NULL,
    cantidad DECIMAL(10,3) NOT NULL,
    precio_unitario DECIMAL(12,2) NOT NULL,
    subtotal DECIMAL(12,2) NOT NULL,
    activado BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT fk_detalle_notas_compras_cabecera FOREIGN KEY (id_nota) REFERENCES compras.notas(id_nota) ON DELETE CASCADE
);

-- 4. AJUSTES EN SERIES (ASEGURAR CAMPOS PARA SUNAT)
------------------------------------------------------------------------------
-- Si la tabla ya existe, aseguramos que tenga id_tipo_comprobante para filtrar por Factura/Boleta/Nota
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='configuracion' AND table_name='series_comprobantes' AND column_name='id_tipo_comprobante') THEN
        ALTER TABLE configuracion.series_comprobantes ADD COLUMN id_tipo_comprobante BIGINT;
    END IF;
END $$;

-- 5. NORMALIZACIÃ“N DE TABLAS SUNAT Y VÃNCULO ALMACÃ‰N-SUCURSAL (2026-02-16)
------------------------------------------------------------------------------

-- 5.1 Renombrar tablas a singular (NormalizaciÃ³n)
DO $$ 
BEGIN
    -- Renombrar tablas principales
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='configuracion' AND table_name='tipos_comprobantes') THEN
        ALTER TABLE configuracion.tipos_comprobantes RENAME TO tipo_comprobante;
    END IF;
    
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='configuracion' AND table_name='impuestos') THEN
        ALTER TABLE configuracion.impuestos RENAME TO impuesto;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='configuracion' AND table_name='sucursales') THEN
        ALTER TABLE configuracion.sucursales RENAME TO sucursal;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='configuracion' AND table_name='metodos_pago') THEN
        ALTER TABLE configuracion.metodos_pago RENAME TO metodo_pago;
    END IF;

    -- Renombrar tablas SUNAT (posibles nombres previos en mayÃºsculas)
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='configuracion' AND table_name='DOCUMENTOIDENTIDAD') THEN
        ALTER TABLE configuracion."DOCUMENTOIDENTIDAD" RENAME TO tipo_documento;
    ELSIF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='configuracion' AND table_name='documentoidentidad') THEN
        ALTER TABLE configuracion.documentoidentidad RENAME TO tipo_documento;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='configuracion' AND table_name='DOCUMENTOIDENTIDAD_DOCUMENTOCOMPROBANTE') THEN
        ALTER TABLE configuracion."DOCUMENTOIDENTIDAD_DOCUMENTOCOMPROBANTE" RENAME TO regla_documento_comprobante;
    ELSIF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='configuracion' AND table_name='documentoidentidad_documentocomprobante') THEN
        ALTER TABLE configuracion.documentoidentidad_documentocomprobante RENAME TO regla_documento_comprobante;
    END IF;
END $$;

-- 5.2 Vincular Almacenes con Sucursales
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='inventario' AND table_name='almacenes' AND column_name='id_sucursal') THEN
        ALTER TABLE inventario.almacenes ADD COLUMN id_sucursal BIGINT NOT NULL DEFAULT 0;
        COMMENT ON COLUMN inventario.almacenes.id_sucursal IS 'ID de la sucursal a la que pertenece el almacÃ©n';
    END IF;
END $$;

-- 6. MATRIZ DE COMPATIBILIDAD SUNAT (2026-02-16)
------------------------------------------------------------------------------
DO $$ 
BEGIN
    -- 6.1 Asegurar tipos de comprobante adicionales
    INSERT INTO configuracion.tipo_comprobante (codigo, nombre, mueve_stock, tipo_movimiento_stock, activado, usuario_creacion, fecha_creacion)
    SELECT '02', 'RECIBO POR HONORARIOS', false, 'NEUTRO', true, 'SYSTEM', NOW()
    WHERE NOT EXISTS (SELECT 1 FROM configuracion.tipo_comprobante WHERE codigo = '02');

    INSERT INTO configuracion.tipo_comprobante (codigo, nombre, mueve_stock, tipo_movimiento_stock, activado, usuario_creacion, fecha_creacion)
    SELECT '04', 'LIQUIDACIÃ“N DE COMPRA', true, 'ENTRADA', true, 'SYSTEM', NOW()
    WHERE NOT EXISTS (SELECT 1 FROM configuracion.tipo_comprobante WHERE codigo = '04');

    -- 6.2 Asegurar tipos de documento adicionales
    INSERT INTO configuracion.tipo_documento (codigo, nombre, longitud, es_numerico, estado, activado, fecha_creacion, usuario_creacion)
    SELECT '0', 'SIN DOCUMENTO', 1, false, true, true, NOW(), 'SYSTEM'
    WHERE NOT EXISTS (SELECT 1 FROM configuracion.tipo_documento WHERE codigo = '0');

    -- 6.3 Configurar Matriz de Compatibilidad
    -- Limpiar para evitar duplicidad y asegurar exactitud
    DELETE FROM configuracion.regla_documento_comprobante;

    -- RUC(6) -> FACTURA(01), BOLETA(03), LIQ.COMPRA(04), RECIBO HON.(02)
    INSERT INTO configuracion.regla_documento_comprobante (codigo_documento, id_tipo_comprobante, activado, usuario_creacion, fecha_creacion)
    SELECT '6', id_tipo_comprobante, true, 'SYSTEM', NOW() 
    FROM configuracion.tipo_comprobante WHERE codigo IN ('01', '02', '03', '04');

    -- DNI(1) -> BOLETA(03), RECIBO HON.(02)
    INSERT INTO configuracion.regla_documento_comprobante (codigo_documento, id_tipo_comprobante, activado, usuario_creacion, fecha_creacion)
    SELECT '1', id_tipo_comprobante, true, 'SYSTEM', NOW() 
    FROM configuracion.tipo_comprobante WHERE codigo IN ('03', '02');

    -- CARNÃ‰ EXTRANJERÃA(4) -> BOLETA(03)
    INSERT INTO configuracion.regla_documento_comprobante (codigo_documento, id_tipo_comprobante, activado, usuario_creacion, fecha_creacion)
    SELECT '4', id_tipo_comprobante, true, 'SYSTEM', NOW() 
    FROM configuracion.tipo_comprobante WHERE codigo IN ('03');

    -- PASAPORTE(7) -> BOLETA(03)
    INSERT INTO configuracion.regla_documento_comprobante (codigo_documento, id_tipo_comprobante, activado, usuario_creacion, fecha_creacion)
    SELECT '7', id_tipo_comprobante, true, 'SYSTEM', NOW() 
    FROM configuracion.tipo_comprobante WHERE codigo IN ('03');

    -- SIN DOCUMENTO(0) -> BOLETA(03)
    INSERT INTO configuracion.regla_documento_comprobante (codigo_documento, id_tipo_comprobante, activado, usuario_creacion, fecha_creacion)
    SELECT '0', id_tipo_comprobante, true, 'SYSTEM', NOW() 
    FROM configuracion.tipo_comprobante WHERE codigo IN ('03');
END $$;
-- =====================================================
-- SCRIPT DE ESTRUCTURA: Reglas SUNAT y Traslados (V2)
-- =====================================================

-- 1. Tipos de OperaciÃ³n SUNAT (Tabla 12)
CREATE TABLE IF NOT EXISTS configuracion.tipo_operacion_sunat (
    id_tipo_operacion SERIAL PRIMARY KEY,
    codigo CHAR(2) UNIQUE NOT NULL, -- 01, 02, 11, etc.
    nombre VARCHAR(200) NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_creacion VARCHAR(100)
);

-- 2. Matriz de Reglas SUNAT (Referencial)
CREATE TABLE IF NOT EXISTS configuracion.matriz_regla_sunat (
    id_regla SERIAL PRIMARY KEY,
    id_tipo_operacion INTEGER NOT NULL REFERENCES configuracion.tipo_operacion_sunat(id_tipo_operacion),
    id_tipo_comprobante INTEGER NOT NULL REFERENCES configuracion.tipo_comprobante(id_tipo_comprobante),
    nivel_obligatoriedad INTEGER DEFAULT 0, -- 0=N/A, 1=ðŸ”µ, 2=ðŸŸ¡
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_creacion VARCHAR(100)
);

-- 3. Cabecera de Traslados (Inventario)
CREATE TABLE IF NOT EXISTS inventario.traslados (
    id_traslado SERIAL PRIMARY KEY,
    numero_traslado VARCHAR(20) UNIQUE NOT NULL,
    almacen_origen_id BIGINT NOT NULL,
    almacen_destino_id BIGINT NOT NULL,
    fecha_pedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_despacho TIMESTAMP,
    fecha_recepcion TIMESTAMP,
    gr_serie VARCHAR(10),
    gr_numero VARCHAR(20),
    estado VARCHAR(20) DEFAULT 'PENDIENTE', -- PENDIENTE, EN_TRANSITO, RECIBIDO, ANULADO
    id_usuario_despacho BIGINT,
    id_usuario_recepcion BIGINT,
    observaciones TEXT
);

-- 4. Detalle de Traslados (Inventario)
CREATE TABLE IF NOT EXISTS inventario.traslados_detalle (
    id_detalle_traslado SERIAL PRIMARY KEY,
    id_traslado INTEGER REFERENCES inventario.traslados(id_traslado),
    id_producto BIGINT NOT NULL,
    cantidad_solicitada DECIMAL(18,6) NOT NULL,
    cantidad_despachada DECIMAL(18,6) DEFAULT 0,
    cantidad_recibida DECIMAL(18,6) DEFAULT 0,
    costo_unitario_despacho DECIMAL(18,6),
    observaciones TEXT
);

-- 5. Incidencias de Traslados
CREATE TABLE IF NOT EXISTS inventario.traslados_incidencias (
    id_incidencia SERIAL PRIMARY KEY,
    id_detalle_traslado INTEGER REFERENCES inventario.traslados_detalle(id_detalle_traslado),
    tipo_incidencia VARCHAR(20), -- FALTANTE, DAÃ‘ADO, SOBRANTE
    cantidad DECIMAL(18,6) NOT NULL,
    descripcion TEXT
);
/*
==============================================================================
MIGRACIÃ“N: ACTUALIZAR FOREIGN KEYS DE TIPO DOCUMENTO
==============================================================================
Este script actualiza las tablas proveedores, clientes y trabajadores para
que apunten a configuracion.tipo_documento en lugar de tablas_generales_detalle.

IMPORTANTE: Ejecutar despuÃ©s de 09_Migracion_Fase1.sql
==============================================================================
*/

-- ============================================================================
-- 1. MAPEO DE IDs: tablas_generales_detalle -> tipo_documento
-- ============================================================================
-- Primero necesitamos crear una tabla temporal para mapear los IDs antiguos
-- a los nuevos IDs de tipo_documento

DO $$
DECLARE
    v_dni_old_id BIGINT;
    v_ruc_old_id BIGINT;
    v_carnet_old_id BIGINT;
    v_pasaporte_old_id BIGINT;
    v_dni_new_id BIGINT;
    v_ruc_new_id BIGINT;
    v_carnet_new_id BIGINT;
    v_pasaporte_new_id BIGINT;
BEGIN
    -- Obtener IDs antiguos de tablas_generales_detalle (asumiendo cÃ³digos estÃ¡ndar)
    SELECT id_detalle INTO v_dni_old_id 
    FROM configuracion.tablas_generales_detalle 
    WHERE codigo = '1' AND id_tabla_general = (
        SELECT id_tabla_general FROM configuracion.tablas_generales WHERE codigo = 'TIPO_DOCUMENTO'
    ) LIMIT 1;
    
    SELECT id_detalle INTO v_ruc_old_id 
    FROM configuracion.tablas_generales_detalle 
    WHERE codigo = '6' AND id_tabla_general = (
        SELECT id_tabla_general FROM configuracion.tablas_generales WHERE codigo = 'TIPO_DOCUMENTO'
    ) LIMIT 1;
    
    SELECT id_detalle INTO v_carnet_old_id 
    FROM configuracion.tablas_generales_detalle 
    WHERE codigo = '4' AND id_tabla_general = (
        SELECT id_tabla_general FROM configuracion.tablas_generales WHERE codigo = 'TIPO_DOCUMENTO'
    ) LIMIT 1;
    
    SELECT id_detalle INTO v_pasaporte_old_id 
    FROM configuracion.tablas_generales_detalle 
    WHERE codigo = '7' AND id_tabla_general = (
        SELECT id_tabla_general FROM configuracion.tablas_generales WHERE codigo = 'TIPO_DOCUMENTO'
    ) LIMIT 1;
    
    -- Obtener IDs nuevos de tipo_documento
    SELECT id_regla INTO v_dni_new_id FROM configuracion.tipo_documento WHERE codigo = '1' LIMIT 1;
    SELECT id_regla INTO v_ruc_new_id FROM configuracion.tipo_documento WHERE codigo = '6' LIMIT 1;
    SELECT id_regla INTO v_carnet_new_id FROM configuracion.tipo_documento WHERE codigo = '4' LIMIT 1;
    SELECT id_regla INTO v_pasaporte_new_id FROM configuracion.tipo_documento WHERE codigo = '7' LIMIT 1;
    
    RAISE NOTICE 'Mapeo de IDs:';
    RAISE NOTICE 'DNI: % -> %', v_dni_old_id, v_dni_new_id;
    RAISE NOTICE 'RUC: % -> %', v_ruc_old_id, v_ruc_new_id;
    RAISE NOTICE 'Carnet: % -> %', v_carnet_old_id, v_carnet_new_id;
    RAISE NOTICE 'Pasaporte: % -> %', v_pasaporte_old_id, v_pasaporte_new_id;
END $$;

-- ============================================================================
-- 2. ACTUALIZAR TABLA PROVEEDORES
-- ============================================================================

-- 2.1 Eliminar constraint existente
ALTER TABLE compras.proveedores 
DROP CONSTRAINT IF EXISTS fk_proveedor_tipo_documento;

-- 2.2 Actualizar los IDs de tipo documento en proveedores
UPDATE compras.proveedores p
SET id_tipo_documento = td.id_regla
FROM configuracion.tipo_documento td
INNER JOIN configuracion.tablas_generales_detalle tgd 
    ON td.codigo = tgd.codigo
WHERE p.id_tipo_documento = tgd.id_detalle
    AND tgd.id_tabla_general = (
        SELECT id_tabla_general 
        FROM configuracion.tablas_generales 
        WHERE codigo = 'TIPO_DOCUMENTO'
    );

-- 2.3 Crear nuevo constraint apuntando a tipo_documento
ALTER TABLE compras.proveedores
ADD CONSTRAINT fk_proveedor_tipo_documento 
FOREIGN KEY (id_tipo_documento) 
REFERENCES configuracion.tipo_documento(id_regla);

-- Verificar actualizaciÃ³n
SELECT 
    'PROVEEDORES' as tabla,
    COUNT(*) as total_registros,
    COUNT(DISTINCT id_tipo_documento) as tipos_documento_distintos
FROM compras.proveedores;

-- ============================================================================
-- 3. ACTUALIZAR TABLA CLIENTES
-- ============================================================================

-- 3.1 Eliminar constraint existente
ALTER TABLE ventas.clientes 
DROP CONSTRAINT IF EXISTS fk_cliente_tipo_documento;

-- 3.2 Actualizar los IDs de tipo documento en clientes
UPDATE ventas.clientes c
SET id_tipo_documento = td.id_regla
FROM configuracion.tipo_documento td
INNER JOIN configuracion.tablas_generales_detalle tgd 
    ON td.codigo = tgd.codigo
WHERE c.id_tipo_documento = tgd.id_detalle
    AND tgd.id_tabla_general = (
        SELECT id_tabla_general 
        FROM configuracion.tablas_generales 
        WHERE codigo = 'TIPO_DOCUMENTO'
    );

-- 3.3 Crear nuevo constraint apuntando a tipo_documento
ALTER TABLE ventas.clientes
ADD CONSTRAINT fk_cliente_tipo_documento 
FOREIGN KEY (id_tipo_documento) 
REFERENCES configuracion.tipo_documento(id_regla);

-- Verificar actualizaciÃ³n
SELECT 
    'CLIENTES' as tabla,
    COUNT(*) as total_registros,
    COUNT(DISTINCT id_tipo_documento) as tipos_documento_distintos
FROM ventas.clientes;

-- ============================================================================
-- 4. ACTUALIZAR TABLA TRABAJADORES
-- ============================================================================

-- 4.1 Eliminar constraint existente
ALTER TABLE rrhh.trabajadores 
DROP CONSTRAINT IF EXISTS fk_trabajador_tipo_documento;

-- 4.2 Actualizar los IDs de tipo documento en trabajadores
UPDATE rrhh.trabajadores t
SET id_tipo_documento = td.id_regla
FROM configuracion.tipo_documento td
INNER JOIN configuracion.tablas_generales_detalle tgd 
    ON td.codigo = tgd.codigo
WHERE t.id_tipo_documento = tgd.id_detalle
    AND tgd.id_tabla_general = (
        SELECT id_tabla_general 
        FROM configuracion.tablas_generales 
        WHERE codigo = 'TIPO_DOCUMENTO'
    );

-- 4.3 Crear nuevo constraint apuntando a tipo_documento
ALTER TABLE rrhh.trabajadores
ADD CONSTRAINT fk_trabajador_tipo_documento 
FOREIGN KEY (id_tipo_documento) 
REFERENCES configuracion.tipo_documento(id_regla);

-- Verificar actualizaciÃ³n
SELECT 
    'TRABAJADORES' as tabla,
    COUNT(*) as total_registros,
    COUNT(DISTINCT id_tipo_documento) as tipos_documento_distintos
FROM rrhh.trabajadores;

-- ============================================================================
-- 5. VERIFICACIÃ“N FINAL
-- ============================================================================

-- Mostrar resumen de tipos de documento en uso
SELECT 
    td.codigo,
    td.nombre,
    COUNT(DISTINCT p.id_proveedor) as proveedores,
    COUNT(DISTINCT c.id_cliente) as clientes,
    COUNT(DISTINCT t.id_trabajador) as trabajadores
FROM configuracion.tipo_documento td
LEFT JOIN compras.proveedores p ON p.id_tipo_documento = td.id_regla
LEFT JOIN ventas.clientes c ON c.id_tipo_documento = td.id_regla
LEFT JOIN rrhh.trabajadores t ON t.id_tipo_documento = td.id_regla
GROUP BY td.id_regla, td.codigo, td.nombre
ORDER BY td.codigo;

-- ============================================================================
-- NOTAS IMPORTANTES
-- ============================================================================
/*
1. Este script asume que los cÃ³digos en tipo_documento coinciden con los de
   tablas_generales_detalle (1=DNI, 6=RUC, 4=Carnet, 7=Pasaporte, etc.)

2. Si hay registros con id_tipo_documento que no tienen correspondencia en
   tipo_documento, esos registros NO se actualizarÃ¡n y causarÃ¡n error al
   crear el foreign key.

3. Para verificar si hay IDs huÃ©rfanos antes de ejecutar, usar:
   
   SELECT DISTINCT p.id_tipo_documento, tgd.codigo, tgd.valor
   FROM compras.proveedores p
   LEFT JOIN configuracion.tablas_generales_detalle tgd 
       ON p.id_tipo_documento = tgd.id_detalle
   WHERE tgd.id_detalle IS NULL;

4. DespuÃ©s de ejecutar este script, las aplicaciones que usen estas tablas
   deben actualizar sus referencias para usar configuracion.tipo_documento.
*/
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260129221256_AgregarTiposComprobante') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'configuracion') THEN
            CREATE SCHEMA configuracion;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260129221256_AgregarTiposComprobante') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260129221256_AgregarTiposComprobante', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216155444_AddReglasDocumentosSUNAT') THEN
    DROP TABLE IF EXISTS configuracion."DOCUMENTOIDENTIDAD_DOCUMENTOCOMPROBANTE" CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216155444_AddReglasDocumentosSUNAT') THEN
    DROP TABLE IF EXISTS configuracion."DOCUMENTOIDENTIDAD" CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216155444_AddReglasDocumentosSUNAT') THEN
    CREATE TABLE configuracion."DOCUMENTOIDENTIDAD" (
        id_regla bigint GENERATED BY DEFAULT AS IDENTITY,
        codigo character varying(10) NOT NULL,
        nombre character varying(100) NOT NULL,
        longitud integer NOT NULL,
        es_numerico boolean NOT NULL,
        estado boolean NOT NULL,
        activado boolean NOT NULL,
        fecha_creacion timestamp with time zone NOT NULL,
        usuario_creacion character varying(50) NOT NULL,
        fecha_modificacion timestamp with time zone,
        usuario_modificacion character varying(50),
        CONSTRAINT pk_documentoidentidad PRIMARY KEY (id_regla)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216155444_AddReglasDocumentosSUNAT') THEN
    CREATE TABLE configuracion."DOCUMENTOIDENTIDAD_DOCUMENTOCOMPROBANTE" (
        id_relacion bigint GENERATED BY DEFAULT AS IDENTITY,
        codigo_documento character varying(10) NOT NULL,
        id_tipo_comprobante bigint NOT NULL,
        activado boolean NOT NULL,
        fecha_creacion timestamp with time zone NOT NULL,
        usuario_creacion character varying(50) NOT NULL,
        fecha_modificacion timestamp with time zone,
        usuario_modificacion character varying(50),
        CONSTRAINT pk_documentoidentidad_documentocomprobante PRIMARY KEY (id_relacion)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216155444_AddReglasDocumentosSUNAT') THEN
    CREATE INDEX ix_documentoidentidad_documentocomprobante_id_tipo_comprobante ON configuracion."DOCUMENTOIDENTIDAD_DOCUMENTOCOMPROBANTE" (id_tipo_comprobante);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216155444_AddReglasDocumentosSUNAT') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260216155444_AddReglasDocumentosSUNAT', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216160331_SeedReglasDocumentosSUNAT') THEN

                    INSERT INTO configuracion."DOCUMENTOIDENTIDAD" (codigo, nombre, longitud, es_numerico, estado, activado, fecha_creacion, usuario_creacion)
                    SELECT '1', 'DNI', 8, true, true, true, NOW(), 'SISTEMA'
                    WHERE NOT EXISTS (SELECT 1 FROM configuracion."DOCUMENTOIDENTIDAD" WHERE codigo = '1');
                    
                    INSERT INTO configuracion."DOCUMENTOIDENTIDAD" (codigo, nombre, longitud, es_numerico, estado, activado, fecha_creacion, usuario_creacion)
                    SELECT '6', 'RUC', 11, true, true, true, NOW(), 'SISTEMA'
                    WHERE NOT EXISTS (SELECT 1 FROM configuracion."DOCUMENTOIDENTIDAD" WHERE codigo = '6');

                    INSERT INTO configuracion."DOCUMENTOIDENTIDAD" (codigo, nombre, longitud, es_numerico, estado, activado, fecha_creacion, usuario_creacion)
                    SELECT '4', 'CARNET EXTRANJERIA', 12, false, true, true, NOW(), 'SISTEMA'
                    WHERE NOT EXISTS (SELECT 1 FROM configuracion."DOCUMENTOIDENTIDAD" WHERE codigo = '4');

                    INSERT INTO configuracion."DOCUMENTOIDENTIDAD" (codigo, nombre, longitud, es_numerico, estado, activado, fecha_creacion, usuario_creacion)
                    SELECT '7', 'PASAPORTE', 12, false, true, true, NOW(), 'SISTEMA'
                    WHERE NOT EXISTS (SELECT 1 FROM configuracion."DOCUMENTOIDENTIDAD" WHERE codigo = '7');
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216160331_SeedReglasDocumentosSUNAT') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260216160331_SeedReglasDocumentosSUNAT', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216185859_RestoreMissingTables') THEN

                    CREATE TABLE IF NOT EXISTS configuracion.tipos_comprobantes (
                        id_tipo_comprobante BIGSERIAL PRIMARY KEY,
                        codigo VARCHAR(10) NOT NULL,
                        nombre VARCHAR(100) NOT NULL,
                        mueve_stock BOOLEAN NOT NULL DEFAULT false,
                        tipo_movimiento_stock VARCHAR(20) NOT NULL DEFAULT 'DEPENDIENTE',
                        activado BOOLEAN NOT NULL DEFAULT true,
                        fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        usuario_creacion VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
                        fecha_modificacion TIMESTAMP WITH TIME ZONE,
                        usuario_modificacion VARCHAR(50)
                    );

                    CREATE TABLE IF NOT EXISTS configuracion.impuestos (
                        id_impuesto BIGSERIAL PRIMARY KEY,
                        codigo VARCHAR(10) NOT NULL,
                        nombre VARCHAR(100) NOT NULL,
                        porcentaje DECIMAL(5,2) NOT NULL DEFAULT 0,
                        es_igv BOOLEAN NOT NULL DEFAULT false,
                        activado BOOLEAN NOT NULL DEFAULT true,
                        fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        usuario_creacion VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
                        fecha_modificacion TIMESTAMP WITH TIME ZONE,
                        usuario_modificacion VARCHAR(50)
                    );

                    CREATE TABLE IF NOT EXISTS configuracion.sucursales (
                        id_sucursal BIGSERIAL PRIMARY KEY,
                        id_empresa BIGINT NOT NULL,
                        nombre_sucursal VARCHAR(100) NOT NULL,
                        direccion VARCHAR(255),
                        telefono VARCHAR(50),
                        es_principal BOOLEAN NOT NULL DEFAULT false,
                        activado BOOLEAN NOT NULL DEFAULT true,
                        fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        usuario_creacion VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
                        fecha_modificacion TIMESTAMP WITH TIME ZONE,
                        usuario_modificacion VARCHAR(50)
                    );

                    CREATE TABLE IF NOT EXISTS configuracion.metodos_pago (
                        id_metodo_pago BIGSERIAL PRIMARY KEY,
                        codigo VARCHAR(20) NOT NULL,
                        nombre VARCHAR(100) NOT NULL,
                        es_efectivo BOOLEAN NOT NULL DEFAULT false,
                        id_tipo_documento_pago BIGINT,
                        activado BOOLEAN NOT NULL DEFAULT true,
                        fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        usuario_creacion VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
                        fecha_modificacion TIMESTAMP WITH TIME ZONE,
                        usuario_modificacion VARCHAR(50)
                    );

                    CREATE TABLE IF NOT EXISTS configuracion.configuraciones (
                        id_configuracion BIGSERIAL PRIMARY KEY,
                        clave VARCHAR(100) NOT NULL,
                        valor TEXT NOT NULL,
                        descripcion VARCHAR(255),
                        grupo VARCHAR(50),
                        activado BOOLEAN NOT NULL DEFAULT true,
                        fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        usuario_creacion VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
                        fecha_modificacion TIMESTAMP WITH TIME ZONE,
                        usuario_modificacion VARCHAR(50)
                    );
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216185859_RestoreMissingTables') THEN

                    INSERT INTO configuracion.tipos_comprobantes (codigo, nombre, mueve_stock, tipo_movimiento_stock, activado, usuario_creacion, fecha_creacion)
                    SELECT '01', 'FACTURA', false, 'NEUTRO', true, 'SYSTEM', NOW()
                    WHERE NOT EXISTS (SELECT 1 FROM configuracion.tipos_comprobantes WHERE codigo = '01');

                    INSERT INTO configuracion.tipos_comprobantes (codigo, nombre, mueve_stock, tipo_movimiento_stock, activado, usuario_creacion, fecha_creacion)
                    SELECT '03', 'BOLETA DE VENTA', false, 'NEUTRO', true, 'SYSTEM', NOW()
                    WHERE NOT EXISTS (SELECT 1 FROM configuracion.tipos_comprobantes WHERE codigo = '03');

                    INSERT INTO configuracion.impuestos (codigo, nombre, porcentaje, es_igv, activado, usuario_creacion, fecha_creacion)
                    SELECT '1000', 'IGV', 18.00, true, true, 'SYSTEM', NOW()
                    WHERE NOT EXISTS (SELECT 1 FROM configuracion.impuestos WHERE codigo = '1000');
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216185859_RestoreMissingTables') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260216185859_RestoreMissingTables', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216193650_NormalizeTableNamesV2') THEN
    ALTER TABLE IF EXISTS configuracion.tipos_comprobantes RENAME TO tipo_comprobante;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216193650_NormalizeTableNamesV2') THEN
    ALTER TABLE IF EXISTS configuracion.impuestos RENAME TO impuesto;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216193650_NormalizeTableNamesV2') THEN
    ALTER TABLE IF EXISTS configuracion.sucursales RENAME TO sucursal;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216193650_NormalizeTableNamesV2') THEN
    ALTER TABLE IF EXISTS configuracion.metodos_pago RENAME TO metodo_pago;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216193650_NormalizeTableNamesV2') THEN
    ALTER TABLE IF EXISTS configuracion."DOCUMENTOIDENTIDAD" RENAME TO tipo_documento;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216193650_NormalizeTableNamesV2') THEN
    ALTER TABLE IF EXISTS configuracion.documentoidentidad RENAME TO tipo_documento;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216193650_NormalizeTableNamesV2') THEN
    ALTER TABLE IF EXISTS configuracion."DOCUMENTOIDENTIDAD_DOCUMENTOCOMPROBANTE" RENAME TO regla_documento_comprobante;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216193650_NormalizeTableNamesV2') THEN
    ALTER TABLE IF EXISTS configuracion.documentoidentidad_documentocomprobante RENAME TO regla_documento_comprobante;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216193650_NormalizeTableNamesV2') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260216193650_NormalizeTableNamesV2', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216215851_SeedMatrixCompatibilidadSUNAT') THEN

                    INSERT INTO configuracion.tipo_comprobante (codigo, nombre, mueve_stock, tipo_movimiento_stock, activado, usuario_creacion, fecha_creacion)
                    SELECT '02', 'RECIBO POR HONORARIOS', false, 'NEUTRO', true, 'SYSTEM', NOW()
                    WHERE NOT EXISTS (SELECT 1 FROM configuracion.tipo_comprobante WHERE codigo = '02');

                    INSERT INTO configuracion.tipo_comprobante (codigo, nombre, mueve_stock, tipo_movimiento_stock, activado, usuario_creacion, fecha_creacion)
                    SELECT '04', 'LIQUIDACIÓN DE COMPRA', true, 'ENTRADA', true, 'SYSTEM', NOW()
                    WHERE NOT EXISTS (SELECT 1 FROM configuracion.tipo_comprobante WHERE codigo = '04');
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216215851_SeedMatrixCompatibilidadSUNAT') THEN

                    INSERT INTO configuracion.tipo_documento (codigo, nombre, longitud, es_numerico, estado, activado, fecha_creacion, usuario_creacion)
                    SELECT '0', 'SIN DOCUMENTO', 1, false, true, true, NOW(), 'SYSTEM'
                    WHERE NOT EXISTS (SELECT 1 FROM configuracion.tipo_documento WHERE codigo = '0');
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216215851_SeedMatrixCompatibilidadSUNAT') THEN
    DELETE FROM configuracion.regla_documento_comprobante;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216215851_SeedMatrixCompatibilidadSUNAT') THEN

                    -- RUC (6) -> FACTURA(01), BOLETA(03), LIQ.COMPRA(04), RECIBO HON.(02)
                    INSERT INTO configuracion.regla_documento_comprobante (codigo_documento, id_tipo_comprobante, activado, usuario_creacion, fecha_creacion)
                    SELECT '6', id_tipo_comprobante, true, 'SYSTEM', NOW() 
                    FROM configuracion.tipo_comprobante WHERE codigo IN ('01', '02', '03', '04');

                    -- DNI (1) -> BOLETA(03), RECIBO HON.(02)
                    INSERT INTO configuracion.regla_documento_comprobante (codigo_documento, id_tipo_comprobante, activado, usuario_creacion, fecha_creacion)
                    SELECT '1', id_tipo_comprobante, true, 'SYSTEM', NOW() 
                    FROM configuracion.tipo_comprobante WHERE codigo IN ('03', '02');

                    -- CARNÉ EXTRANJERÍA (4) -> BOLETA(03)
                    INSERT INTO configuracion.regla_documento_comprobante (codigo_documento, id_tipo_comprobante, activado, usuario_creacion, fecha_creacion)
                    SELECT '4', id_tipo_comprobante, true, 'SYSTEM', NOW() 
                    FROM configuracion.tipo_comprobante WHERE codigo IN ('03');

                    -- PASAPORTE (7) -> BOLETA(03)
                    INSERT INTO configuracion.regla_documento_comprobante (codigo_documento, id_tipo_comprobante, activado, usuario_creacion, fecha_creacion)
                    SELECT '7', id_tipo_comprobante, true, 'SYSTEM', NOW() 
                    FROM configuracion.tipo_comprobante WHERE codigo IN ('03');

                    -- SIN DOCUMENTO (0) -> BOLETA(03)
                    INSERT INTO configuracion.regla_documento_comprobante (codigo_documento, id_tipo_comprobante, activado, usuario_creacion, fecha_creacion)
                    SELECT '0', id_tipo_comprobante, true, 'SYSTEM', NOW() 
                    FROM configuracion.tipo_comprobante WHERE codigo IN ('03');
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216215851_SeedMatrixCompatibilidadSUNAT') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260216215851_SeedMatrixCompatibilidadSUNAT', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260217174701_AddModuleFlagsToTipoComprobante') THEN
    ALTER TABLE configuracion.tipo_comprobante ADD es_compra boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260217174701_AddModuleFlagsToTipoComprobante') THEN
    ALTER TABLE configuracion.tipo_comprobante ADD es_orden_compra boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260217174701_AddModuleFlagsToTipoComprobante') THEN
    ALTER TABLE configuracion.tipo_comprobante ADD es_venta boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260217174701_AddModuleFlagsToTipoComprobante') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260217174701_AddModuleFlagsToTipoComprobante', '8.0.0');
    END IF;
END $EF$;
COMMIT;

-- Fecha de vencimiento para control de cuentas por pagar
ALTER TABLE compras.compras
  ADD COLUMN fecha_vencimiento date
    COLLATE pg_catalog."default";
COMMENT ON COLUMN compras.compras.fecha_vencimiento IS 'Fecha de vencimiento para pago. Requerida para control de CxP.';

-- Desglose de bases imponibles para Registro de Compras SUNAT
ALTER TABLE compras.compras
  ADD COLUMN base_gravada numeric(12,2) NOT NULL DEFAULT 0.00;
COMMENT ON COLUMN compras.compras.base_gravada IS 'Suma de subtotales de items con afectacion G (gravados)';

ALTER TABLE compras.compras
  ADD COLUMN base_exonerada numeric(12,2) NOT NULL DEFAULT 0.00;
COMMENT ON COLUMN compras.compras.base_exonerada IS 'Suma de subtotales de items con afectacion E (exonerados)';

ALTER TABLE compras.compras
  ADD COLUMN base_inafecta numeric(12,2) NOT NULL DEFAULT 0.00;
COMMENT ON COLUMN compras.compras.base_inafecta IS 'Suma de subtotales de items con afectacion I (inafectos)';


-- Tipo de afectacion IGV por item, requerido para Registro de Compras SUNAT
-- G = Gravado con IGV
-- E = Exonerado de IGV
-- I = Inafecto al IGV
ALTER TABLE compras.detalle_compra
  ADD COLUMN afectacion_igv character varying(1) COLLATE pg_catalog."default" NOT NULL DEFAULT 'G';
COMMENT ON COLUMN compras.detalle_compra.afectacion_igv IS 'Afectacion IGV del item: G=Gravado, E=Exonerado, I=Inafecto. SUNAT PLE 8.1';

-- Constraint de validacion
ALTER TABLE compras.detalle_compra
  ADD CONSTRAINT chk_afectacion_igv CHECK (afectacion_igv::text = ANY (ARRAY['G'::character varying, 'E'::character varying, 'I'::character varying]::text[]));
-- AÃ±adir campo 'activado' a tabla 'sucursales'
ALTER TABLE configuracion.sucursal
    ADD COLUMN activado boolean NOT NULL DEFAULT true;

COMMENT ON COLUMN configuracion.sucursal.activado IS 'Indica si la sucursal estÃ¡ activa para su uso en operaciones del sistema. Agregado durante unificaciÃ³n del backend con PatrÃ³n B del Frontend.';
