CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260129221256_AgregarTiposComprobante') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'configuracion') THEN
            CREATE SCHEMA configuracion;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260129221256_AgregarTiposComprobante') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260129221256_AgregarTiposComprobante', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216155444_AddReglasDocumentosSUNAT') THEN
    DROP TABLE IF EXISTS configuracion."DOCUMENTOIDENTIDAD_DOCUMENTOCOMPROBANTE" CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216155444_AddReglasDocumentosSUNAT') THEN
    DROP TABLE IF EXISTS configuracion."DOCUMENTOIDENTIDAD" CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216155444_AddReglasDocumentosSUNAT') THEN
    CREATE TABLE configuracion."DOCUMENTOIDENTIDAD" (
        id_regla bigint GENERATED BY DEFAULT AS IDENTITY,
        codigo character varying(10) NOT NULL,
        nombre character varying(100) NOT NULL,
        longitud integer NOT NULL,
        es_numerico boolean NOT NULL,
        estado boolean NOT NULL,
        activado boolean NOT NULL,
        fecha_creacion timestamp with time zone NOT NULL,
        usuario_creacion character varying(50) NOT NULL,
        fecha_modificacion timestamp with time zone,
        usuario_modificacion character varying(50),
        CONSTRAINT pk_documentoidentidad PRIMARY KEY (id_regla)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216155444_AddReglasDocumentosSUNAT') THEN
    CREATE TABLE configuracion."DOCUMENTOIDENTIDAD_DOCUMENTOCOMPROBANTE" (
        id_relacion bigint GENERATED BY DEFAULT AS IDENTITY,
        codigo_documento character varying(10) NOT NULL,
        id_tipo_comprobante bigint NOT NULL,
        activado boolean NOT NULL,
        fecha_creacion timestamp with time zone NOT NULL,
        usuario_creacion character varying(50) NOT NULL,
        fecha_modificacion timestamp with time zone,
        usuario_modificacion character varying(50),
        CONSTRAINT pk_documentoidentidad_documentocomprobante PRIMARY KEY (id_relacion)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216155444_AddReglasDocumentosSUNAT') THEN
    CREATE INDEX ix_documentoidentidad_documentocomprobante_id_tipo_comprobante ON configuracion."DOCUMENTOIDENTIDAD_DOCUMENTOCOMPROBANTE" (id_tipo_comprobante);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216155444_AddReglasDocumentosSUNAT') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260216155444_AddReglasDocumentosSUNAT', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216160331_SeedReglasDocumentosSUNAT') THEN

                    INSERT INTO configuracion."DOCUMENTOIDENTIDAD" (codigo, nombre, longitud, es_numerico, estado, activado, fecha_creacion, usuario_creacion)
                    SELECT '1', 'DNI', 8, true, true, true, NOW(), 'SISTEMA'
                    WHERE NOT EXISTS (SELECT 1 FROM configuracion."DOCUMENTOIDENTIDAD" WHERE codigo = '1');
                    
                    INSERT INTO configuracion."DOCUMENTOIDENTIDAD" (codigo, nombre, longitud, es_numerico, estado, activado, fecha_creacion, usuario_creacion)
                    SELECT '6', 'RUC', 11, true, true, true, NOW(), 'SISTEMA'
                    WHERE NOT EXISTS (SELECT 1 FROM configuracion."DOCUMENTOIDENTIDAD" WHERE codigo = '6');

                    INSERT INTO configuracion."DOCUMENTOIDENTIDAD" (codigo, nombre, longitud, es_numerico, estado, activado, fecha_creacion, usuario_creacion)
                    SELECT '4', 'CARNET EXTRANJERIA', 12, false, true, true, NOW(), 'SISTEMA'
                    WHERE NOT EXISTS (SELECT 1 FROM configuracion."DOCUMENTOIDENTIDAD" WHERE codigo = '4');

                    INSERT INTO configuracion."DOCUMENTOIDENTIDAD" (codigo, nombre, longitud, es_numerico, estado, activado, fecha_creacion, usuario_creacion)
                    SELECT '7', 'PASAPORTE', 12, false, true, true, NOW(), 'SISTEMA'
                    WHERE NOT EXISTS (SELECT 1 FROM configuracion."DOCUMENTOIDENTIDAD" WHERE codigo = '7');
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216160331_SeedReglasDocumentosSUNAT') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260216160331_SeedReglasDocumentosSUNAT', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216185859_RestoreMissingTables') THEN

                    CREATE TABLE IF NOT EXISTS configuracion.tipos_comprobantes (
                        id_tipo_comprobante BIGSERIAL PRIMARY KEY,
                        codigo VARCHAR(10) NOT NULL,
                        nombre VARCHAR(100) NOT NULL,
                        mueve_stock BOOLEAN NOT NULL DEFAULT false,
                        tipo_movimiento_stock VARCHAR(20) NOT NULL DEFAULT 'DEPENDIENTE',
                        activado BOOLEAN NOT NULL DEFAULT true,
                        fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        usuario_creacion VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
                        fecha_modificacion TIMESTAMP WITH TIME ZONE,
                        usuario_modificacion VARCHAR(50)
                    );

                    CREATE TABLE IF NOT EXISTS configuracion.impuestos (
                        id_impuesto BIGSERIAL PRIMARY KEY,
                        codigo VARCHAR(10) NOT NULL,
                        nombre VARCHAR(100) NOT NULL,
                        porcentaje DECIMAL(5,2) NOT NULL DEFAULT 0,
                        es_igv BOOLEAN NOT NULL DEFAULT false,
                        activado BOOLEAN NOT NULL DEFAULT true,
                        fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        usuario_creacion VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
                        fecha_modificacion TIMESTAMP WITH TIME ZONE,
                        usuario_modificacion VARCHAR(50)
                    );

                    CREATE TABLE IF NOT EXISTS configuracion.sucursales (
                        id_sucursal BIGSERIAL PRIMARY KEY,
                        id_empresa BIGINT NOT NULL,
                        nombre_sucursal VARCHAR(100) NOT NULL,
                        direccion VARCHAR(255),
                        telefono VARCHAR(50),
                        es_principal BOOLEAN NOT NULL DEFAULT false,
                        activado BOOLEAN NOT NULL DEFAULT true,
                        fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        usuario_creacion VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
                        fecha_modificacion TIMESTAMP WITH TIME ZONE,
                        usuario_modificacion VARCHAR(50)
                    );

                    CREATE TABLE IF NOT EXISTS configuracion.metodos_pago (
                        id_metodo_pago BIGSERIAL PRIMARY KEY,
                        codigo VARCHAR(20) NOT NULL,
                        nombre VARCHAR(100) NOT NULL,
                        es_efectivo BOOLEAN NOT NULL DEFAULT false,
                        id_tipo_documento_pago BIGINT,
                        activado BOOLEAN NOT NULL DEFAULT true,
                        fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        usuario_creacion VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
                        fecha_modificacion TIMESTAMP WITH TIME ZONE,
                        usuario_modificacion VARCHAR(50)
                    );

                    CREATE TABLE IF NOT EXISTS configuracion.configuraciones (
                        id_configuracion BIGSERIAL PRIMARY KEY,
                        clave VARCHAR(100) NOT NULL,
                        valor TEXT NOT NULL,
                        descripcion VARCHAR(255),
                        grupo VARCHAR(50),
                        activado BOOLEAN NOT NULL DEFAULT true,
                        fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        usuario_creacion VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
                        fecha_modificacion TIMESTAMP WITH TIME ZONE,
                        usuario_modificacion VARCHAR(50)
                    );
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216185859_RestoreMissingTables') THEN

                    INSERT INTO configuracion.tipos_comprobantes (codigo, nombre, mueve_stock, tipo_movimiento_stock, activado, usuario_creacion, fecha_creacion)
                    SELECT '01', 'FACTURA', false, 'NEUTRO', true, 'SYSTEM', NOW()
                    WHERE NOT EXISTS (SELECT 1 FROM configuracion.tipos_comprobantes WHERE codigo = '01');

                    INSERT INTO configuracion.tipos_comprobantes (codigo, nombre, mueve_stock, tipo_movimiento_stock, activado, usuario_creacion, fecha_creacion)
                    SELECT '03', 'BOLETA DE VENTA', false, 'NEUTRO', true, 'SYSTEM', NOW()
                    WHERE NOT EXISTS (SELECT 1 FROM configuracion.tipos_comprobantes WHERE codigo = '03');

                    INSERT INTO configuracion.impuestos (codigo, nombre, porcentaje, es_igv, activado, usuario_creacion, fecha_creacion)
                    SELECT '1000', 'IGV', 18.00, true, true, 'SYSTEM', NOW()
                    WHERE NOT EXISTS (SELECT 1 FROM configuracion.impuestos WHERE codigo = '1000');
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216185859_RestoreMissingTables') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260216185859_RestoreMissingTables', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216193650_NormalizeTableNamesV2') THEN
    ALTER TABLE IF EXISTS configuracion.tipos_comprobantes RENAME TO tipo_comprobante;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216193650_NormalizeTableNamesV2') THEN
    ALTER TABLE IF EXISTS configuracion.impuestos RENAME TO impuesto;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216193650_NormalizeTableNamesV2') THEN
    ALTER TABLE IF EXISTS configuracion.sucursales RENAME TO sucursal;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216193650_NormalizeTableNamesV2') THEN
    ALTER TABLE IF EXISTS configuracion.metodos_pago RENAME TO metodo_pago;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216193650_NormalizeTableNamesV2') THEN
    ALTER TABLE IF EXISTS configuracion."DOCUMENTOIDENTIDAD" RENAME TO tipo_documento;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216193650_NormalizeTableNamesV2') THEN
    ALTER TABLE IF EXISTS configuracion.documentoidentidad RENAME TO tipo_documento;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216193650_NormalizeTableNamesV2') THEN
    ALTER TABLE IF EXISTS configuracion."DOCUMENTOIDENTIDAD_DOCUMENTOCOMPROBANTE" RENAME TO regla_documento_comprobante;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216193650_NormalizeTableNamesV2') THEN
    ALTER TABLE IF EXISTS configuracion.documentoidentidad_documentocomprobante RENAME TO regla_documento_comprobante;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216193650_NormalizeTableNamesV2') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260216193650_NormalizeTableNamesV2', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216215851_SeedMatrixCompatibilidadSUNAT') THEN

                    INSERT INTO configuracion.tipo_comprobante (codigo, nombre, mueve_stock, tipo_movimiento_stock, activado, usuario_creacion, fecha_creacion)
                    SELECT '02', 'RECIBO POR HONORARIOS', false, 'NEUTRO', true, 'SYSTEM', NOW()
                    WHERE NOT EXISTS (SELECT 1 FROM configuracion.tipo_comprobante WHERE codigo = '02');

                    INSERT INTO configuracion.tipo_comprobante (codigo, nombre, mueve_stock, tipo_movimiento_stock, activado, usuario_creacion, fecha_creacion)
                    SELECT '04', 'LIQUIDACIÓN DE COMPRA', true, 'ENTRADA', true, 'SYSTEM', NOW()
                    WHERE NOT EXISTS (SELECT 1 FROM configuracion.tipo_comprobante WHERE codigo = '04');
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216215851_SeedMatrixCompatibilidadSUNAT') THEN

                    INSERT INTO configuracion.tipo_documento (codigo, nombre, longitud, es_numerico, estado, activado, fecha_creacion, usuario_creacion)
                    SELECT '0', 'SIN DOCUMENTO', 1, false, true, true, NOW(), 'SYSTEM'
                    WHERE NOT EXISTS (SELECT 1 FROM configuracion.tipo_documento WHERE codigo = '0');
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216215851_SeedMatrixCompatibilidadSUNAT') THEN
    DELETE FROM configuracion.regla_documento_comprobante;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216215851_SeedMatrixCompatibilidadSUNAT') THEN

                    -- RUC (6) -> FACTURA(01), BOLETA(03), LIQ.COMPRA(04), RECIBO HON.(02)
                    INSERT INTO configuracion.regla_documento_comprobante (codigo_documento, id_tipo_comprobante, activado, usuario_creacion, fecha_creacion)
                    SELECT '6', id_tipo_comprobante, true, 'SYSTEM', NOW() 
                    FROM configuracion.tipo_comprobante WHERE codigo IN ('01', '02', '03', '04');

                    -- DNI (1) -> BOLETA(03), RECIBO HON.(02)
                    INSERT INTO configuracion.regla_documento_comprobante (codigo_documento, id_tipo_comprobante, activado, usuario_creacion, fecha_creacion)
                    SELECT '1', id_tipo_comprobante, true, 'SYSTEM', NOW() 
                    FROM configuracion.tipo_comprobante WHERE codigo IN ('03', '02');

                    -- CARNÉ EXTRANJERÍA (4) -> BOLETA(03)
                    INSERT INTO configuracion.regla_documento_comprobante (codigo_documento, id_tipo_comprobante, activado, usuario_creacion, fecha_creacion)
                    SELECT '4', id_tipo_comprobante, true, 'SYSTEM', NOW() 
                    FROM configuracion.tipo_comprobante WHERE codigo IN ('03');

                    -- PASAPORTE (7) -> BOLETA(03)
                    INSERT INTO configuracion.regla_documento_comprobante (codigo_documento, id_tipo_comprobante, activado, usuario_creacion, fecha_creacion)
                    SELECT '7', id_tipo_comprobante, true, 'SYSTEM', NOW() 
                    FROM configuracion.tipo_comprobante WHERE codigo IN ('03');

                    -- SIN DOCUMENTO (0) -> BOLETA(03)
                    INSERT INTO configuracion.regla_documento_comprobante (codigo_documento, id_tipo_comprobante, activado, usuario_creacion, fecha_creacion)
                    SELECT '0', id_tipo_comprobante, true, 'SYSTEM', NOW() 
                    FROM configuracion.tipo_comprobante WHERE codigo IN ('03');
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260216215851_SeedMatrixCompatibilidadSUNAT') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260216215851_SeedMatrixCompatibilidadSUNAT', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260217174701_AddModuleFlagsToTipoComprobante') THEN
    ALTER TABLE configuracion.tipo_comprobante ADD es_compra boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260217174701_AddModuleFlagsToTipoComprobante') THEN
    ALTER TABLE configuracion.tipo_comprobante ADD es_orden_compra boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260217174701_AddModuleFlagsToTipoComprobante') THEN
    ALTER TABLE configuracion.tipo_comprobante ADD es_venta boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260217174701_AddModuleFlagsToTipoComprobante') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260217174701_AddModuleFlagsToTipoComprobante', '8.0.0');
    END IF;
END $EF$;
COMMIT;

